# Bibliotecas

In [1]:
import pandas as pd

# Leitura e tratamento dos dados

DATA COM: É dada que se pode comprar para receber o pagamento referido na linha

DY: É o valor do dividendo sobre o valor da ação

In [4]:
planilha = pd.read_csv(r"C:\Users\luis.nascimento\Documents\Análises Financeiras\(Cru) FIIs rendimentos por data (2021-2025).csv")
planilha

       ATIVO          VALOR    DATA COM DATA PAGAMENTO        TIPO     DY
0     ARRI11  R$ 0,08018867  30/12/2020     08/01/2021  Rendimento  0,09%
1     BRCO11  R$ 0,55000000  30/12/2020     08/01/2021  Rendimento  0,48%
2     HSAF11  R$ 0,70000000  30/12/2020     08/01/2021  Rendimento  0,74%
3     HSML11  R$ 0,50000000  30/12/2020     08/01/2021  Rendimento  0,53%
4     LVBI11  R$ 0,47000000  30/12/2020     08/01/2021  Rendimento  0,39%
...      ...            ...         ...            ...         ...    ...
5582  RCRB11  R$ 0,92000000  29/08/2025     15/09/2025  Rendimento  0,70%
5583  VRTA11  R$ 0,85000000  29/08/2025     15/09/2025  Rendimento  1,12%
5584  VRTM11  R$ 0,09000000  29/08/2025     15/09/2025  Rendimento  1,31%
5585  MANA11  R$ 0,11000000  29/08/2025     19/09/2025  Rendimento  1,27%
5586  BCIA11  R$ 0,84000000  29/08/2025     26/09/2025  Rendimento  1,00%

[5587 rows x 6 columns]

In [5]:
planilha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5587 entries, 0 to 5586
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ATIVO           5587 non-null   object
 1   VALOR           5587 non-null   object
 2   DATA COM        5587 non-null   object
 3   DATA PAGAMENTO  5587 non-null   object
 4   TIPO            5587 non-null   object
 5   DY              5587 non-null   object
dtypes: object(6)
memory usage: 262.0+ KB

In [6]:
planilha["VALOR"] = planilha["VALOR"].apply(lambda x: x.replace("R$ ", ""))
# planilha["VALOR"] = planilha["VALOR"].apply(lambda x: float(x.split('.')[0] + '.' + x.split('.')[1][:2]))
planilha["DATA COM"] =  planilha["DATA COM"].apply(lambda x: pd.to_datetime(x.replace('/', '-'), format='%d-%m-%Y'))
planilha["DATA PAGAMENTO"] =  planilha["DATA PAGAMENTO"].apply(lambda x: pd.to_datetime(x.replace('/', '-'), format='%d-%m-%Y'))
planilha["DY"] =  planilha["DY"].apply(lambda x: x.replace('%', ''))
planilha

       ATIVO       VALOR   DATA COM DATA PAGAMENTO        TIPO    DY
0     ARRI11  0,08018867 2020-12-30     2021-01-08  Rendimento  0,09
1     BRCO11  0,55000000 2020-12-30     2021-01-08  Rendimento  0,48
2     HSAF11  0,70000000 2020-12-30     2021-01-08  Rendimento  0,74
3     HSML11  0,50000000 2020-12-30     2021-01-08  Rendimento  0,53
4     LVBI11  0,47000000 2020-12-30     2021-01-08  Rendimento  0,39
...      ...         ...        ...            ...         ...   ...
5582  RCRB11  0,92000000 2025-08-29     2025-09-15  Rendimento  0,70
5583  VRTA11  0,85000000 2025-08-29     2025-09-15  Rendimento  1,12
5584  VRTM11  0,09000000 2025-08-29     2025-09-15  Rendimento  1,31
5585  MANA11  0,11000000 2025-08-29     2025-09-19  Rendimento  1,27
5586  BCIA11  0,84000000 2025-08-29     2025-09-26  Rendimento  1,00

[5587 rows x 6 columns]

In [7]:
planilha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5587 entries, 0 to 5586
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ATIVO           5587 non-null   object
 1   VALOR           5587 non-null   object
 2   DATA COM        5587 non-null   datetime64[ns]
 3   DATA PAGAMENTO  5587 non-null   datetime64[ns]
 4   TIPO            5587 non-null   object
 5   DY              5587 non-null   object
dtypes: datetime64[ns](2), object(4)
memory usage: 262.0+ KB

# Análise dos dados

In [8]:
planilha.to_csv(r"C:\Users\luis.nascimento\Documents\Análises Financeiras\FIIs rendimentos por data (2021-2025).csv", index=False)

In [41]:
planilha.sort_values('DATA PAGAMENTO')

     ATIVO  VALOR   DATA COM DATA PAGAMENTO       TIPO    DY
0    BBDC3   0.01 2022-12-01     2023-01-02        JCP  0.13
1    BBDC4   0.01 2022-12-01     2023-01-02        JCP  0.12
2    HYPE3   0.30 2022-03-28     2023-01-02        JCP  0.80
3    HYPE3   0.30 2022-09-28     2023-01-02        JCP  0.68
4    HYPE3   0.30 2022-06-27     2023-01-02        JCP  0.80
..     ...    ...        ...            ...        ...   ...
878  CMIG4   0.09 2024-12-23     2025-12-30        JCP  0.87
880  HYPE3   0.09 2024-06-21     2025-12-31        JCP  0.34
881  HYPE3   0.09 2024-07-24     2025-12-31        JCP  0.35
879  HYPE3   0.09 2024-05-23     2025-12-31        JCP  0.32
882  PSSA3   0.47 2025-03-28     2025-12-31  Dividendo  1.20

[883 rows x 6 columns]

In [45]:
planilha.loc[planilha['ATIVO'] == 'SUZB3']

     ATIVO  VALOR   DATA COM DATA PAGAMENTO TIPO    DY
315  SUZB3   1.16 2023-12-07     2024-01-10  JCP  2.33
624  SUZB3   2.01 2024-12-16     2025-01-10  JCP  3.16

In [26]:
mes = planilha.loc[0, 'DATA PAGAMENTO'].month
ano = planilha.loc[0, 'DATA PAGAMENTO'].year
dia = planilha.loc[0, 'DATA PAGAMENTO'].day
print(dia, mes, ano)

2 1 2023

In [52]:
ano_mes = []
for i in planilha.index:
    ano_mes.append(str(planilha.loc[i, 'DATA PAGAMENTO'])[:7])
    
planilha['ANO_MES'] = ano_mes
planilha

     ATIVO  VALOR   DATA COM DATA PAGAMENTO       TIPO    DY  ANO_MES
0    BBDC3   0.01 2022-12-01     2023-01-02        JCP  0.13  2023-01
1    BBDC4   0.01 2022-12-01     2023-01-02        JCP  0.12  2023-01
2    HYPE3   0.30 2022-03-28     2023-01-02        JCP  0.80  2023-01
3    HYPE3   0.30 2022-09-28     2023-01-02        JCP  0.68  2023-01
4    HYPE3   0.30 2022-06-27     2023-01-02        JCP  0.80  2023-01
..     ...    ...        ...            ...        ...   ...      ...
878  CMIG4   0.09 2024-12-23     2025-12-30        JCP  0.87  2025-12
879  HYPE3   0.09 2024-05-23     2025-12-31        JCP  0.32  2025-12
880  HYPE3   0.09 2024-06-21     2025-12-31        JCP  0.34  2025-12
881  HYPE3   0.09 2024-07-24     2025-12-31        JCP  0.35  2025-12
882  PSSA3   0.47 2025-03-28     2025-12-31  Dividendo  1.20  2025-12

[883 rows x 7 columns]

In [53]:
planilha.loc[:, ['ATIVO', 'VALOR', 'ANO_MES']].groupby(['ATIVO', 'ANO_MES']).sum()

               VALOR
ATIVO ANO_MES
ABEV3 2023-12   0.73
      2024-12   0.24
      2025-01   0.42
      2025-04   0.12
      2025-07   0.12
...              ...
WEGE3 2025-03   0.44
      2025-08   0.34
YDUQ3 2023-12   0.27
      2024-05   0.27
      2025-05   0.57

[608 rows x 1 columns]

In [80]:
a = planilha.loc[:, ['ATIVO', 'VALOR', 'ANO_MES']].groupby(['ATIVO', 'ANO_MES']).agg(VALOR_TOTAL=('VALOR', 'sum'), QTD_MESES=('ANO_MES', 'nunique'))
a

b = planilha.loc[:, ['ATIVO', 'VALOR', 'ANO_MES']].groupby(['ATIVO', 'ANO_MES'])
for i, e in b:
    print(i, e)
# planilha.loc[:, ['ATIVO', 'ANO_MES']].groupby(['ATIVO']).agg(QTD_MESES=('ANO_MES', 'nunique'))

('ABEV3', '2023-12')      ATIVO  VALOR  ANO_MES
292  ABEV3   0.73  2023-12
('ABEV3', '2024-12')      ATIVO  VALOR  ANO_MES
609  ABEV3   0.24  2024-12
('ABEV3', '2025-01')      ATIVO  VALOR  ANO_MES
619  ABEV3   0.42  2025-01
('ABEV3', '2025-04')      ATIVO  VALOR  ANO_MES
705  ABEV3   0.12  2025-04
('ABEV3', '2025-07')      ATIVO  VALOR  ANO_MES
791  ABEV3   0.12  2025-07
('ABEV3', '2025-10')      ATIVO  VALOR  ANO_MES
851  ABEV3   0.12  2025-10
('ALOS3', '2023-05')      ATIVO  VALOR  ANO_MES
111  ALOS3   0.25  2023-05
('ALOS3', '2023-07')      ATIVO  VALOR  ANO_MES
160  ALOS3   0.25  2023-07
('ALOS3', '2024-05')      ATIVO  VALOR  ANO_MES
405  ALOS3   0.55  2024-05
('ALOS3', '2024-07')      ATIVO  VALOR  ANO_MES
474  ALOS3   0.55  2024-07
('ALOS3', '2024-10')      ATIVO  VALOR  ANO_MES
538  ALOS3   0.09  2024-10
('ALOS3', '2024-11')      ATIVO  VALOR  ANO_MES
547  ALOS3   0.09  2024-11
('ALOS3', '2024-12')      ATIVO  VALOR  ANO_MES
576  ALOS3   0.09  2024-12
('ALOS3', '2025-01')      ATIVO  VALOR  ANO_MES
620  ALOS3   0.12  2025-01
('ALOS3', '2025-02')      ATIVO  VALOR  ANO_MES
639  ALOS3   0.08  2025-02
640  ALOS3   0.00  2025-02
('ALOS3', '2025-03')      ATIVO  VALOR  ANO_MES
661  ALOS3   0.09  2025-03
('ALOS3', '2025-04')      ATIVO  VALOR  ANO_MES
704  ALOS3    0.1  2025-04
('ALOS3', '2025-05')      ATIVO  VALOR  ANO_MES
730  ALOS3    0.1  2025-05
('ALOS3', '2025-06')      ATIVO  VALOR  ANO_MES
768  ALOS3    0.1  2025-06
('ALOS3', '2025-07')      ATIVO  VALOR  ANO_MES
789  ALOS3    0.1  2025-07
('ALOS3', '2025-08')      ATIVO  VALOR  ANO_MES
809  ALOS3    0.1  2025-08
('ALOS3', '2025-09')      ATIVO  VALOR  ANO_MES
837  ALOS3    0.1  2025-09
('ASAI3', '2023-02')     ATIVO  VALOR  ANO_MES
33  ASAI3   0.03  2023-02
('ASAI3', '2023-06')      ATIVO  VALOR  ANO_MES
137  ASAI3   0.05  2023-06
('ASAI3', '2025-02')      ATIVO  VALOR  ANO_MES
654  ASAI3   0.09  2025-02
('ASAI3', '2025-06')      ATIVO  VALOR  ANO_MES
776  ASAI3   0.01  2025-06
('AURE3', '2023-05')     ATIVO  VALOR  ANO_MES
90  AURE3    1.5  2023-05
('AURE3', '2023-12')      ATIVO  VALOR  ANO_MES
281  AURE3    1.5  2023-12
('AURE3', '2024-03')      ATIVO  VALOR  ANO_MES
362  AURE3    0.4  2024-03
('AURE3', '2025-05')      ATIVO  VALOR  ANO_MES
728  AURE3   0.05  2025-05
('AZZA3', '2023-01')     ATIVO  VALOR  ANO_MES
24  AZZA3   0.74  2023-01
('AZZA3', '2023-09')      ATIVO  VALOR  ANO_MES
200  AZZA3   0.84  2023-09
('AZZA3', '2023-11')      ATIVO  VALOR  ANO_MES
250  AZZA3   0.29  2023-11
251  AZZA3   0.40  2023-11
252  AZZA3   0.38  2023-11
('AZZA3', '2024-07')      ATIVO  VALOR  ANO_MES
476  AZZA3   0.54  2024-07
('AZZA3', '2024-12')      ATIVO  VALOR  ANO_MES
588  AZZA3   0.57  2024-12
('B3SA3', '2023-01')     ATIVO  VALOR  ANO_MES
10  B3SA3   0.06  2023-01
('B3SA3', '2023-04')     ATIVO  VALOR  ANO_MES
70  B3SA3   0.03  2023-04
71  B3SA3   0.06  2023-04
('B3SA3', '2023-07')      ATIVO  VALOR  ANO_MES
154  B3SA3   0.06  2023-07
155  B3SA3   0.05  2023-07
('B3SA3', '2023-10')      ATIVO  VALOR  ANO_MES
221  B3SA3   0.04  2023-10
222  B3SA3   0.05  2023-10
('B3SA3', '2024-01')      ATIVO  VALOR  ANO_MES
312  B3SA3   0.05  2024-01
313  B3SA3   0.04  2024-01
('B3SA3', '2024-04')      ATIVO  VALOR  ANO_MES
379  B3SA3   0.06  2024-04
380  B3SA3   0.05  2024-04
('B3SA3', '2024-07')      ATIVO  VALOR  ANO_MES
468  B3SA3   0.05  2024-07
469  B3SA3   0.03  2024-07
('B3SA3', '2024-10')      ATIVO  VALOR  ANO_MES
535  B3SA3   0.06  2024-10
536  B3SA3   0.03  2024-10
('B3SA3', '2025-01')      ATIVO  VALOR  ANO_MES
621  B3SA3   0.06  2025-01
('B3SA3', '2025-04')      ATIVO  VALOR  ANO_MES
708  B3SA3   0.06  2025-04
('B3SA3', '2025-07')      ATIVO  VALOR  ANO_MES
792  B3SA3   0.07  2025-07
('BBAS3', '2023-03')     ATIVO  VALOR  ANO_MES
42  BBAS3   0.11  2023-03
43  BBAS3   0.28  2023-03
44  BBAS3   0.00  2023-03
45  BBAS3   0.00  2023-03
62  BBAS3   0.17  2023-03
('BBAS3', '2023-06')      ATIVO  VALOR  ANO_MES
128  BBAS3   0.32  2023-06
129  BBAS3   0.06  2023-06
140  BBAS3   0.16  2023-06
('BBAS3', '2023-08')      ATIVO  VALOR  ANO_MES
193  BBAS3   0.00  2023-08
194  BBAS3   0.00  2023-08
195  BBAS3   0.07  2023-08
196  BBAS3   0.32  2023-08
('BBAS3', '2023-09')      ATIVO  VALOR  ANO_MES
210  BBAS3   0.16  2023-09
('BBAS3', '2023-11')      ATIVO  VALOR  ANO_MES
256  BBAS3   0.05  2023-11
257  BBAS3   0.34  2023-11
('BBAS3', '2023-12')      ATIVO  VALOR  ANO_MES
293  BBAS3   0.17  2023-12
('BBAS3', '2024-02')      ATIVO  VALOR  ANO_MES
340  BBAS3   0.11  2024-02
341  BBAS3   0.00  2024-02
342  BBAS3   0.30  2024-02
('BBAS3', '2024-03')      ATIVO  VALOR  ANO_MES
369  BBAS3    0.2  2024-03
('BBAS3', '2024-06')      ATIVO  VALOR  ANO_MES
446  BBAS3   0.16  2024-06
447  BBAS3   0.29  2024-06
451  BBAS3   0.20  2024-06
('BBAS3', '2024-08')      ATIVO  VALOR  ANO_MES
504  BBAS3   0.00  2024-08
505  BBAS3   0.00  2024-08
506  BBAS3   0.15  2024-08
507  BBAS3   0.31  2024-08
('BBAS3', '2024-09')      ATIVO  VALOR  ANO_MES
527  BBAS3   0.18  2024-09
('BBAS3', '2024-12')      ATIVO  VALOR  ANO_MES
578  BBAS3   0.48  2024-12
597  BBAS3   0.17  2024-12
('BBAS3', '2025-03')      ATIVO  VALOR  ANO_MES
682  BBAS3   0.13  2025-03
683  BBAS3   0.34  2025-03
684  BBAS3   0.00  2025-03
685  BBAS3   0.00  2025-03
694  BBAS3   0.14  2025-03
('BBAS3', '2025-06')      ATIVO  VALOR  ANO_MES
769  BBAS3   0.33  2025-06
770  BBAS3   0.09  2025-06
('BBDC3', '2023-01')    ATIVO  VALOR  ANO_MES
0  BBDC3   0.01  2023-01
('BBDC3', '2023-02')     ATIVO  VALOR  ANO_MES
26  BBDC3   0.01  2023-02
('BBDC3', '2023-03')     ATIVO  VALOR  ANO_MES
37  BBDC3   0.01  2023-03
48  BBDC3   0.53  2023-03
('BBDC3', '2023-04')     ATIVO  VALOR  ANO_MES
63  BBDC3   0.01  2023-04
('BBDC3', '2023-05')     ATIVO  VALOR  ANO_MES
81  BBDC3   0.01  2023-05
('BBDC3', '2023-06')      ATIVO  VALOR  ANO_MES
124  BBDC3   0.01  2023-06
('BBDC3', '2023-07')      ATIVO  VALOR  ANO_MES
147  BBDC3   0.01  2023-07
152  BBDC3   0.17  2023-07
('BBDC3', '2023-08')      ATIVO  VALOR  ANO_MES
164  BBDC3   0.01  2023-08
('BBDC3', '2023-09')      ATIVO  VALOR  ANO_MES
201  BBDC3   0.01  2023-09
('BBDC3', '2023-10')      ATIVO  VALOR  ANO_MES
211  BBDC3   0.01  2023-10
('BBDC3', '2023-11')      ATIVO  VALOR  ANO_MES
232  BBDC3   0.01  2023-11
('BBDC3', '2023-12')      ATIVO  VALOR  ANO_MES
261  BBDC3   0.01  2023-12
('BBDC3', '2024-01')      ATIVO  VALOR  ANO_MES
303  BBDC3   0.17  2024-01
('BBDC3', '2024-02')      ATIVO  VALOR  ANO_MES
321  BBDC3   0.01  2024-02
('BBDC3', '2024-03')      ATIVO  VALOR  ANO_MES
344  BBDC3   0.01  2024-03
('BBDC3', '2024-04')      ATIVO  VALOR  ANO_MES
372  BBDC3   0.01  2024-04
('BBDC3', '2024-05')      ATIVO  VALOR  ANO_MES
395  BBDC3   0.01  2024-05
('BBDC3', '2024-06')      ATIVO  VALOR  ANO_MES
431  BBDC3   0.01  2024-06
452  BBDC3   0.44  2024-06
('BBDC3', '2024-07')      ATIVO  VALOR  ANO_MES
463  BBDC3   0.01  2024-07
('BBDC3', '2024-08')      ATIVO  VALOR  ANO_MES
484  BBDC3   0.01  2024-08
('BBDC3', '2024-09')      ATIVO  VALOR  ANO_MES
516  BBDC3   0.01  2024-09
('BBDC3', '2024-10')      ATIVO  VALOR  ANO_MES
529  BBDC3   0.01  2024-10
('BBDC3', '2024-11')      ATIVO  VALOR  ANO_MES
544  BBDC3   0.01  2024-11
('BBDC3', '2024-12')      ATIVO  VALOR  ANO_MES
572  BBDC3   0.01  2024-12
('BBDC3', '2025-01')      ATIVO  VALOR  ANO_MES
615  BBDC3   0.01  2025-01
634  BBDC3   0.35  2025-01
('BBDC3', '2025-02')      ATIVO  VALOR  ANO_MES
636  BBDC3   0.01  2025-02
('BBDC3', '2025-03')      ATIVO  VALOR  ANO_MES
655  BBDC3   0.01  2025-03
('BBDC3', '2025-04')      ATIVO  VALOR  ANO_MES
699  BBDC3   0.01  2025-04
720  BBDC3   0.17  2025-04
('BBDC3', '2025-05')      ATIVO  VALOR  ANO_MES
724  BBDC3   0.01  2025-05
('BBDC3', '2025-06')      ATIVO  VALOR  ANO_MES
765  BBDC3   0.01  2025-06
('BBDC3', '2025-07')      ATIVO  VALOR  ANO_MES
784  BBDC3   0.01  2025-07
803  BBDC3   0.26  2025-07
('BBDC3', '2025-08')      ATIVO  VALOR  ANO_MES
806  BBDC3   0.01  2025-08
('BBDC3', '2025-09')      ATIVO  VALOR  ANO_MES
834  BBDC3   0.01  2025-09
('BBDC3', '2025-10')      ATIVO  VALOR  ANO_MES
846  BBDC3   0.01  2025-10
('BBDC3', '2025-11')      ATIVO  VALOR  ANO_MES
855  BBDC3   0.01  2025-11
('BBDC3', '2025-12')      ATIVO  VALOR  ANO_MES
865  BBDC3   0.01  2025-12
('BBDC4', '2023-01')    ATIVO  VALOR  ANO_MES
1  BBDC4   0.01  2023-01
('BBDC4', '2023-02')     ATIVO  VALOR  ANO_MES
27  BBDC4   0.01  2023-02
('BBDC4', '2023-03')     ATIVO  VALOR  ANO_MES
38  BBDC4   0.01  2023-03
49  BBDC4   0.58  2023-03
('BBDC4', '2023-04')     ATIVO  VALOR  ANO_MES
64  BBDC4   0.01  2023-04
('BBDC4', '2023-05')     ATIVO  VALOR  ANO_MES
82  BBDC4   0.01  2023-05
('BBDC4', '2023-06')      ATIVO  VALOR  ANO_MES
125  BBDC4   0.01  2023-06
('BBDC4', '2023-07')      ATIVO  VALOR  ANO_MES
148  BBDC4   0.01  2023-07
153  BBDC4   0.19  2023-07
('BBDC4', '2023-08')      ATIVO  VALOR  ANO_MES
165  BBDC4   0.01  2023-08
('BBDC4', '2023-09')      ATIVO  VALOR  ANO_MES
202  BBDC4   0.01  2023-09
('BBDC4', '2023-10')      ATIVO  VALOR  ANO_MES
212  BBDC4   0.01  2023-10
('BBDC4', '2023-11')      ATIVO  VALOR  ANO_MES
233  BBDC4   0.01  2023-11
('BBDC4', '2023-12')      ATIVO  VALOR  ANO_MES
262  BBDC4   0.01  2023-12
('BBDC4', '2024-01')      ATIVO  VALOR  ANO_MES
304  BBDC4   0.19  2024-01
('BBDC4', '2024-02')      ATIVO  VALOR  ANO_MES
322  BBDC4   0.01  2024-02
('BBDC4', '2024-03')      ATIVO  VALOR  ANO_MES
345  BBDC4   0.01  2024-03
('BBDC4', '2024-04')      ATIVO  VALOR  ANO_MES
373  BBDC4   0.01  2024-04
('BBDC4', '2024-05')      ATIVO  VALOR  ANO_MES
396  BBDC4   0.01  2024-05
('BBDC4', '2024-06')      ATIVO  VALOR  ANO_MES
432  BBDC4   0.01  2024-06
453  BBDC4   0.49  2024-06
('BBDC4', '2024-07')      ATIVO  VALOR  ANO_MES
464  BBDC4   0.01  2024-07
('BBDC4', '2024-08')      ATIVO  VALOR  ANO_MES
485  BBDC4   0.01  2024-08
('BBDC4', '2024-09')      ATIVO  VALOR  ANO_MES
517  BBDC4   0.01  2024-09
('BBDC4', '2024-10')      ATIVO  VALOR  ANO_MES
530  BBDC4   0.01  2024-10
('BBDC4', '2024-11')      ATIVO  VALOR  ANO_MES
545  BBDC4   0.01  2024-11
('BBDC4', '2024-12')      ATIVO  VALOR  ANO_MES
573  BBDC4   0.01  2024-12
('BBDC4', '2025-01')      ATIVO  VALOR  ANO_MES
616  BBDC4   0.01  2025-01
635  BBDC4   0.39  2025-01
('BBDC4', '2025-02')      ATIVO  VALOR  ANO_MES
637  BBDC4   0.01  2025-02
('BBDC4', '2025-03')      ATIVO  VALOR  ANO_MES
656  BBDC4   0.01  2025-03
('BBDC4', '2025-04')      ATIVO  VALOR  ANO_MES
700  BBDC4   0.01  2025-04
721  BBDC4   0.19  2025-04
('BBDC4', '2025-05')      ATIVO  VALOR  ANO_MES
725  BBDC4   0.01  2025-05
('BBDC4', '2025-06')      ATIVO  VALOR  ANO_MES
766  BBDC4   0.01  2025-06
('BBDC4', '2025-07')      ATIVO  VALOR  ANO_MES
785  BBDC4   0.01  2025-07
804  BBDC4   0.29  2025-07
('BBDC4', '2025-08')      ATIVO  VALOR  ANO_MES
807  BBDC4   0.01  2025-08
('BBDC4', '2025-09')      ATIVO  VALOR  ANO_MES
835  BBDC4   0.01  2025-09
('BBDC4', '2025-10')      ATIVO  VALOR  ANO_MES
847  BBDC4   0.01  2025-10
('BBDC4', '2025-11')      ATIVO  VALOR  ANO_MES
856  BBDC4   0.01  2025-11
('BBDC4', '2025-12')      ATIVO  VALOR  ANO_MES
866  BBDC4   0.01  2025-12
('BBSE3', '2023-03')     ATIVO  VALOR  ANO_MES
39  BBSE3   1.83  2023-03
40  BBSE3   0.03  2023-03
('BBSE3', '2023-08')      ATIVO  VALOR  ANO_MES
187  BBSE3    1.6  2023-08
('BBSE3', '2024-02')      ATIVO  VALOR  ANO_MES
336  BBSE3   0.01  2024-02
337  BBSE3   1.24  2024-02
('BBSE3', '2024-08')      ATIVO  VALOR  ANO_MES
508  BBSE3   1.39  2024-08
('BBSE3', '2025-03')      ATIVO  VALOR  ANO_MES
657  BBSE3   0.04  2025-03
658  BBSE3   2.27  2025-03
('BBSE3', '2025-08')      ATIVO  VALOR  ANO_MES
824  BBSE3   1.94  2025-08
('BEEF3', '2023-05')     ATIVO  VALOR  ANO_MES
83  BEEF3   0.35  2023-05
('BEEF3', '2023-08')      ATIVO  VALOR  ANO_MES
180  BEEF3   0.19  2023-08
('BPAC11', '2023-02')      ATIVO  VALOR  ANO_MES
30  BPAC11   0.19  2023-02
31  BPAC11   0.14  2023-02
('BPAC11', '2023-08')       ATIVO  VALOR  ANO_MES
169  BPAC11    0.4  2023-08
('BPAC11', '2024-02')       ATIVO  VALOR  ANO_MES
325  BPAC11   0.14  2024-02
326  BPAC11   0.23  2024-02
('BPAC11', '2024-08')       ATIVO  VALOR  ANO_MES
491  BPAC11    0.4  2024-08
('BPAC11', '2025-02')       ATIVO  VALOR  ANO_MES
645  BPAC11   0.30  2025-02
646  BPAC11   0.14  2025-02
('BPAC11', '2025-08')       ATIVO  VALOR  ANO_MES
814  BPAC11    0.6  2025-08
('BRAP4', '2023-05')     ATIVO  VALOR  ANO_MES
91  BRAP4   0.17  2023-05
92  BRAP4   1.23  2023-05
('BRAP4', '2023-12')      ATIVO  VALOR  ANO_MES
268  BRAP4   0.60  2023-12
269  BRAP4   1.18  2023-12
('BRAP4', '2024-05')      ATIVO  VALOR  ANO_MES
406  BRAP4   0.81  2024-05
407  BRAP4   0.37  2024-05
('BRAP4', '2024-11')      ATIVO  VALOR  ANO_MES
555  BRAP4   0.89  2024-11
('BRAP4', '2025-05')      ATIVO  VALOR  ANO_MES
740  BRAP4   0.21  2025-05
741  BRAP4   0.91  2025-05
('BRAV3', '2024-07')      ATIVO  VALOR  ANO_MES
465  BRAV3   0.38  2024-07
('BRFS3', '2024-12')      ATIVO  VALOR  ANO_MES
577  BRFS3   0.58  2024-12
610  BRFS3   0.12  2024-12
('CMIG4', '2023-06')      ATIVO  VALOR  ANO_MES
141  CMIG4   0.10  2023-06
142  CMIG4   0.08  2023-06
143  CMIG4   0.09  2023-06
144  CMIG4   0.11  2023-06
145  CMIG4   0.05  2023-06
('CMIG4', '2023-12')      ATIVO  VALOR  ANO_MES
294  CMIG4   0.05  2023-12
299  CMIG4   0.08  2023-12
300  CMIG4   0.10  2023-12
301  CMIG4   0.09  2023-12
302  CMIG4   0.11  2023-12
('CMIG4', '2024-06')      ATIVO  VALOR  ANO_MES
458  CMIG4   0.09  2024-06
459  CMIG4   0.09  2024-06
460  CMIG4   0.09  2024-06
461  CMIG4   0.12  2024-06
462  CMIG4   0.30  2024-06
('CMIG4', '2024-08')      ATIVO  VALOR  ANO_MES
509  CMIG4   0.49  2024-08
('CMIG4', '2024-12')      ATIVO  VALOR  ANO_MES
598  CMIG4   0.12  2024-12
599  CMIG4   0.30  2024-12
600  CMIG4   0.09  2024-12
601  CMIG4   0.09  2024-12
602  CMIG4   0.09  2024-12
('CMIG4', '2025-06')      ATIVO  VALOR  ANO_MES
779  CMIG4   0.08  2025-06
780  CMIG4   0.08  2025-06
781  CMIG4   0.07  2025-06
782  CMIG4   0.09  2025-06
783  CMIG4   0.32  2025-06
('CMIG4', '2025-12')      ATIVO  VALOR  ANO_MES
875  CMIG4   0.07  2025-12
876  CMIG4   0.08  2025-12
877  CMIG4   0.32  2025-12
878  CMIG4   0.09  2025-12
('CMIN3', '2023-05')      ATIVO  VALOR  ANO_MES
98   CMIN3   0.01  2023-05
99   CMIN3   0.11  2023-05
100  CMIN3   0.28  2023-05
101  CMIN3   0.05  2023-05
('CMIN3', '2023-11')      ATIVO  VALOR  ANO_MES
253  CMIN3   0.24  2023-11
('CMIN3', '2024-05')      ATIVO  VALOR  ANO_MES
421  CMIN3   0.07  2024-05
422  CMIN3   0.18  2024-05
('CMIN3', '2024-12')      ATIVO  VALOR  ANO_MES
611  CMIN3   0.43  2024-12
612  CMIN3   0.02  2024-12
613  CMIN3   0.08  2024-12
('CMIN3', '2025-07')      ATIVO  VALOR  ANO_MES
794  CMIN3   0.03  2025-07
795  CMIN3   0.03  2025-07
796  CMIN3   0.20  2025-07
('COGN3', '2025-05')      ATIVO  VALOR  ANO_MES
762  COGN3   0.06  2025-05
('CPFE3', '2023-05')     ATIVO  VALOR  ANO_MES
96  CPFE3   0.86  2023-05
('CPFE3', '2023-06')      ATIVO  VALOR  ANO_MES
136  CPFE3   0.54  2023-06
('CPFE3', '2023-10')      ATIVO  VALOR  ANO_MES
227  CPFE3   0.26  2023-10
('CPFE3', '2023-11')      ATIVO  VALOR  ANO_MES
242  CPFE3   0.17  2023-11
243  CPFE3   0.43  2023-11
258  CPFE3   0.14  2023-11
('CPFE3', '2023-12')      ATIVO  VALOR  ANO_MES
273  CPFE3   0.30  2023-12
282  CPFE3   0.15  2023-12
('CPFE3', '2024-05')      ATIVO  VALOR  ANO_MES
403  CPFE3   1.19  2024-05
('CPFE3', '2024-06')      ATIVO  VALOR  ANO_MES
454  CPFE3   0.37  2024-06
('CPFE3', '2024-07')      ATIVO  VALOR  ANO_MES
479  CPFE3   0.08  2024-07
('CPFE3', '2024-08')      ATIVO  VALOR  ANO_MES
510  CPFE3   0.17  2024-08
('CPFE3', '2024-09')      ATIVO  VALOR  ANO_MES
528  CPFE3    0.3  2024-09
('CPFE3', '2024-12')      ATIVO  VALOR  ANO_MES
595  CPFE3   0.61  2024-12
('CPFE3', '2025-06')      ATIVO  VALOR  ANO_MES
777  CPFE3   0.78  2025-06
('CPFE3', '2025-07')      ATIVO  VALOR  ANO_MES
801  CPFE3   0.43  2025-07
('CPFE3', '2025-08')      ATIVO  VALOR  ANO_MES
823  CPFE3   0.32  2025-08
('CPLE6', '2023-06')      ATIVO  VALOR  ANO_MES
146  CPLE6   0.14  2023-06
('CPLE6', '2023-11')      ATIVO  VALOR  ANO_MES
259  CPLE6   0.15  2023-11
('CPLE6', '2024-06')      ATIVO  VALOR  ANO_MES
455  CPLE6   0.17  2024-06
456  CPLE6   0.04  2024-06
('CPLE6', '2024-11')      ATIVO  VALOR  ANO_MES
568  CPLE6   0.07  2024-11
569  CPLE6   0.09  2024-11
('CPLE6', '2024-12')      ATIVO  VALOR  ANO_MES
592  CPLE6    0.2  2024-12
('CPLE6', '2025-05')      ATIVO  VALOR  ANO_MES
742  CPLE6   0.43  2025-05
('CSAN3', '2023-05')      ATIVO  VALOR  ANO_MES
119  CSAN3   0.42  2023-05
('CSAN3', '2024-06')      ATIVO  VALOR  ANO_MES
457  CSAN3   0.45  2024-06
('CSNA3', '2023-05')      ATIVO  VALOR  ANO_MES
102  CSNA3   0.52  2023-05
103  CSNA3   0.63  2023-05
104  CSNA3   0.58  2023-05
('CSNA3', '2023-11')      ATIVO  VALOR  ANO_MES
254  CSNA3   0.74  2023-11
('CSNA3', '2024-05')      ATIVO  VALOR  ANO_MES
425  CSNA3   0.71  2024-05
('CSNA3', '2024-11')      ATIVO  VALOR  ANO_MES
565  CSNA3   0.55  2024-11
('CURY3', '2023-02')     ATIVO  VALOR  ANO_MES
32  CURY3    0.2  2023-02
('CURY3', '2023-05')      ATIVO  VALOR  ANO_MES
112  CURY3   0.06  2023-05
('CURY3', '2023-10')      ATIVO  VALOR  ANO_MES
218  CURY3   0.51  2023-10
('CURY3', '2024-05')      ATIVO  VALOR  ANO_MES
404  CURY3    0.4  2024-05
('CURY3', '2024-07')      ATIVO  VALOR  ANO_MES
472  CURY3   0.91  2024-07
('CURY3', '2024-10')      ATIVO  VALOR  ANO_MES
543  CURY3   0.34  2024-10
('CURY3', '2025-02')      ATIVO  VALOR  ANO_MES
647  CURY3    0.6  2025-02
('CURY3', '2025-05')      ATIVO  VALOR  ANO_MES
731  CURY3   0.26  2025-05
732  CURY3   0.26  2025-05
('CXSE3', '2023-05')     ATIVO  VALOR  ANO_MES
87  CXSE3   0.50  2023-05
88  CXSE3   0.01  2023-05
('CXSE3', '2023-11')      ATIVO  VALOR  ANO_MES
235  CXSE3    0.5  2023-11
('CXSE3', '2024-05')      ATIVO  VALOR  ANO_MES
399  CXSE3   0.01  2024-05
400  CXSE3   0.55  2024-05
('CXSE3', '2024-08')      ATIVO  VALOR  ANO_MES
492  CXSE3   0.28  2024-08
('CXSE3', '2024-11')      ATIVO  VALOR  ANO_MES
554  CXSE3   0.23  2024-11
('CXSE3', '2025-01')      ATIVO  VALOR  ANO_MES
629  CXSE3   0.31  2025-01
('CXSE3', '2025-05')      ATIVO  VALOR  ANO_MES
743  CXSE3   0.32  2025-05
('CXSE3', '2025-08')      ATIVO  VALOR  ANO_MES
815  CXSE3   0.31  2025-08
('CXSE3', '2025-11')      ATIVO  VALOR  ANO_MES
858  CXSE3   0.32  2025-11
('CYRE3', '2023-08')      ATIVO  VALOR  ANO_MES
179  CYRE3   0.51  2023-08
('CYRE3', '2023-12')      ATIVO  VALOR  ANO_MES
280  CYRE3   0.33  2023-12
('CYRE3', '2024-11')      ATIVO  VALOR  ANO_MES
561  CYRE3   0.59  2024-11
('DIRR3', '2023-01')    ATIVO  VALOR  ANO_MES
9  DIRR3   0.23  2023-01
('DIRR3', '2024-01')      ATIVO  VALOR  ANO_MES
307  DIRR3   0.15  2024-01
('DIRR3', '2024-07')      ATIVO  VALOR  ANO_MES
475  DIRR3   0.53  2024-07
('DIRR3', '2025-01')      ATIVO  VALOR  ANO_MES
627  DIRR3   0.15  2025-01
628  DIRR3   0.42  2025-01
('DIRR3', '2025-07')      ATIVO  VALOR  ANO_MES
790  DIRR3   0.66  2025-07
('EGIE3', '2023-07')      ATIVO  VALOR  ANO_MES
161  EGIE3   0.24  2023-07
('EGIE3', '2023-09')      ATIVO  VALOR  ANO_MES
209  EGIE3   1.78  2023-09
('EGIE3', '2023-12')      ATIVO  VALOR  ANO_MES
287  EGIE3   0.94  2023-12
('EGIE3', '2024-07')      ATIVO  VALOR  ANO_MES
480  EGIE3   1.21  2024-07
481  EGIE3   0.17  2024-07
('EGIE3', '2025-02')      ATIVO  VALOR  ANO_MES
641  EGIE3    0.3  2025-02
('EGIE3', '2025-05')      ATIVO  VALOR  ANO_MES
757  EGIE3   1.14  2025-05
('EGIE3', '2025-12')      ATIVO  VALOR  ANO_MES
874  EGIE3   0.87  2025-12
('ELET3', '2023-05')      ATIVO  VALOR  ANO_MES
113  ELET3   0.22  2023-05
('ELET3', '2024-05')      ATIVO  VALOR  ANO_MES
401  ELET3    0.4  2024-05
('ELET3', '2025-01')      ATIVO  VALOR  ANO_MES
625  ELET3   0.86  2025-01
('ELET3', '2025-05')      ATIVO  VALOR  ANO_MES
738  ELET3   0.89  2025-05
('ELET3', '2025-08')      ATIVO  VALOR  ANO_MES
826  ELET3   1.75  2025-08
('ELET6', '2023-05')      ATIVO  VALOR  ANO_MES
114  ELET6   1.49  2023-05
('ELET6', '2024-05')      ATIVO  VALOR  ANO_MES
402  ELET6   1.82  2024-05

In [ ]:
planilha.loc[:, ['ATIVO', 'VALOR', 'ANO_MES']].groupby(['ATIVO', 'ANO_MES']).agg(VALOR_TOTAL=('VALOR', 'sum'), QTD_MESES=('ANO_MES', 'nunique')).

In [66]:
resumo = (
    planilha
    .groupby(['ATIVO', 'ANO_MES'])
    .agg(VALOR=('VALOR', 'sum'))
    .reset_index()
)

# agora conta quantos ANO_MES cada ATIVO tem
resumo['QTD_MESES'] = resumo.groupby('ATIVO')['ANO_MES'].transform('nunique')
resumo

     ATIVO  ANO_MES  VALOR  QTD_MESES
0    ABEV3  2023-12   0.73          6
1    ABEV3  2024-12   0.24          6
2    ABEV3  2025-01   0.42          6
3    ABEV3  2025-04   0.12          6
4    ABEV3  2025-07   0.12          6
..     ...      ...    ...        ...
603  WEGE3  2025-03   0.44          6
604  WEGE3  2025-08   0.34          6
605  YDUQ3  2023-12   0.27          3
606  YDUQ3  2024-05   0.27          3
607  YDUQ3  2025-05   0.57          3

[608 rows x 4 columns]

In [64]:
resumo.loc[resumo['ATIVO'] == 'ALOS3']

    ATIVO  ANO_MES  VALOR  QTD_MESES
6   ALOS3  2023-05   0.25         16
7   ALOS3  2023-07   0.25         16
8   ALOS3  2024-05   0.55         16
9   ALOS3  2024-07   0.55         16
10  ALOS3  2024-10   0.09         16
11  ALOS3  2024-11   0.09         16
12  ALOS3  2024-12   0.09         16
13  ALOS3  2025-01   0.12         16
14  ALOS3  2025-02   0.08         16
15  ALOS3  2025-03   0.09         16
16  ALOS3  2025-04   0.10         16
17  ALOS3  2025-05   0.10         16
18  ALOS3  2025-06   0.10         16
19  ALOS3  2025-07   0.10         16
20  ALOS3  2025-08   0.10         16
21  ALOS3  2025-09   0.10         16

In [94]:
lista_ano = []
for i in planilha.index:
    lista_ano.append(planilha.loc[i, 'DATA PAGAMENTO'].year)
planilha["ANO"] = lista_ano

In [95]:
planilha.sort_values(['ATIVO','DATA PAGAMENTO'])

     ATIVO  VALOR   DATA COM DATA PAGAMENTO       TIPO    DY  ANO_MES   ANO
292  ABEV3   0.73 2023-12-19     2023-12-28        JCP  4.95  2023-12  2023
609  ABEV3   0.24 2024-12-19     2024-12-30        JCP  1.92  2024-12  2024
619  ABEV3   0.42 2024-12-19     2025-01-07  Dividendo  3.31  2025-01  2025
705  ABEV3   0.12 2025-03-14     2025-04-04  Dividendo  0.94  2025-04  2025
791  ABEV3   0.12 2025-05-15     2025-07-07  Dividendo  0.90  2025-07  2025
..     ...    ...        ...            ...        ...   ...      ...   ...
812  WEGE3   0.09 2025-06-20     2025-08-13        JCP  0.23  2025-08  2025
813  WEGE3   0.08 2025-03-21     2025-08-13        JCP  0.17  2025-08  2025
270  YDUQ3   0.27 2023-08-18     2023-12-05  Dividendo  1.24  2023-12  2023
427  YDUQ3   0.27 2024-04-26     2024-05-29  Dividendo  1.79  2024-05  2024
735  YDUQ3   0.57 2025-04-28     2025-05-08  Dividendo  3.91  2025-05  2025

[883 rows x 8 columns]

In [121]:
lista_ativos = []
lista_qtd_2023 = []
lista_qtd_2024 = []
lista_qtd_2025 = []

lista_total_2023 = []
lista_total_2024 = []
lista_total_2025 = []

for i in planilha.index:
    ativo = planilha.loc[i, 'ATIVO']
    if ativo not in lista_ativos: 
        lista_ativos.append(ativo)
        df_aux = planilha.loc[planilha['ATIVO'] == ativo]
        # df_aux.sort_values("ANO_MES")
        lista_qtd_2023.append(len(pd.unique(df_aux.loc[df_aux["ANO"] == 2023]["ANO_MES"])))
        lista_qtd_2024.append(len(pd.unique(df_aux.loc[df_aux["ANO"] == 2024]["ANO_MES"])))
        lista_qtd_2025.append(len(pd.unique(df_aux.loc[df_aux["ANO"] == 2025]["ANO_MES"])))

        lista_total_2023.append(sum(df_aux.loc[df_aux["ANO"] == 2023]["VALOR"]))
        lista_total_2024.append(sum(df_aux.loc[df_aux["ANO"] == 2024]["VALOR"]))
        lista_total_2025.append(sum(df_aux.loc[df_aux["ANO"] == 2025]["VALOR"]))
    
df_ativos = pd.DataFrame({"Ativo": lista_ativos,
                         "Quantidade em 2023": lista_qtd_2023,
                         "Quantidade em 2024": lista_qtd_2024,
                         "Quantidade em 2025": lista_qtd_2025,
                         "Total pago em 2023": lista_total_2023,
                         "Total pago em 2024": lista_total_2024,
                         "Total pago em 2025": lista_total_2025})


df_ativos
# ativo_ano.append(df_aux["DATA PAGAMENTO"].year)
# ativo_ano.append(df_aux["DATA PAGAMENTO"].year)

,Ativo,Quantidade em 2023,Quantidade em 2024,Quantidade em 2025,Total pago em 2023,Total pago em 2024,Total pago em 2025
0,BBDC3,12,12,12,0.82,0.72,0.90
1,BBDC4,12,12,12,0.89,0.79,0.99
2,HYPE3,1,1,1,1.20,1.20,0.27
3,ITSA4,6,6,6,0.53,0.82,1.01
4,ITUB4,12,12,12,1.12,2.23,2.97
...,...,...,...,...,...,...,...
70,BRFS3,0,1,0,0.00,0.70,0.00
71,MRFG3,0,1,0,0.00,2.82,0.00
72,MGLU3,0,0,1,0.00,0.00,0.30
73,EMBR3,0,0,1,0.00,0.00,0.07
74,COGN3,0,0,1,0.00,0.00,0.06

In [122]:
df_ativos.to_csv(r"C:\Users\luis.nascimento\Documents\Análises Financeiras\Ativos.csv" , index=False)

In [ ]:
# lista_valor_mes = []
# lista_qtd_mes = []

# qtd_mes = 0
# valor = 0
# ativo = ''
# ano_mes = ''
# for i in planilha.index:
#     ativo_aux = planilha.iloc[i, 'ATIVO']
#     ano_mes_aux = planilha.iloc[i, 'ANO_MES']

#     if ativo != ativo_aux:
#         ativo = ativo_aux
#         qtd_mes = 0
        
    
#     if ano_mes != ano_mes_aux:
#         ano_mes = ano_mes_aux
#         valor = 0