# Bibliotecas

In [317]:
import pandas as pd

# Ativos da Carteira

In [348]:
df_ativos = pd.read_csv('Dados Modelados/Ativos.csv')
lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XPML11",
    "XPCI11"

]

lista_index = []
for i in df_ativos.index:
    if df_ativos.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_ativos = df_ativos.loc[lista_index, :]
df_ativos.index = range(0, len(df_ativos))
df_ativos['Tipo'] = "Ação"
df_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação

In [349]:
df_fiis = pd.read_csv('Dados Modelados/FIIs.csv')

lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XPML11",
    "XPCI11"

]

lista_index = []
for i in df_fiis.index:
    if df_fiis.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_fiis = df_fiis.loc[lista_index, :]
df_fiis.index = range(0, len(df_fiis))
df_fiis['Tipo'] = "FII"
df_fiis

    ATIVO                 SETOR    INDUSTRIA Tipo
0  KNCR11       REIT - Mortgage  Real Estate  FII
1  HGLG11    REIT - Diversified  Real Estate  FII
2  XPCI11       REIT - Mortgage  Real Estate  FII
3  XPML11         REIT - Retail  Real Estate  FII
4  HTMX11  REIT - Hotel & Motel  Real Estate  FII

In [350]:
df_carteira_ativos = pd.concat([df_ativos, df_fiis])
df_carteira_ativos.index = range(0, len(df_carteira_ativos))
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII

In [351]:
acoes = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "Ação"]['ATIVO'].values
acoes.sort()
print(acoes)

fundos = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "FII"]['ATIVO'].values
fundos.sort()
print(fundos)

['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']

In [352]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1
}

balanco_ativos = []
for i in df_carteira_ativos.index:
    balanco_ativos.append(
        balanco[df_carteira_ativos.loc[[i], "ATIVO"].values[0]]
    )

df_carteira_ativos["Balanço de Cotas"] = balanco_ativos
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação,1
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação,1
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação,10
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação,1
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII,1
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII,1
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII,1

In [323]:
df_carteira_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Histórico

In [353]:
df_ativos = pd.read_csv('Dados Modelados/historico_Ativos.csv')
df_ativos = df_ativos.loc[df_ativos["Ativo"].isin(lista_ativos_selecionados)]
# df_ativos.index = range(0, len(df_ativos))
# df_ativos['Tipo Ativo'] = "Ação"
df_ativos

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
1098,24.350000,26.049999,23.610001,23.680000,88234500,15.714323,0.000000,NaN,BBSE3,01-10-2020
1099,23.680000,29.799999,23.680000,28.559999,120982300,18.952745,0.000000,NaN,BBSE3,01-11-2020
1100,29.000000,30.760000,28.260000,29.629999,70198700,19.662809,0.000000,NaN,BBSE3,01-12-2020
1101,29.629999,30.450001,27.660000,27.660000,86915800,18.355495,0.000000,NaN,BBSE3,01-01-2021
1102,28.000000,29.000000,25.430000,25.430000,89982600,16.875643,0.476121,NaN,BBSE3,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
2743,35.360001,35.529999,33.669998,34.930000,31750500,34.043571,0.000000,NaN,TAEE11,01-06-2025
2744,34.810001,35.169998,33.160000,33.360001,26490900,32.513416,0.000000,NaN,TAEE11,01-07-2025
2745,33.560001,34.919998,32.840000,34.869999,47238700,33.985092,0.869171,NaN,TAEE11,01-08-2025
2746,34.880001,35.220001,34.180000,34.900002,10775000,34.900002,0.000000,NaN,TAEE11,01-09-2025
2747,34.950001,35.150002,34.849998,34.980000,750000,34.980000,0.000000,NaN,TAEE11,11-09-2025

In [354]:
df_fiis = pd.read_csv('Dados Modelados/historico_Fii.csv')
df_fiis = df_fiis.loc[df_fiis["Ativo"].isin(lista_ativos_selecionados)]
# df_fiis.index = range(0, len(df_fiis))
# df_fiis['Tipo Ativo'] = "FII"
df_fiis

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
674,89.930000,94.480003,88.019997,91.949997,913427.0,58.732109,0.00,NaN,KNCR11,01-10-2020
675,91.949997,92.989998,87.910004,88.699997,863036.0,56.656181,0.00,NaN,KNCR11,01-11-2020
676,88.250000,88.599998,85.500000,87.050003,1348549.0,55.602295,0.00,NaN,KNCR11,01-12-2020
677,87.050003,89.769997,86.699997,88.820000,832932.0,56.732868,0.00,NaN,KNCR11,01-01-2021
678,88.699997,91.489998,87.000000,89.410004,924011.0,57.109722,0.00,NaN,KNCR11,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
5210,141.600006,147.000000,140.600006,145.300003,78781.0,139.966797,1.54,NaN,HTMX11,01-06-2025
5211,145.160004,146.169998,141.410004,145.470001,71302.0,141.689133,1.50,NaN,HTMX11,01-07-2025
5212,141.020004,143.699997,139.000000,139.869995,75358.0,137.655762,1.22,NaN,HTMX11,01-08-2025
5213,138.949997,139.000000,136.500000,138.399994,48631.0,137.361023,1.05,NaN,HTMX11,01-09-2025
5214,0.000000,0.000000,0.000000,138.399994,0.0,138.399994,0.00,NaN,HTMX11,15-09-2025

In [355]:
df_historico = pd.concat([df_ativos, df_fiis])
df_historico = df_historico.filter(["Ativo", "Data", "close"])
df_historico.rename(columns={"close": "Valor"}, inplace=True)
df_historico["Natureza"] = ["Histórico de Preço"] * len(df_historico)
df_historico["Data"] = pd.to_datetime(df_historico["Data"], format="%d-%m-%Y")
df_historico.index = range(0, len(df_historico))
df_historico

      Ativo       Data       Valor            Natureza
0     BBSE3 2020-10-01   23.680000  Histórico de Preço
1     BBSE3 2020-11-01   28.559999  Histórico de Preço
2     BBSE3 2020-12-01   29.629999  Histórico de Preço
3     BBSE3 2021-01-01   27.660000  Histórico de Preço
4     BBSE3 2021-02-01   25.430000  Histórico de Preço
..      ...        ...         ...                 ...
537  HTMX11 2025-06-01  145.300003  Histórico de Preço
538  HTMX11 2025-07-01  145.470001  Histórico de Preço
539  HTMX11 2025-08-01  139.869995  Histórico de Preço
540  HTMX11 2025-09-01  138.399994  Histórico de Preço
541  HTMX11 2025-09-15  138.399994  Histórico de Preço

[542 rows x 4 columns]

In [356]:
df_historico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Ativo     542 non-null    object
 1   Data      542 non-null    datetime64[ns]
 2   Valor     542 non-null    float64
 3   Natureza  542 non-null    object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 17.1+ KB

## Aquisição

In [328]:
df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao["Natureza"] = ["Aquisição"] * len(df_aquisicao)
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono   Natureza
0    PETR4 2024-04-01   32.00                1    Luis  Aquisição
1    PETR4 2024-08-01   31.00                2    Luis  Aquisição
2    PETR4 2024-11-01   29.31                3    Luis  Aquisição
3    VALE3 2024-11-01   34.87                2    Luis  Aquisição
4   TAEE11 2025-07-01   28.96                1    Luis  Aquisição
6    PETR4 2025-07-01   32.87                2  Heitor  Aquisição
7    PETR4 2025-07-01   31.79                3  Heitor  Aquisição
8    VALE3 2025-08-01   33.89                2  Heitor  Aquisição
9   HGLG11 2025-08-01  152.89                1  Heitor  Aquisição
5    PETR4 2025-09-01   31.09                1    Luis  Aquisição
10   PETR4 2025-09-01   31.34                1  Heitor  Aquisição
11   PETR4 2025-09-01   31.75                2  Heitor  Aquisição

In [329]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            12 non-null     object
 1   Data             12 non-null     datetime64[ns]
 2   Valor            12 non-null     float64
 3   Número de Cotas  12 non-null     int64
 4   Dono             12 non-null     object
 5   Natureza         12 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 672.0+ bytes

### Acumula cotas e agrupa aquisições no mesmo dia

In [330]:
# Acumula as cotas por ativo e dono

dic_cotas_acum = {
    "Heitor": {},
    "Luis": {}
}

lista_cotas_acum = []

for i in df_aquisicao.index:
    ativo = df_aquisicao.loc[i, "Ativo"]
    cotas = df_aquisicao.loc[i, "Número de Cotas"]
    dono = df_aquisicao.loc[i, "Dono"]
    if ativo not in dic_cotas_acum[dono]:
        dic_cotas_acum[dono][ativo] = cotas
    else:
        dic_cotas_acum[dono][ativo] += cotas
    lista_cotas_acum.append(dic_cotas_acum[dono][ativo])

df_aquisicao["Cotas Acumuladas"] = lista_cotas_acum
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Cotas Acumuladas", "Dono", "Natureza"])
df_aquisicao

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Natureza
0,PETR4,2024-04-01,32.00,1,1,Luis,Aquisição
1,PETR4,2024-08-01,31.00,2,3,Luis,Aquisição
2,PETR4,2024-11-01,29.31,3,6,Luis,Aquisição
3,VALE3,2024-11-01,34.87,2,2,Luis,Aquisição
4,TAEE11,2025-07-01,28.96,1,1,Luis,Aquisição
6,PETR4,2025-07-01,32.87,2,2,Heitor,Aquisição
7,PETR4,2025-07-01,31.79,3,5,Heitor,Aquisição
8,VALE3,2025-08-01,33.89,2,2,Heitor,Aquisição
9,HGLG11,2025-08-01,152.89,1,1,Heitor,Aquisição
5,PETR4,2025-09-01,31.09,1,7,Luis,Aquisição
10,PETR4,2025-09-01,31.34,1,6,Heitor,Aquisição
11,PETR4,2025-09-01,31.75,2,8,Heitor,Aquisição

In [331]:
df_compras_mesmo_dia = df_aquisicao.loc[df_aquisicao.duplicated(subset=["Ativo", "Data", "Dono"], keep=False)]
df_compras_mesmo_dia

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Natureza
6,PETR4,2025-07-01,32.87,2,2,Heitor,Aquisição
7,PETR4,2025-07-01,31.79,3,5,Heitor,Aquisição
10,PETR4,2025-09-01,31.34,1,6,Heitor,Aquisição
11,PETR4,2025-09-01,31.75,2,8,Heitor,Aquisição

In [332]:
# Unifica as aquisições do mesmo dono no mesmo dia

indices_mesmo_dia = list(df_compras_mesmo_dia.index)

dicionario_novo = {"Ativo": [], "Data": [], "Valor": [], "Número de Cotas": [], "Cotas Acumuladas": [], "Dono": [], "Natureza": []}

ativo_anterior = None
data_anterior = None
dono_anterior = None
valor_total = 0
cotas_totais = 0
maior_cota_acumulada = -1
primeiro = True

for i in df_compras_mesmo_dia.index:
    ativo = df_compras_mesmo_dia.loc[i, "Ativo"]
    data = df_compras_mesmo_dia.loc[i, "Data"]
    valor = df_compras_mesmo_dia.loc[i, "Valor"]
    num_cotas = df_compras_mesmo_dia.loc[i, "Número de Cotas"]
    num_cotas_acumul = df_compras_mesmo_dia.loc[i, "Cotas Acumuladas"]
    dono = df_compras_mesmo_dia.loc[i, "Dono"]
    natureza = df_compras_mesmo_dia.loc[i, "Natureza"]

    if (not primeiro) and ((ativo != ativo_anterior) or (data != data_anterior) or (dono != dono_anterior)):
        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
        dicionario_novo["Natureza"].append(natureza)

        valor_total = valor * num_cotas
        cotas_totais = num_cotas
        maior_cota_acumulada = num_cotas_acumul
    elif i == df_compras_mesmo_dia.index[-1]:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

        if num_cotas_acumul > maior_cota_acumulada:
            maior_cota_acumulada = num_cotas_acumul

        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
        dicionario_novo["Natureza"].append(natureza)
    else:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

    if num_cotas_acumul > maior_cota_acumulada:
        maior_cota_acumulada = num_cotas_acumul
    
    ativo_anterior = ativo
    data_anterior = data
    dono_anterior = dono
    primeiro = False

pd.DataFrame(dicionario_novo)

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Natureza
0,PETR4,2025-07-01,32.222000,5,5,Heitor,Aquisição
1,PETR4,2025-09-01,31.613333,3,8,Heitor,Aquisição

In [333]:
# Remove as aquisições do mesmo dia e adiciona a média ponderada da compra

df_aquisicao.drop(indices_mesmo_dia, inplace=True)
df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])
df_aquisicao.sort_values(by="Data")
df_aquisicao.index = range(len(df_aquisicao))
df_aquisicao

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Natureza
0,PETR4,2024-04-01,32.000000,1,1,Luis,Aquisição
1,PETR4,2024-08-01,31.000000,2,3,Luis,Aquisição
2,PETR4,2024-11-01,29.310000,3,6,Luis,Aquisição
3,VALE3,2024-11-01,34.870000,2,2,Luis,Aquisição
4,TAEE11,2025-07-01,28.960000,1,1,Luis,Aquisição
5,VALE3,2025-08-01,33.890000,2,2,Heitor,Aquisição
6,HGLG11,2025-08-01,152.890000,1,1,Heitor,Aquisição
7,PETR4,2025-09-01,31.090000,1,7,Luis,Aquisição
8,PETR4,2025-07-01,32.222000,5,5,Heitor,Aquisição
9,PETR4,2025-09-01,31.613333,3,8,Heitor,Aquisição

## Dividendos

In [334]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(lista_ativos_selecionados)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Natureza"] = ["Dividendos"] * len(df_dividendos)
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos.sort_values(by="Data", inplace=True)
df_dividendos

       Ativo       Data  Valor   DATA COM Tipo Receita    DY    Natureza
12    KNCR11 2021-01-14   0.43 2020-12-30   Rendimento  0,49  Dividendos
55    XPCI11 2021-01-15   0.75 2020-12-30   Rendimento  0,81  Dividendos
29    HGLG11 2021-01-15   2.63 2020-12-30   Rendimento  1,45  Dividendos
74    XPML11 2021-01-22   0.67 2021-01-15   Rendimento  0,59  Dividendos
89    KNCR11 2021-02-11   0.28 2021-01-29   Rendimento  0,32  Dividendos
...      ...        ...    ...        ...          ...   ...         ...
1443  TAEE11 2025-11-27   0.32 2025-04-29    Dividendo  0.89  Dividendos
1444  TAEE11 2025-11-27   0.23 2025-08-18    Dividendo  0.68  Dividendos
1445  TAEE11 2025-11-27   0.63 2025-08-18          JCP  1.87  Dividendos
1454   PETR4 2025-12-22   0.20 2025-08-21    Dividendo  0.66  Dividendos
1455   PETR4 2025-12-22   0.13 2025-08-21          JCP  0.45  Dividendos

[394 rows x 7 columns]

In [335]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 394 entries, 12 to 1455
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         394 non-null    object
 1   Data          394 non-null    datetime64[ns]
 2   Valor         394 non-null    float64
 3   DATA COM      394 non-null    datetime64[ns]
 4   Tipo Receita  394 non-null    object
 5   DY            394 non-null    object
 6   Natureza      394 non-null    object
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 24.6+ KB

### Relaciona Dividendos com Aquisições para multiplicar o valor de dividendo pela quantidade total de cotas válidas

In [336]:
# Junta valores pelo dia

df_dividendos = df_dividendos.groupby(["Ativo", "Data", "DATA COM", "Tipo Receita", "Natureza"]).agg("sum")
df_dividendos = df_dividendos.reset_index()
df_dividendos

      Ativo       Data   DATA COM     Tipo Receita    Natureza  Valor    DY
0     BBSE3 2021-02-25 2021-02-11        Dividendo  Dividendos   0.47  1.64
1     BBSE3 2021-02-25 2021-02-11  Rend. Tributado  Dividendos   0.00   0.0
2     BBSE3 2021-08-23 2021-08-11        Dividendo  Dividendos   0.52   2.4
3     BBSE3 2022-02-23 2022-02-10        Dividendo  Dividendos   0.91  3.76
4     BBSE3 2022-02-23 2022-02-10  Rend. Tributado  Dividendos   0.01  0.05
..      ...        ...        ...              ...         ...    ...   ...
383  XPML11 2025-04-25 2025-04-16       Rendimento  Dividendos   0.92  0,88
384  XPML11 2025-05-23 2025-05-19       Rendimento  Dividendos   0.92  0,87
385  XPML11 2025-06-25 2025-06-17       Rendimento  Dividendos   0.92  0,89
386  XPML11 2025-07-25 2025-07-18       Rendimento  Dividendos   0.92  0,89
387  XPML11 2025-08-25 2025-08-18       Rendimento  Dividendos   0.92  0,92

[388 rows x 7 columns]

In [337]:
# Filtra apenas os dividendos válidos para as cotas adquiridas
# Separa cada dividendo por dono

df_dividendos_adquiridos = pd.merge(df_dividendos, df_aquisicao, on="Ativo", suffixes=[" Dividendos", " Aquisição"])
df_dividendos_adquiridos = df_dividendos_adquiridos.loc[df_dividendos_adquiridos["DATA COM"] >= df_dividendos_adquiridos["Data Aquisição"]]
df_dividendos_adquiridos

,Ativo,Data Dividendos,DATA COM,Tipo Receita,Natureza Dividendos,Valor Dividendos,DY,Data Aquisição,Valor Aquisição,Número de Cotas,Cotas Acumuladas,Dono,Natureza Aquisição
56,HGLG11,2025-09-12,2025-08-29,Rendimento,Dividendos,1.10,"0,71",2025-08-01,152.89,1,1,Heitor,Aquisição
267,PETR4,2024-05-20,2024-04-25,Dividendo,Dividendos,1.10,2.6,2024-04-01,32.00,1,1,Luis,Aquisição
273,PETR4,2024-05-20,2024-04-25,Rend. Tributado,Dividendos,0.02,0.05,2024-04-01,32.00,1,1,Luis,Aquisição
279,PETR4,2024-05-20,2024-05-02,Dividendo,Dividendos,0.84,2.02,2024-04-01,32.00,1,1,Luis,Aquisição
285,PETR4,2024-05-20,2024-05-02,Rend. Tributado,Dividendos,0.03,0.08,2024-04-01,32.00,1,1,Luis,Aquisição
...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,TAEE11,2025-11-27,2025-08-18,JCP,Dividendos,0.63,1.87,2025-07-01,28.96,1,1,Luis,Aquisição
497,VALE3,2025-03-14,2024-12-11,JCP,Dividendos,0.52,0.89,2024-11-01,34.87,2,2,Luis,Aquisição
499,VALE3,2025-03-14,2025-03-07,Dividendo,Dividendos,2.14,3.79,2024-11-01,34.87,2,2,Luis,Aquisição
501,VALE3,2025-09-03,2025-08-12,JCP,Dividendos,1.89,3.39,2024-11-01,34.87,2,2,Luis,Aquisição
502,VALE3,2025-09-03,2025-08-12,JCP,Dividendos,1.89,3.39,2025-08-01,33.89,2,2,Heitor,Aquisição

In [338]:
df_dividendos_adquiridos = df_dividendos_adquiridos.filter(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Natureza Dividendos', 'Cotas Acumuladas', 'Dono'])
df_dividendos_adquiridos

,Ativo,Data Dividendos,Valor Dividendos,DATA COM,Tipo Receita,DY,Natureza Dividendos,Cotas Acumuladas,Dono
56,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Dividendos,1,Heitor
267,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Dividendos,1,Luis
273,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Dividendos,1,Luis
279,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Dividendos,1,Luis
285,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Dividendos,1,Luis
...,...,...,...,...,...,...,...,...,...
468,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Dividendos,1,Luis
497,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Dividendos,2,Luis
499,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Dividendos,2,Luis
501,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,2,Luis
502,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,2,Heitor

In [339]:
# Agrupa os dividendos, capturando o valor máximo de cotas do ativo válidas para multiplicar pelo dividendo

df_dividendos_adquiridos = df_dividendos_adquiridos.groupby(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Natureza Dividendos', 'Dono']).agg("max")
df_dividendos_adquiridos = df_dividendos_adquiridos.reset_index()
df_dividendos_adquiridos.rename(columns={"Data Dividendos": "Data", "Valor Dividendos": "Valor", "Natureza Dividendos": "Natureza"}, inplace=True)
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Natureza,Dono,Cotas Acumuladas
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Dividendos,Heitor,1
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Dividendos,Luis,1
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Dividendos,Luis,1
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Dividendos,Luis,1
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Dividendos,Luis,1
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Dividendos,Luis,1
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Dividendos,Luis,1
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Dividendos,Luis,1
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Dividendos,Luis,1
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Dividendos,Luis,1
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Dividendos,Luis,1
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Dividendos,Luis,3
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Dividendos,Luis,3
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Dividendos,Luis,3
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Dividendos,Luis,6
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Dividendos,Luis,6
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Dividendos,Luis,6
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Dividendos,Luis,6
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Dividendos,Luis,6
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Dividendos,Luis,6
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Dividendos,Luis,6
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Dividendos,Luis,6
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Dividendos,Luis,6
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Dividendos,Luis,6
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Dividendos,Luis,6
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Dividendos,Luis,6
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Dividendos,Luis,6
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Dividendos,Heitor,5
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Dividendos,Luis,6
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Dividendos,Heitor,5
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Dividendos,Luis,6
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Dividendos,Heitor,5
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Dividendos,Luis,6
33,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Dividendos,Luis,1
34,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Dividendos,Luis,1
35,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Dividendos,Luis,2
36,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Dividendos,Luis,2
37,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,Heitor,2
38,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,Luis,2

In [340]:
# Calcula dividendo total, valor x número de cotas válidas e acumula os dividendos

lista_dividendos_totais = []
# lista_dividendos_acumulados = []

dividendo_acumulado = 0
for i in df_dividendos_adquiridos.index:
    valor = df_dividendos_adquiridos.loc[i, "Valor"]
    cotas_acumul = df_dividendos_adquiridos.loc[i, "Cotas Acumuladas"]
    dividendo_acumulado += valor * cotas_acumul

    lista_dividendos_totais.append(valor * cotas_acumul)
    # lista_dividendos_acumulados.append(dividendo_acumulado)

df_dividendos_adquiridos["Dividendos Totais"] = lista_dividendos_totais
# df_dividendos_adquiridos["Dividendos Acumulados"] = lista_dividendos_acumulados
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Natureza,Dono,Cotas Acumuladas,Dividendos Totais
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Dividendos,Heitor,1,1.10
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Dividendos,Luis,1,0.02
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Dividendos,Luis,1,0.03
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Dividendos,Luis,1,0.84
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Dividendos,Luis,1,1.10
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Dividendos,Luis,1,0.02
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Dividendos,Luis,1,0.04
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Dividendos,Luis,1,0.84
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Dividendos,Luis,1,0.52
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Dividendos,Luis,1,0.07
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Dividendos,Luis,1,0.44
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Dividendos,Luis,3,0.33
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Dividendos,Luis,3,1.23
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Dividendos,Luis,3,1.56
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Dividendos,Luis,6,9.30
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Dividendos,Luis,6,0.06
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Dividendos,Luis,6,3.96
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Dividendos,Luis,6,0.06
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Dividendos,Luis,6,0.06
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Dividendos,Luis,6,3.90
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Dividendos,Luis,6,0.06
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Dividendos,Luis,6,2.10
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Dividendos,Luis,6,0.12
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Dividendos,Luis,6,2.10
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Dividendos,Luis,6,2.70
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Dividendos,Luis,6,0.84
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Dividendos,Luis,6,1.80
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Dividendos,Heitor,5,1.65
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Dividendos,Luis,6,1.98
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Dividendos,Heitor,5,0.65
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Dividendos,Luis,6,0.78
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Dividendos,Heitor,5,1.00
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Dividendos,Luis,6,1.20
33,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Dividendos,Luis,1,0.23
34,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Dividendos,Luis,1,0.63
35,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Dividendos,Luis,2,1.04
36,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Dividendos,Luis,2,4.28
37,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,Heitor,2,3.78
38,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Dividendos,Luis,2,3.78

## Une os dados

In [341]:
df_historico_carteira = pd.concat([df_historico, df_dividendos_adquiridos])
df_historico_carteira = pd.concat([df_historico_carteira, df_aquisicao])
df_historico_carteira

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas
0,BBSE3,2020-10-01,23.680000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,BBSE3,2020-11-01,28.559999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,BBSE3,2020-12-01,29.629999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,BBSE3,2021-01-01,27.660000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
4,BBSE3,2021-02-01,25.430000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5,VALE3,2025-08-01,33.890000,Aquisição,NaT,NaN,NaN,Heitor,2.0,NaN,2.0
6,HGLG11,2025-08-01,152.890000,Aquisição,NaT,NaN,NaN,Heitor,1.0,NaN,1.0
7,PETR4,2025-09-01,31.090000,Aquisição,NaT,NaN,NaN,Luis,7.0,NaN,1.0
8,PETR4,2025-07-01,32.222000,Aquisição,NaT,NaN,NaN,Heitor,5.0,NaN,5.0
9,PETR4,2025-09-01,31.613333,Aquisição,NaT,NaN,NaN,Heitor,8.0,NaN,3.0

In [342]:
df_historico_carteira.sort_values(by="Data", inplace=True)
df_historico_carteira.index = range(0, len(df_historico_carteira))
df_historico_carteira

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas
0,BBSE3,2020-10-01,23.680000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1,XPCI11,2020-10-01,89.493019,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
2,KNCR11,2020-10-01,91.949997,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,TAEE11,2020-10-01,28.150000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
4,PETR4,2020-10-01,18.940001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
586,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,Luis,1.0,0.23,NaN
587,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Heitor,5.0,1.00,NaN
588,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Luis,6.0,0.78,NaN
589,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Heitor,5.0,0.65,NaN
590,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Luis,6.0,1.20,NaN

In [343]:
df_historico_carteira.loc[df_historico_carteira["Natureza"] == "Aquisição"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas
377,PETR4,2024-04-01,32.000000,Aquisição,NaT,NaN,NaN,Luis,1.0,NaN,1.0
415,PETR4,2024-08-01,31.000000,Aquisição,NaT,NaN,NaN,Luis,3.0,NaN,2.0
450,VALE3,2024-11-01,34.870000,Aquisição,NaT,NaN,NaN,Luis,2.0,NaN,2.0
456,PETR4,2024-11-01,29.310000,Aquisição,NaT,NaN,NaN,Luis,6.0,NaN,3.0
541,TAEE11,2025-07-01,28.960000,Aquisição,NaT,NaN,NaN,Luis,1.0,NaN,1.0
542,PETR4,2025-07-01,32.222000,Aquisição,NaT,NaN,NaN,Heitor,5.0,NaN,5.0
546,HGLG11,2025-08-01,152.890000,Aquisição,NaT,NaN,NaN,Heitor,1.0,NaN,1.0
555,VALE3,2025-08-01,33.890000,Aquisição,NaT,NaN,NaN,Heitor,2.0,NaN,2.0
558,PETR4,2025-09-01,31.090000,Aquisição,NaT,NaN,NaN,Luis,7.0,NaN,1.0
560,PETR4,2025-09-01,31.613333,Aquisição,NaT,NaN,NaN,Heitor,8.0,NaN,3.0

In [ ]:
# a = df_historico_carteira.loc[df_historico_carteira["Data"] >= '2024-04-01']
# a

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Dividendos Acumulados,Número de Cotas
371,XPML11,2024-04-01,116.309998,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,XPCI11,2024-04-01,88.900002,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,HTMX11,2024-04-01,176.889999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,KNCR11,2024-04-01,105.010002,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,HGLG11,2024-04-01,166.630005,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
586,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,Luis,1.0,0.23,42.69,NaN
587,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Heitor,5.0,1.00,41.26,NaN
588,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Luis,6.0,0.78,40.26,NaN
589,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Heitor,5.0,0.65,39.48,NaN
590,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Luis,6.0,1.20,42.46,NaN

In [344]:
lista_valor_investido = []
lista_preco_unitario = []
lista_preco_total = []
# lista_dividendos_total = []
# lista_dividendos_total_d = []

# lista_valor_investido_acumulado_distinto = []
# lista_preco_total_acumulado_distinto = []
# lista_valor_investido_acumulado = []
# lista_preco_total_acumulado = []
# lista_dividendos_acumulados = []

# dicionario_acumulados_distintos = {
#     "Heitor": [0, 0, 0],
#     "Luis": [0, 0, 0]
# }

# valor_investido_acumulado = 0
# preco_total_acumulado = 0
# dividendos_acumulados = 0

for i in df_historico_carteira.index:
    ativo = df_historico_carteira.loc[i, "Ativo"]
    data = df_historico_carteira.loc[i, "Data"]
    valor = df_historico_carteira.loc[i, "Valor"]
    dono = df_historico_carteira.loc[i, "Dono"]

    valor_investido = 0
    preco_total = 0
    valor_dividendos = 0

    if df_historico_carteira.loc[i, "Natureza"] == "Aquisição":
        preco = df_historico.loc[(df_historico["Ativo"] == ativo) & (df_historico["Data"] == data)]["Valor"].values[0]
        num_cotas = df_historico_carteira.loc[i, 'Número de Cotas']
        valor_investido = num_cotas * valor
        preco_total = preco * num_cotas

        lista_valor_investido.append(valor_investido)
        lista_preco_unitario.append(preco)
        lista_preco_total.append(preco_total)
    else:
        lista_valor_investido.append(None)
        lista_preco_unitario.append(None)
        lista_preco_total.append(None)

    # if a.loc[i, "Natureza"] == "Dividendos":
    #     data_com = a.loc[i, "DATA COM"]
    #     num_cotas = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] <= data_com)]["Número de Cotas"].sum()
    #     valor_dividendos = valor * num_cotas

    #     lista_dividendos_total.append(valor_dividendos)

    #     num_cotas = df_aquisicao.loc[
    #         (df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] <= data_com) & (df_aquisicao["Dono"] == dono)
    #     ]["Número de Cotas"].sum()
    #     valor_dividendos_d = valor * num_cotas
    #     lista_dividendos_total_d.append(valor_dividendos_d)
    # else:
    #     lista_dividendos_total.append(None)
    #     lista_dividendos_total_d.append(None)

    # if dono == "Luis" or dono == "Heitor":
    #     dicionario_acumulados_distintos[dono][0] += valor_investido
    #     lista_valor_investido_acumulado_distinto.append(dicionario_acumulados_distintos[dono][0])
    #     dicionario_acumulados_distintos[dono][1] += preco_total
    #     lista_preco_total_acumulado_distinto.append(dicionario_acumulados_distintos[dono][1])
    # else:
    #     lista_valor_investido_acumulado_distinto.append(None)
    #     lista_preco_total_acumulado_distinto.append(None)

    # # valor_investido_acumulado += valor_investido
    # # preco_total_acumulado += preco_total
    # dividendos_acumulados += valor_dividendos

    # # lista_valor_investido_acumulado.append(valor_investido_acumulado)
    # # lista_preco_total_acumulado.append(preco_total_acumulado)
    # lista_dividendos_acumulados.append(dividendos_acumulados)


df_historico_carteira["Valor Investido"] = lista_valor_investido
# a["Valor Investido Acumulado"] = lista_valor_investido_acumulado_distinto
# a["Valor Investido Acumulado"] = lista_valor_investido_acumulado
df_historico_carteira["Preço Unitário"] = lista_preco_unitario
df_historico_carteira["Preço Total"] = lista_preco_total
# a["Preço Total Acumulado"] = lista_preco_total_acumulado_distinto
# a["Preço Total Acumulado"] = lista_preco_total_acumulado

# a["Dividendos Totais D"] = lista_dividendos_total_d
# a["Dividendos Totais"] = lista_dividendos_total
# a["Dividendos Acumulados"] = lista_dividendos_acumulados
df_historico_carteira

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas,Valor Investido,Preço Unitário,Preço Total
0,BBSE3,2020-10-01,23.680000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,XPCI11,2020-10-01,89.493019,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KNCR11,2020-10-01,91.949997,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TAEE11,2020-10-01,28.150000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PETR4,2020-10-01,18.940001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,Luis,1.0,0.23,NaN,NaN,NaN,NaN
587,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Heitor,5.0,1.00,NaN,NaN,NaN,NaN
588,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Luis,6.0,0.78,NaN,NaN,NaN,NaN
589,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,Heitor,5.0,0.65,NaN,NaN,NaN,NaN
590,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,Luis,6.0,1.20,NaN,NaN,NaN,NaN

In [345]:
df_historico_carteira.loc[df_historico_carteira["Natureza"] == "Aquisição"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas,Valor Investido,Preço Unitário,Preço Total
377,PETR4,2024-04-01,32.000000,Aquisição,NaT,NaN,NaN,Luis,1.0,NaN,1.0,32.00,42.020000,42.020000
415,PETR4,2024-08-01,31.000000,Aquisição,NaT,NaN,NaN,Luis,3.0,NaN,2.0,62.00,39.369999,78.739998
450,VALE3,2024-11-01,34.870000,Aquisição,NaT,NaN,NaN,Luis,2.0,NaN,2.0,69.74,58.779999,117.559998
456,PETR4,2024-11-01,29.310000,Aquisição,NaT,NaN,NaN,Luis,6.0,NaN,3.0,87.93,38.900002,116.700005
541,TAEE11,2025-07-01,28.960000,Aquisição,NaT,NaN,NaN,Luis,1.0,NaN,1.0,28.96,33.360001,33.360001
542,PETR4,2025-07-01,32.222000,Aquisição,NaT,NaN,NaN,Heitor,5.0,NaN,5.0,161.11,32.639999,163.199997
546,HGLG11,2025-08-01,152.890000,Aquisição,NaT,NaN,NaN,Heitor,1.0,NaN,1.0,152.89,154.990005,154.990005
555,VALE3,2025-08-01,33.890000,Aquisição,NaT,NaN,NaN,Heitor,2.0,NaN,2.0,67.78,55.560001,111.120003
558,PETR4,2025-09-01,31.090000,Aquisição,NaT,NaN,NaN,Luis,7.0,NaN,1.0,31.09,31.510000,31.510000
560,PETR4,2025-09-01,31.613333,Aquisição,NaT,NaN,NaN,Heitor,8.0,NaN,3.0,94.84,31.510000,94.530001

In [346]:
df_historico_carteira.loc[df_historico_carteira["Natureza"] == "Dividendos"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais,Número de Cotas,Valor Investido,Preço Unitário,Preço Total
390,PETR4,2024-05-20,0.84,Dividendos,2024-05-02,Dividendo,2.02,Luis,1.0,0.84,NaN,NaN,NaN,NaN
391,PETR4,2024-05-20,1.10,Dividendos,2024-04-25,Dividendo,2.6,Luis,1.0,1.10,NaN,NaN,NaN,NaN
392,PETR4,2024-05-20,0.03,Dividendos,2024-05-02,Rend. Tributado,0.08,Luis,1.0,0.03,NaN,NaN,NaN,NaN
393,PETR4,2024-05-20,0.02,Dividendos,2024-04-25,Rend. Tributado,0.05,Luis,1.0,0.02,NaN,NaN,NaN,NaN
403,PETR4,2024-06-20,0.04,Dividendos,2024-05-02,Rend. Tributado,0.1,Luis,1.0,0.04,NaN,NaN,NaN,NaN
404,PETR4,2024-06-20,0.84,Dividendos,2024-05-02,Dividendo,2.02,Luis,1.0,0.84,NaN,NaN,NaN,NaN
405,PETR4,2024-06-20,0.02,Dividendos,2024-04-25,Rend. Tributado,0.07,Luis,1.0,0.02,NaN,NaN,NaN,NaN
425,PETR4,2024-08-20,0.52,Dividendos,2024-06-11,JCP,1.38,Luis,1.0,0.52,NaN,NaN,NaN,NaN
435,PETR4,2024-09-20,0.44,Dividendos,2024-06-11,Dividendo,1.19,Luis,1.0,0.44,NaN,NaN,NaN,NaN
436,PETR4,2024-09-20,0.07,Dividendos,2024-06-11,JCP,0.2,Luis,1.0,0.07,NaN,NaN,NaN,NaN
457,PETR4,2024-11-21,0.41,Dividendos,2024-08-21,JCP,1.07,Luis,3.0,1.23,NaN,NaN,NaN,NaN
458,PETR4,2024-11-21,0.11,Dividendos,2024-08-21,Dividendo,0.3,Luis,3.0,0.33,NaN,NaN,NaN,NaN
468,PETR4,2024-12-20,0.52,Dividendos,2024-08-21,Dividendo,1.37,Luis,3.0,1.56,NaN,NaN,NaN,NaN
469,PETR4,2024-12-23,1.55,Dividendos,2024-12-11,Dividendo,3.86,Luis,6.0,9.30,NaN,NaN,NaN,NaN
488,PETR4,2025-02-20,0.66,Dividendos,2024-12-23,JCP,1.8,Luis,6.0,3.96,NaN,NaN,NaN,NaN
489,PETR4,2025-02-20,0.01,Dividendos,2024-12-23,Rend. Tributado,0.03,Luis,6.0,0.06,NaN,NaN,NaN,NaN
499,VALE3,2025-03-14,2.14,Dividendos,2025-03-07,Dividendo,3.79,Luis,2.0,4.28,NaN,NaN,NaN,NaN
500,VALE3,2025-03-14,0.52,Dividendos,2024-12-11,JCP,0.89,Luis,2.0,1.04,NaN,NaN,NaN,NaN
501,PETR4,2025-03-20,0.65,Dividendos,2024-12-23,Dividendo,1.77,Luis,6.0,3.90,NaN,NaN,NaN,NaN
502,PETR4,2025-03-20,0.01,Dividendos,2024-12-23,Rend. Tributado,0.05,Luis,6.0,0.06,NaN,NaN,NaN,NaN
503,PETR4,2025-03-20,0.01,Dividendos,2024-12-23,JCP,0.03,Luis,6.0,0.06,NaN,NaN,NaN,NaN
522,PETR4,2025-05-20,0.35,Dividendos,2025-04-16,Dividendo,1.13,Luis,6.0,2.10,NaN,NaN,NaN,NaN
523,PETR4,2025-05-20,0.01,Dividendos,2025-04-16,Rend. Tributado,0.05,Luis,6.0,0.06,NaN,NaN,NaN,NaN
533,PETR4,2025-06-20,0.02,Dividendos,2025-04-16,Rend. Tributado,0.07,Luis,6.0,0.12,NaN,NaN,NaN,NaN
534,PETR4,2025-06-20,0.35,Dividendos,2025-04-16,Dividendo,1.13,Luis,6.0,2.10,NaN,NaN,NaN,NaN
557,PETR4,2025-08-20,0.45,Dividendos,2025-06-02,JCP,1.45,Luis,6.0,2.70,NaN,NaN,NaN,NaN
569,VALE3,2025-09-03,1.89,Dividendos,2025-08-12,JCP,3.39,Luis,2.0,3.78,NaN,NaN,NaN,NaN
570,VALE3,2025-09-03,1.89,Dividendos,2025-08-12,JCP,3.39,Heitor,2.0,3.78,NaN,NaN,NaN,NaN
575,HGLG11,2025-09-12,1.10,Dividendos,2025-08-29,Rendimento,"0,71",Heitor,1.0,1.10,NaN,NaN,NaN,NaN
581,PETR4,2025-09-22,0.30,Dividendos,2025-06-02,Dividendo,0.99,Luis,6.0,1.80,NaN,NaN,NaN,NaN
582,PETR4,2025-09-22,0.14,Dividendos,2025-06-02,JCP,0.47,Luis,6.0,0.84,NaN,NaN,NaN,NaN
583,PETR4,2025-11-21,0.33,Dividendos,2025-08-21,JCP,1.11,Luis,6.0,1.98,NaN,NaN,NaN,NaN
584,PETR4,2025-11-21,0.33,Dividendos,2025-08-21,JCP,1.11,Heitor,5.0,1.65,NaN,NaN,NaN,NaN
585,TAEE11,2025-11-27,0.63,Dividendos,2025-08-18,JCP,1.87,Luis,1.0,0.63,NaN,NaN,NaN,NaN
586,TAEE11,2025-11-27,0.23,Dividendos,2025-08-18,Dividendo,0.68,Luis,1.0,0.23,NaN,NaN,NaN,NaN
587,PETR4,2025-12-22,0.20,Dividendos,2025-08-21,Dividendo,0.66,Heitor,5.0,1.00,NaN,NaN,NaN,NaN
588,PETR4,2025-12-22,0.13,Dividendos,2025-08-21,JCP,0.45,Luis,6.0,0.78,NaN,NaN,NaN,NaN
589,PETR4,2025-12-22,0.13,Dividendos,2025-08-21,JCP,0.45,Heitor,5.0,0.65,NaN,NaN,NaN,NaN
590,PETR4,2025-12-22,0.20,Dividendos,2025-08-21,Dividendo,0.66,Luis,6.0,1.20,NaN,NaN,NaN,NaN

In [347]:
df_historico_carteira.to_csv('Dados Modelados/historico_da_carteira.csv', index=False)

## Cria Medidas

In [ ]:
# ativos_concatenados.to_csv('Dados Modelados/historico_ativos_carteira.csv', index=False)