# Bibliotecas

In [1]:
import pandas as pd

# Ativos da Carteira

In [48]:
df_ativos = pd.read_csv('Dados Modelados/Ativos.csv')
lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XMLP11",
    "XPCI11"

]

lista_index = []
for i in df_ativos.index:
    if df_ativos.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_ativos = df_ativos.loc[lista_index, :]
df_ativos.index = range(0, len(df_ativos))
df_ativos['Tipo'] = "Ação"
df_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação

In [49]:
df_fiis = pd.read_csv('Dados Modelados/FIIs.csv')

lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XPML11",
    "XPCI11"

]

lista_index = []
for i in df_fiis.index:
    if df_fiis.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_fiis = df_fiis.loc[lista_index, :]
df_fiis.index = range(0, len(df_fiis))
df_fiis['Tipo'] = "FII"
df_fiis

    ATIVO                 SETOR    INDUSTRIA Tipo
0  KNCR11       REIT - Mortgage  Real Estate  FII
1  HGLG11    REIT - Diversified  Real Estate  FII
2  XPCI11       REIT - Mortgage  Real Estate  FII
3  XPML11         REIT - Retail  Real Estate  FII
4  HTMX11  REIT - Hotel & Motel  Real Estate  FII

In [50]:
df_carteira_ativos = pd.concat([df_ativos, df_fiis])
df_carteira_ativos.index = range(0, len(df_carteira_ativos))
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII

In [51]:
acoes = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "Ação"]['ATIVO'].values
acoes.sort()
print(acoes)

fundos = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "FII"]['ATIVO'].values
fundos.sort()
print(fundos)

['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']

In [53]:
balanco = {
    'BBSE3': 3,
    'PETR4': 30,
    'TAEE11': 3,
    'VALE3': 3,

    'HGLG11': 3,
    'HTMX11': 3, 
    'KNCR11': 3, 
    'XPCI11': 3,
    'XPML11': 3
}

balanco_ativos = []
for i in df_carteira_ativos.index:
    balanco_ativos.append(
        balanco[df_carteira_ativos.loc[[i], "ATIVO"].values[0]]
    )

df_carteira_ativos["Balanço de Cotas"] = balanco_ativos
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação,3
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação,3
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação,30
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação,3
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII,3
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII,3
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII,3
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII,3
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII,3

In [54]:
df_carteira_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta Histórico dos Ativos da Carteira

In [55]:
df_ativos = pd.read_csv('Dados Modelados/historico_Ativos.csv')
lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XMLP11",
    "XPCI11"

]

lista_index = []
for i in df_ativos.index:
    if df_ativos.loc[i, "Ativo"] in lista_ativos_selecionados:
        lista_index.append(i)

df_ativos = df_ativos.loc[lista_index, :]
df_ativos.index = range(0, len(df_ativos))
df_ativos['Tipo'] = "Ação"
df_ativos

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,Tipo
0,24.350000,26.049999,23.610001,23.680000,88234500,15.714323,0.000000,NaN,BBSE3,01-10-2020,Ação
1,23.680000,29.799999,23.680000,28.559999,120982300,18.952745,0.000000,NaN,BBSE3,01-11-2020,Ação
2,29.000000,30.760000,28.260000,29.629999,70198700,19.662809,0.000000,NaN,BBSE3,01-12-2020,Ação
3,29.629999,30.450001,27.660000,27.660000,86915800,18.355495,0.000000,NaN,BBSE3,01-01-2021,Ação
4,28.000000,29.000000,25.430000,25.430000,89982600,16.875643,0.476121,NaN,BBSE3,01-02-2021,Ação
...,...,...,...,...,...,...,...,...,...,...,...
239,35.360001,35.529999,33.669998,34.930000,31750500,34.043571,0.000000,NaN,TAEE11,01-06-2025,Ação
240,34.810001,35.169998,33.160000,33.360001,26490900,32.513416,0.000000,NaN,TAEE11,01-07-2025,Ação
241,33.560001,34.919998,32.840000,34.869999,47238700,33.985092,0.869171,NaN,TAEE11,01-08-2025,Ação
242,34.880001,35.220001,34.180000,34.900002,10775000,34.900002,0.000000,NaN,TAEE11,01-09-2025,Ação
243,34.950001,35.150002,34.849998,34.980000,750000,34.980000,0.000000,NaN,TAEE11,11-09-2025,Ação

In [56]:
df_fiis = pd.read_csv('Dados Modelados/historico_Fii.csv')

lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XMLP11",
    "XPCI11"

]

lista_index = []
for i in df_fiis.index:
    if df_fiis.loc[i, "Ativo"] in lista_ativos_selecionados:
        lista_index.append(i)

df_fiis = df_fiis.loc[lista_index, :]
df_fiis.index = range(0, len(df_fiis))
df_fiis['Tipo'] = "FII"
df_fiis

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,Tipo
0,89.930000,94.480003,88.019997,91.949997,913427.0,58.732109,0.00,NaN,KNCR11,01-10-2020,FII
1,91.949997,92.989998,87.910004,88.699997,863036.0,56.656181,0.00,NaN,KNCR11,01-11-2020,FII
2,88.250000,88.599998,85.500000,87.050003,1348549.0,55.602295,0.00,NaN,KNCR11,01-12-2020,FII
3,87.050003,89.769997,86.699997,88.820000,832932.0,56.732868,0.00,NaN,KNCR11,01-01-2021,FII
4,88.699997,91.489998,87.000000,89.410004,924011.0,57.109722,0.00,NaN,KNCR11,01-02-2021,FII
...,...,...,...,...,...,...,...,...,...,...,...
232,141.600006,147.000000,140.600006,145.300003,78781.0,139.966797,1.54,NaN,HTMX11,01-06-2025,FII
233,145.160004,146.169998,141.410004,145.470001,71302.0,141.689133,1.50,NaN,HTMX11,01-07-2025,FII
234,141.020004,143.699997,139.000000,139.869995,75358.0,137.655762,1.22,NaN,HTMX11,01-08-2025,FII
235,138.949997,139.000000,136.500000,138.399994,48631.0,137.361023,1.05,NaN,HTMX11,01-09-2025,FII
236,0.000000,0.000000,0.000000,138.399994,0.0,138.399994,0.00,NaN,HTMX11,15-09-2025,FII

In [57]:
ativos_concatenados = pd.concat([df_ativos, df_fiis])
ativos_concatenados.index = range(0, len(ativos_concatenados))
ativos_concatenados

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,Tipo
0,24.350000,26.049999,23.610001,23.680000,88234500.0,15.714323,0.000000,NaN,BBSE3,01-10-2020,Ação
1,23.680000,29.799999,23.680000,28.559999,120982300.0,18.952745,0.000000,NaN,BBSE3,01-11-2020,Ação
2,29.000000,30.760000,28.260000,29.629999,70198700.0,19.662809,0.000000,NaN,BBSE3,01-12-2020,Ação
3,29.629999,30.450001,27.660000,27.660000,86915800.0,18.355495,0.000000,NaN,BBSE3,01-01-2021,Ação
4,28.000000,29.000000,25.430000,25.430000,89982600.0,16.875643,0.476121,NaN,BBSE3,01-02-2021,Ação
...,...,...,...,...,...,...,...,...,...,...,...
476,141.600006,147.000000,140.600006,145.300003,78781.0,139.966797,1.540000,NaN,HTMX11,01-06-2025,FII
477,145.160004,146.169998,141.410004,145.470001,71302.0,141.689133,1.500000,NaN,HTMX11,01-07-2025,FII
478,141.020004,143.699997,139.000000,139.869995,75358.0,137.655762,1.220000,NaN,HTMX11,01-08-2025,FII
479,138.949997,139.000000,136.500000,138.399994,48631.0,137.361023,1.050000,NaN,HTMX11,01-09-2025,FII
480,0.000000,0.000000,0.000000,138.399994,0.0,138.399994,0.000000,NaN,HTMX11,15-09-2025,FII

In [58]:
ativos_concatenados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   open       481 non-null    float64
 1   high       481 non-null    float64
 2   low        481 non-null    float64
 3   close      481 non-null    float64
 4   volume     481 non-null    float64
 5   adjclose   481 non-null    float64
 6   dividends  481 non-null    float64
 7   splits     0 non-null      float64
 8   Ativo      481 non-null    object
 9   Data       481 non-null    object
 10  Tipo       481 non-null    object
dtypes: float64(8), object(3)
memory usage: 41.5+ KB

In [59]:
ativos_concatenados.to_csv('Dados Modelados/historico_ativos_carteira.csv', index=False)