# Bibliotecas

In [1]:
import pandas as pd

# Ativos da Carteira

In [14]:
df_ativos = pd.read_csv('Dados Modelados/Ativos.csv')
lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XMLP11",
    "XPCI11"

]

lista_index = []
for i in df_ativos.index:
    if df_ativos.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_ativos = df_ativos.loc[lista_index, :]
df_ativos.index = range(0, len(df_ativos))
df_ativos['Tipo'] = "Ação"
df_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação

In [16]:
df_fiis = pd.read_csv('Dados Modelados/FIIs.csv')

lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XPML11",
    "XPCI11"

]

lista_index = []
for i in df_fiis.index:
    if df_fiis.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_fiis = df_fiis.loc[lista_index, :]
df_fiis.index = range(0, len(df_fiis))
df_fiis['Tipo'] = "FII"
df_fiis

    ATIVO                 SETOR    INDUSTRIA Tipo
0  KNCR11       REIT - Mortgage  Real Estate  FII
1  HGLG11    REIT - Diversified  Real Estate  FII
2  XPCI11       REIT - Mortgage  Real Estate  FII
3  XPML11         REIT - Retail  Real Estate  FII
4  HTMX11  REIT - Hotel & Motel  Real Estate  FII

In [17]:
df_carteira_ativos = pd.concat([df_ativos, df_fiis])
df_carteira_ativos.index = range(0, len(df_carteira_ativos))
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII

In [18]:
acoes = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "Ação"]['ATIVO'].values
acoes.sort()
print(acoes)

fundos = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "FII"]['ATIVO'].values
fundos.sort()
print(fundos)

['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']

In [19]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1
}

balanco_ativos = []
for i in df_carteira_ativos.index:
    balanco_ativos.append(
        balanco[df_carteira_ativos.loc[[i], "ATIVO"].values[0]]
    )

df_carteira_ativos["Balanço de Cotas"] = balanco_ativos
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação,1
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação,1
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação,10
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação,1
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII,1
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII,1
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII,1

In [7]:
df_carteira_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Histórico

In [107]:
df_ativos = pd.read_csv('Dados Modelados/historico_Ativos.csv')
df_ativos = df_ativos.loc[df_ativos["Ativo"].isin(lista_ativos_selecionados)]
# df_ativos.index = range(0, len(df_ativos))
# df_ativos['Tipo Ativo'] = "Ação"
df_ativos

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
1098,24.350000,26.049999,23.610001,23.680000,88234500,15.714323,0.000000,NaN,BBSE3,01-10-2020
1099,23.680000,29.799999,23.680000,28.559999,120982300,18.952745,0.000000,NaN,BBSE3,01-11-2020
1100,29.000000,30.760000,28.260000,29.629999,70198700,19.662809,0.000000,NaN,BBSE3,01-12-2020
1101,29.629999,30.450001,27.660000,27.660000,86915800,18.355495,0.000000,NaN,BBSE3,01-01-2021
1102,28.000000,29.000000,25.430000,25.430000,89982600,16.875643,0.476121,NaN,BBSE3,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
2743,35.360001,35.529999,33.669998,34.930000,31750500,34.043571,0.000000,NaN,TAEE11,01-06-2025
2744,34.810001,35.169998,33.160000,33.360001,26490900,32.513416,0.000000,NaN,TAEE11,01-07-2025
2745,33.560001,34.919998,32.840000,34.869999,47238700,33.985092,0.869171,NaN,TAEE11,01-08-2025
2746,34.880001,35.220001,34.180000,34.900002,10775000,34.900002,0.000000,NaN,TAEE11,01-09-2025
2747,34.950001,35.150002,34.849998,34.980000,750000,34.980000,0.000000,NaN,TAEE11,11-09-2025

In [108]:
df_fiis = pd.read_csv('Dados Modelados/historico_Fii.csv')
df_fiis = df_fiis.loc[df_fiis["Ativo"].isin(lista_ativos_selecionados)]
# df_fiis.index = range(0, len(df_fiis))
# df_fiis['Tipo Ativo'] = "FII"
df_fiis

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
674,89.930000,94.480003,88.019997,91.949997,913427.0,58.732109,0.00,NaN,KNCR11,01-10-2020
675,91.949997,92.989998,87.910004,88.699997,863036.0,56.656181,0.00,NaN,KNCR11,01-11-2020
676,88.250000,88.599998,85.500000,87.050003,1348549.0,55.602295,0.00,NaN,KNCR11,01-12-2020
677,87.050003,89.769997,86.699997,88.820000,832932.0,56.732868,0.00,NaN,KNCR11,01-01-2021
678,88.699997,91.489998,87.000000,89.410004,924011.0,57.109722,0.00,NaN,KNCR11,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
5210,141.600006,147.000000,140.600006,145.300003,78781.0,139.966797,1.54,NaN,HTMX11,01-06-2025
5211,145.160004,146.169998,141.410004,145.470001,71302.0,141.689133,1.50,NaN,HTMX11,01-07-2025
5212,141.020004,143.699997,139.000000,139.869995,75358.0,137.655762,1.22,NaN,HTMX11,01-08-2025
5213,138.949997,139.000000,136.500000,138.399994,48631.0,137.361023,1.05,NaN,HTMX11,01-09-2025
5214,0.000000,0.000000,0.000000,138.399994,0.0,138.399994,0.00,NaN,HTMX11,15-09-2025

In [109]:
df_historico = pd.concat([df_ativos, df_fiis])
df_historico = df_historico.filter(["Ativo", "Data", "close"])
df_historico.rename(columns={"close": "Valor"}, inplace=True)
df_historico["Natureza"] = ["Histórico de Preço"] * len(df_historico)
df_historico["Data"] = pd.to_datetime(df_historico["Data"], format="%d-%m-%Y")
df_historico.index = range(0, len(df_historico))
df_historico

      Ativo       Data       Valor            Natureza
0     BBSE3 2020-10-01   23.680000  Histórico de Preço
1     BBSE3 2020-11-01   28.559999  Histórico de Preço
2     BBSE3 2020-12-01   29.629999  Histórico de Preço
3     BBSE3 2021-01-01   27.660000  Histórico de Preço
4     BBSE3 2021-02-01   25.430000  Histórico de Preço
..      ...        ...         ...                 ...
537  HTMX11 2025-06-01  145.300003  Histórico de Preço
538  HTMX11 2025-07-01  145.470001  Histórico de Preço
539  HTMX11 2025-08-01  139.869995  Histórico de Preço
540  HTMX11 2025-09-01  138.399994  Histórico de Preço
541  HTMX11 2025-09-15  138.399994  Histórico de Preço

[542 rows x 4 columns]

In [110]:
df_historico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Ativo     542 non-null    object
 1   Data      542 non-null    datetime64[ns]
 2   Valor     542 non-null    float64
 3   Natureza  542 non-null    object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 17.1+ KB

## Dividendos

In [111]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(lista_ativos_selecionados)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Natureza"] = ["Dividendos"] * len(df_dividendos)
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos

       Ativo       Data  Valor   DATA COM     Tipo Receita    DY    Natureza
31     BBSE3 2021-02-25   0.47 2021-02-11        Dividendo  1.64  Dividendos
32     BBSE3 2021-02-25   0.00 2021-02-11  Rend. Tributado   0.0  Dividendos
53     VALE3 2021-03-15   0.83 2021-03-04              JCP  0.84  Dividendos
54     VALE3 2021-03-15   3.42 2021-03-04        Dividendo  3.45  Dividendos
77     PETR4 2021-04-29   0.78 2021-04-14        Dividendo  3.25  Dividendos
...      ...        ...    ...        ...              ...   ...         ...
5509  XPML11 2025-08-25   0.92 2025-08-18       Rendimento  0,92  Dividendos
5517  HTMX11 2025-09-05   1.05 2025-08-29       Rendimento  0,75  Dividendos
5534  KNCR11 2025-09-11   1.35 2025-08-29       Rendimento  1,28  Dividendos
5548  HGLG11 2025-09-12   1.10 2025-08-29       Rendimento  0,71  Dividendos
5575  XPCI11 2025-09-12   0.95 2025-08-29       Rendimento  1,15  Dividendos

[394 rows x 7 columns]

In [112]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 394 entries, 31 to 5575
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         394 non-null    object
 1   Data          394 non-null    datetime64[ns]
 2   Valor         394 non-null    float64
 3   DATA COM      394 non-null    datetime64[ns]
 4   Tipo Receita  394 non-null    object
 5   DY            394 non-null    object
 6   Natureza      394 non-null    object
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 24.6+ KB

## Aquisição

In [113]:
df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao["Natureza"] = ["Aquisição"] * len(df_aquisicao)
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono   Natureza
0    PETR4 2024-04-01   32.00                1    Luis  Aquisição
1    PETR4 2024-08-01   31.00                2    Luis  Aquisição
2    PETR4 2024-11-01   29.31                3    Luis  Aquisição
3    VALE3 2024-11-01   34.87                2    Luis  Aquisição
4   TAEE11 2025-07-01   28.96                1    Luis  Aquisição
5    PETR4 2025-09-01   31.09                1    Luis  Aquisição
6    PETR4 2025-07-01   32.87                2  Heitor  Aquisição
7    PETR4 2025-07-01   31.79                3  Heitor  Aquisição
8    VALE3 2025-08-01   33.89                2  Heitor  Aquisição
9   HGLG11 2025-08-01  152.89                1  Heitor  Aquisição
10   PETR4 2025-09-01   31.34                1  Heitor  Aquisição
11   PETR4 2025-09-01   31.75                2  Heitor  Aquisição

In [114]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            12 non-null     object
 1   Data             12 non-null     datetime64[ns]
 2   Valor            12 non-null     float64
 3   Número de Cotas  12 non-null     int64
 4   Dono             12 non-null     object
 5   Natureza         12 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 708.0+ bytes

## Une os dados

In [115]:
df_historico_carteira = pd.concat([df_historico, df_dividendos])
df_historico_carteira = pd.concat([df_historico_carteira, df_aquisicao])
df_historico_carteira

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono
0,BBSE3,2020-10-01,23.680000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
1,BBSE3,2020-11-01,28.559999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
2,BBSE3,2020-12-01,29.629999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
3,BBSE3,2021-01-01,27.660000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
4,BBSE3,2021-02-01,25.430000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7,PETR4,2025-07-01,31.790000,Aquisição,NaT,NaN,NaN,3.0,Heitor
8,VALE3,2025-08-01,33.890000,Aquisição,NaT,NaN,NaN,2.0,Heitor
9,HGLG11,2025-08-01,152.890000,Aquisição,NaT,NaN,NaN,1.0,Heitor
10,PETR4,2025-09-01,31.340000,Aquisição,NaT,NaN,NaN,1.0,Heitor
11,PETR4,2025-09-01,31.750000,Aquisição,NaT,NaN,NaN,2.0,Heitor

In [116]:
df_historico_carteira.sort_values(by="Data", inplace=True)
df_historico_carteira.index = range(0, len(df_historico_carteira))
df_historico_carteira

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono
0,BBSE3,2020-10-01,23.680000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
1,TAEE11,2020-10-01,28.150000,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
2,KNCR11,2020-10-01,91.949997,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
3,HGLG11,2020-10-01,161.051880,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
4,VALE3,2020-10-01,60.549999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
943,TAEE11,2025-11-27,0.320000,Dividendos,2025-04-29,Dividendo,0.89,NaN,NaN
944,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,NaN,NaN
945,TAEE11,2025-11-27,0.630000,Dividendos,2025-08-18,JCP,1.87,NaN,NaN
946,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,NaN,NaN
947,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,NaN,NaN

In [98]:
df_historico_carteira.loc[df_historico_carteira["Natureza"] == "Aquisição"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono
167,PETR4,01-04-2024,32.00,Aquisição,NaN,NaN,NaN,1.0,Luis
302,TAEE11,01-07-2025,28.96,Aquisição,NaN,NaN,NaN,1.0,Luis
303,PETR4,01-07-2025,31.79,Aquisição,NaN,NaN,NaN,3.0,Heitor
306,PETR4,01-07-2025,32.87,Aquisição,NaN,NaN,NaN,2.0,Heitor
349,PETR4,01-08-2024,31.00,Aquisição,NaN,NaN,NaN,2.0,Luis
353,HGLG11,01-08-2025,152.89,Aquisição,NaN,NaN,NaN,1.0,Heitor
354,VALE3,01-08-2025,33.89,Aquisição,NaN,NaN,NaN,2.0,Heitor
406,PETR4,01-09-2025,31.09,Aquisição,NaN,NaN,NaN,1.0,Luis
408,PETR4,01-09-2025,31.34,Aquisição,NaN,NaN,NaN,1.0,Heitor
409,PETR4,01-09-2025,31.75,Aquisição,NaN,NaN,NaN,2.0,Heitor
494,VALE3,01-11-2024,34.87,Aquisição,NaN,NaN,NaN,2.0,Luis
497,PETR4,01-11-2024,29.31,Aquisição,NaN,NaN,NaN,3.0,Luis

In [168]:
a = df_historico_carteira.loc[df_historico_carteira["Data"] >= '2024-04-01']
a

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono
626,TAEE11,2024-04-01,35.220001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
627,PETR4,2024-04-01,32.000000,Aquisição,NaT,NaN,NaN,1.0,Luis
628,HTMX11,2024-04-01,176.889999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
629,XPML11,2024-04-01,116.309998,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
630,BBSE3,2024-04-01,32.200001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
943,TAEE11,2025-11-27,0.320000,Dividendos,2025-04-29,Dividendo,0.89,NaN,NaN
944,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,NaN,NaN
945,TAEE11,2025-11-27,0.630000,Dividendos,2025-08-18,JCP,1.87,NaN,NaN
946,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,NaN,NaN
947,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,NaN,NaN

In [169]:
lista_valor_investido = []
lista_preco_unitario = []
lista_preco_total = []
lista_dividendos_total = []
lista_dividendos_total_d = []

lista_valor_investido_acumulado_distinto = []
lista_preco_total_acumulado_distinto = []
# lista_valor_investido_acumulado = []
# lista_preco_total_acumulado = []
lista_dividendos_acumulados = []

dicionario_acumulados_distintos = {
    "Heitor": [0, 0, 0],
    "Luis": [0, 0, 0]
}

# valor_investido_acumulado = 0
# preco_total_acumulado = 0
dividendos_acumulados = 0

for i in a.index:
    ativo = a.loc[i, "Ativo"]
    data = a.loc[i, "Data"]
    valor = a.loc[i, "Valor"]
    dono = a.loc[i, "Dono"]

    valor_investido = 0
    preco_total = 0
    valor_dividendos = 0

    if a.loc[i, "Natureza"] == "Aquisição":
        preco = df_historico.loc[(df_historico["Ativo"] == ativo) & (df_historico["Data"] == data)]["Valor"].values[0]
        num_cotas = a.loc[i, 'Número de Cotas']
        valor_investido = num_cotas * valor
        preco_total = preco * num_cotas

        lista_valor_investido.append(valor_investido)
        lista_preco_unitario.append(preco)
        lista_preco_total.append(preco_total)
    else:
        lista_valor_investido.append(None)
        lista_preco_unitario.append(None)
        lista_preco_total.append(None)

    if a.loc[i, "Natureza"] == "Dividendos":
        data_com = a.loc[i, "DATA COM"]
        num_cotas = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] <= data_com)]["Número de Cotas"].sum()
        valor_dividendos = valor * num_cotas

        lista_dividendos_total.append(valor_dividendos)

        num_cotas = df_aquisicao.loc[
            (df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] <= data_com) & (df_aquisicao["Dono"] == dono)
        ]["Número de Cotas"].sum()
        valor_dividendos_d = valor * num_cotas
        lista_dividendos_total_d.append(valor_dividendos_d)
    else:
        lista_dividendos_total.append(None)
        lista_dividendos_total_d.append(None)

    if dono == "Luis" or dono == "Heitor":
        dicionario_acumulados_distintos[dono][0] += valor_investido
        lista_valor_investido_acumulado_distinto.append(dicionario_acumulados_distintos[dono][0])
        dicionario_acumulados_distintos[dono][1] += preco_total
        lista_preco_total_acumulado_distinto.append(dicionario_acumulados_distintos[dono][1])
    else:
        lista_valor_investido_acumulado_distinto.append(None)
        lista_preco_total_acumulado_distinto.append(None)

    # valor_investido_acumulado += valor_investido
    # preco_total_acumulado += preco_total
    dividendos_acumulados += valor_dividendos

    # lista_valor_investido_acumulado.append(valor_investido_acumulado)
    # lista_preco_total_acumulado.append(preco_total_acumulado)
    lista_dividendos_acumulados.append(dividendos_acumulados)


a["Valor Investido"] = lista_valor_investido
a["Valor Investido Acumulado"] = lista_valor_investido_acumulado_distinto
# a["Valor Investido Acumulado"] = lista_valor_investido_acumulado
a["Preço Unitário"] = lista_preco_unitario
a["Preço Total"] = lista_preco_total
a["Preço Total Acumulado"] = lista_preco_total_acumulado_distinto
# a["Preço Total Acumulado"] = lista_preco_total_acumulado
a["Dividendos Totais D"] = lista_dividendos_total_d
a["Dividendos Totais"] = lista_dividendos_total
a["Dividendos Acumulados"] = lista_dividendos_acumulados
a

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Valor Investido"] = lista_valor_investido
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Valor Investido Acumulado"] = lista_valor_investido_acumulado_distinto
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Preço Unitário"] = lista_preco_unitario
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Preço Total"] = lista_preco_total
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Preço Total Acumulado"] = lista_preco_total_acumulado_distinto
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Dividendos Totais D"] = lista_dividendos_total_d
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Dividendos Totais"] = lista_dividendos_total
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\2095147181.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["Dividendos Acumulados"] = lista_dividendos_acumulados

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono,Valor Investido,Valor Investido Acumulado,Preço Unitário,Preço Total,Preço Total Acumulado,Dividendos Totais D,Dividendos Totais,Dividendos Acumulados
626,TAEE11,2024-04-01,35.220001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
627,PETR4,2024-04-01,32.000000,Aquisição,NaT,NaN,NaN,1.0,Luis,32.0,32.0,42.02,42.02,42.02,NaN,NaN,0.00
628,HTMX11,2024-04-01,176.889999,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
629,XPML11,2024-04-01,116.309998,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
630,BBSE3,2024-04-01,32.200001,Histórico de Preço,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,TAEE11,2025-11-27,0.320000,Dividendos,2025-04-29,Dividendo,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,51.71
944,TAEE11,2025-11-27,0.230000,Dividendos,2025-08-18,Dividendo,0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.23,51.94
945,TAEE11,2025-11-27,0.630000,Dividendos,2025-08-18,JCP,1.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.63,52.57
946,PETR4,2025-12-22,0.130000,Dividendos,2025-08-21,JCP,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.43,54.00
947,PETR4,2025-12-22,0.200000,Dividendos,2025-08-21,Dividendo,0.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.20,56.20

In [170]:
a.loc[df_historico_carteira["Natureza"] == "Aquisição"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono,Valor Investido,Valor Investido Acumulado,Preço Unitário,Preço Total,Preço Total Acumulado,Dividendos Totais D,Dividendos Totais,Dividendos Acumulados
627,PETR4,2024-04-01,32.00,Aquisição,NaT,NaN,NaN,1.0,Luis,32.00,32.00,42.020000,42.020000,42.020000,NaN,NaN,0.00
693,PETR4,2024-08-01,31.00,Aquisição,NaT,NaN,NaN,2.0,Luis,62.00,94.00,39.369999,78.739998,120.759998,NaN,NaN,2.89
743,VALE3,2024-11-01,34.87,Aquisição,NaT,NaN,NaN,2.0,Luis,69.74,163.74,58.779999,117.559998,238.319996,NaN,NaN,3.92
747,PETR4,2024-11-01,29.31,Aquisição,NaT,NaN,NaN,3.0,Luis,87.93,251.67,38.900002,116.700005,355.020000,NaN,NaN,3.92
882,PETR4,2025-07-01,31.79,Aquisição,NaT,NaN,NaN,3.0,Heitor,95.37,95.37,32.639999,97.919998,97.919998,NaN,NaN,34.08
884,TAEE11,2025-07-01,28.96,Aquisição,NaT,NaN,NaN,1.0,Luis,28.96,280.63,33.360001,33.360001,388.380001,NaN,NaN,34.08
889,PETR4,2025-07-01,32.87,Aquisição,NaT,NaN,NaN,2.0,Heitor,65.74,161.11,32.639999,65.279999,163.199997,NaN,NaN,34.08
903,HGLG11,2025-08-01,152.89,Aquisição,NaT,NaN,NaN,1.0,Heitor,152.89,314.00,154.990005,154.990005,318.190002,NaN,NaN,34.08
904,VALE3,2025-08-01,33.89,Aquisição,NaT,NaN,NaN,2.0,Heitor,67.78,381.78,55.560001,111.120003,429.310005,NaN,NaN,34.08
914,PETR4,2025-09-01,31.09,Aquisição,NaT,NaN,NaN,1.0,Luis,31.09,311.72,31.510000,31.510000,419.890001,NaN,NaN,36.78
915,PETR4,2025-09-01,31.75,Aquisição,NaT,NaN,NaN,2.0,Heitor,63.50,445.28,31.510000,63.020000,492.330006,NaN,NaN,36.78
924,PETR4,2025-09-01,31.34,Aquisição,NaT,NaN,NaN,1.0,Heitor,31.34,476.62,31.510000,31.510000,523.840006,NaN,NaN,36.78

In [171]:
a.loc[df_historico_carteira["Natureza"] == "Dividendos"]

,Ativo,Data,Valor,Natureza,DATA COM,Tipo Receita,DY,Número de Cotas,Dono,Valor Investido,Valor Investido Acumulado,Preço Unitário,Preço Total,Preço Total Acumulado,Dividendos Totais D,Dividendos Totais,Dividendos Acumulados
636,HTMX11,2024-04-05,1.66,Dividendos,2024-03-28,Rendimento,"0,92",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00
637,KNCR11,2024-04-11,0.95,Dividendos,2024-03-28,Rendimento,"0,92",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00
638,XPCI11,2024-04-12,0.90,Dividendos,2024-03-28,Rendimento,"0,99",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00
639,HGLG11,2024-04-12,1.10,Dividendos,2024-03-28,Rendimento,"0,65",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00
640,XPML11,2024-04-25,0.91,Dividendos,2024-04-18,Rendimento,"0,78",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,TAEE11,2025-11-27,0.32,Dividendos,2025-04-29,Dividendo,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,51.71
944,TAEE11,2025-11-27,0.23,Dividendos,2025-08-18,Dividendo,0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.23,51.94
945,TAEE11,2025-11-27,0.63,Dividendos,2025-08-18,JCP,1.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.63,52.57
946,PETR4,2025-12-22,0.13,Dividendos,2025-08-21,JCP,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.43,54.00
947,PETR4,2025-12-22,0.20,Dividendos,2025-08-21,Dividendo,0.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.20,56.20

In [153]:
b = a.loc[936, :]
b

Ativo                                     XPCI11
Data                         2025-09-15 00:00:00
Valor                                  82.239998
Natureza                      Histórico de Preço
DATA COM                                     NaT
Tipo Receita                                 NaN
DY                                           NaN
Número de Cotas                              NaN
Dono                                         NaN
Valor Investido                              NaN
Valor Investido Acumulado                 788.34
Preço Unitário                               NaN
Preço Total                                  NaN
Preço Total Acumulado                 943.730007
Dividendos Totais                            NaN
Dividendos Acumulados                      45.44
Name: 936, dtype: object

In [154]:
b["Dono"] = "Luis"
b

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_7620\1201517889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b["Dono"] = "Luis"

Ativo                                     XPCI11
Data                         2025-09-15 00:00:00
Valor                                  82.239998
Natureza                      Histórico de Preço
DATA COM                                     NaT
Tipo Receita                                 NaN
DY                                           NaN
Número de Cotas                              NaN
Dono                                        Luis
Valor Investido                              NaN
Valor Investido Acumulado                 788.34
Preço Unitário                               NaN
Preço Total                                  NaN
Preço Total Acumulado                 943.730007
Dividendos Totais                            NaN
Dividendos Acumulados                      45.44
Name: 936, dtype: object

## Cria Medidas

In [45]:
calendario = []

for i in ativos_concatenados.index:
    if not pd.isnull(ativos_concatenados.loc[i, "Data"]):
        calendario.append(ativos_concatenados.loc[i, "Data"])
    elif not pd.isnull(ativos_concatenados.loc[i, "DATA PAGAMENTO"]):
        calendario.append(ativos_concatenados.loc[i, "DATA PAGAMENTO"])
    else:
        calendario.append(ativos_concatenados.loc[i, "Data de Aquisição"])

ativos_concatenados["Data Calendário"] = calendario
ativos_concatenados

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,...,Dividendo,DATA COM,DATA PAGAMENTO,Tipo Receita,DY,Dono,Preço de Aquisição,Número de Cotas,Data de Aquisição,Data Calendário
0,24.350000,26.049999,23.610001,23.680000,88234500.0,15.714323,0.000000,NaN,BBSE3,01-10-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-10-2020
1,23.680000,29.799999,23.680000,28.559999,120982300.0,18.952745,0.000000,NaN,BBSE3,01-11-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-11-2020
2,29.000000,30.760000,28.260000,29.629999,70198700.0,19.662809,0.000000,NaN,BBSE3,01-12-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-12-2020
3,29.629999,30.450001,27.660000,27.660000,86915800.0,18.355495,0.000000,NaN,BBSE3,01-01-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2021
4,28.000000,29.000000,25.430000,25.430000,89982600.0,16.875643,0.476121,NaN,BBSE3,01-02-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,79",3.0,01-07-2025,01-07-2025
680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VALE3,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"33,89",2.0,01-08-2025,01-08-2025
681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGLG11,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"152,89",1.0,01-08-2025,01-08-2025
682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,34",1.0,01-09-2025,01-09-2025
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,75",2.0,01-09-2025,01-09-2025

In [46]:
ativos_concatenados.sort_values(by="Data Calendário")
ativos_concatenados.index = range(0, len(ativos_concatenados))
ativos_concatenados

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,...,Dividendo,DATA COM,DATA PAGAMENTO,Tipo Receita,DY,Dono,Preço de Aquisição,Número de Cotas,Data de Aquisição,Data Calendário
0,24.350000,26.049999,23.610001,23.680000,88234500.0,15.714323,0.000000,NaN,BBSE3,01-10-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-10-2020
1,23.680000,29.799999,23.680000,28.559999,120982300.0,18.952745,0.000000,NaN,BBSE3,01-11-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-11-2020
2,29.000000,30.760000,28.260000,29.629999,70198700.0,19.662809,0.000000,NaN,BBSE3,01-12-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-12-2020
3,29.629999,30.450001,27.660000,27.660000,86915800.0,18.355495,0.000000,NaN,BBSE3,01-01-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2021
4,28.000000,29.000000,25.430000,25.430000,89982600.0,16.875643,0.476121,NaN,BBSE3,01-02-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,79",3.0,01-07-2025,01-07-2025
680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VALE3,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"33,89",2.0,01-08-2025,01-08-2025
681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGLG11,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"152,89",1.0,01-08-2025,01-08-2025
682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,34",1.0,01-09-2025,01-09-2025
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,NaN,Heitor,"31,75",2.0,01-09-2025,01-09-2025

In [47]:
preco_total_historico = []

for i in ativos_concatenados.index:
    preco_historico = ativos_concatenados.loc[i, "close"]
    numero_cotas = ativos_concatenados.loc[i, "Número de Cotas"]
    preco_total_historico.append(preco_historico * numero_cotas)

ativos_concatenados["Preço Total Histórico"] = preco_total_historico

In [48]:
ativos_concatenados

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data,...,DATA COM,DATA PAGAMENTO,Tipo Receita,DY,Dono,Preço de Aquisição,Número de Cotas,Data de Aquisição,Data Calendário,Preço Total Histórico
0,24.350000,26.049999,23.610001,23.680000,88234500.0,15.714323,0.000000,NaN,BBSE3,01-10-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-10-2020,NaN
1,23.680000,29.799999,23.680000,28.559999,120982300.0,18.952745,0.000000,NaN,BBSE3,01-11-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-11-2020,NaN
2,29.000000,30.760000,28.260000,29.629999,70198700.0,19.662809,0.000000,NaN,BBSE3,01-12-2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-12-2020,NaN
3,29.629999,30.450001,27.660000,27.660000,86915800.0,18.355495,0.000000,NaN,BBSE3,01-01-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2021,NaN
4,28.000000,29.000000,25.430000,25.430000,89982600.0,16.875643,0.476121,NaN,BBSE3,01-02-2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2021,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,Heitor,"31,79",3.0,01-07-2025,01-07-2025,NaN
680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VALE3,NaN,...,NaN,NaN,NaN,NaN,Heitor,"33,89",2.0,01-08-2025,01-08-2025,NaN
681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HGLG11,NaN,...,NaN,NaN,NaN,NaN,Heitor,"152,89",1.0,01-08-2025,01-08-2025,NaN
682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,Heitor,"31,34",1.0,01-09-2025,01-09-2025,NaN
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PETR4,NaN,...,NaN,NaN,NaN,NaN,Heitor,"31,75",2.0,01-09-2025,01-09-2025,NaN

In [ ]:
# ativos_concatenados.to_csv('Dados Modelados/historico_ativos_carteira.csv', index=False)