# Bibliotecas

In [246]:
import pandas as pd
import yahooquery as yq
from itertools import product

# Ativos da Carteira

In [2]:
df_ativos = pd.read_csv('Dados Modelados/Ativos.csv')
lista_ativos_selecionados = [
    # Ações
    "BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3",

    # FIIs
    "HGLG11",
    "HTMX11",
    "KNCR11",
    "XPML11",
    "XPCI11"

]

lista_index = []
for i in df_ativos.index:
    if df_ativos.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_ativos = df_ativos.loc[lista_index, :]
df_ativos.index = range(0, len(df_ativos))
df_ativos['Tipo'] = "Ação"
df_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação

In [3]:
df_fiis = pd.read_csv('Dados Modelados/FIIs.csv')

lista_index = []
for i in df_fiis.index:
    if df_fiis.loc[i, "ATIVO"] in lista_ativos_selecionados:
        lista_index.append(i)

df_fiis = df_fiis.loc[lista_index, :]
df_fiis.index = range(0, len(df_fiis))
df_fiis['Tipo'] = "FII"
df_fiis

    ATIVO                 SETOR    INDUSTRIA Tipo
0  KNCR11       REIT - Mortgage  Real Estate  FII
1  HGLG11    REIT - Diversified  Real Estate  FII
2  XPCI11       REIT - Mortgage  Real Estate  FII
3  XPML11         REIT - Retail  Real Estate  FII
4  HTMX11  REIT - Hotel & Motel  Real Estate  FII

In [4]:
df_carteira_ativos = pd.concat([df_ativos, df_fiis])
df_carteira_ativos.index = range(0, len(df_carteira_ativos))
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII

In [5]:
acoes = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "Ação"]['ATIVO'].values
acoes.sort()
print(acoes)

fundos = df_carteira_ativos.loc[df_carteira_ativos['Tipo'] == "FII"]['ATIVO'].values
fundos.sort()
print(fundos)

['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']

In [6]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1
}

balanco_ativos = []
for i in df_carteira_ativos.index:
    balanco_ativos.append(
        balanco[df_carteira_ativos.loc[[i], "ATIVO"].values[0]]
    )

df_carteira_ativos["Balanço de Cotas"] = balanco_ativos
df_carteira_ativos

,ATIVO,SETOR,INDUSTRIA,DATA,RECOMENDACAO,Tipo,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,11-09-2025,hold,Ação,1
1,VALE3,Other Industrial Metals & Mining,Basic Materials,11-09-2025,buy,Ação,1
2,PETR4,Oil & Gas Integrated,Energy,11-09-2025,buy,Ação,10
3,TAEE11,Utilities - Regulated Electric,Utilities,11-09-2025,underperform,Ação,1
4,KNCR11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
5,HGLG11,REIT - Diversified,Real Estate,NaN,NaN,FII,1
6,XPCI11,REIT - Mortgage,Real Estate,NaN,NaN,FII,1
7,XPML11,REIT - Retail,Real Estate,NaN,NaN,FII,1
8,HTMX11,REIT - Hotel & Motel,Real Estate,NaN,NaN,FII,1

In [323]:
df_carteira_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Histórico

In [274]:
df_ativos = pd.read_csv('Dados Modelados/historico_Ativos.csv')
df_ativos = df_ativos.loc[df_ativos["Ativo"].isin(lista_ativos_selecionados)]
# df_ativos.index = range(0, len(df_ativos))
# df_ativos['Tipo Ativo'] = "Ação"
df_ativos

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
1098,24.350000,26.049999,23.610001,23.680000,88234500,15.714323,0.000000,NaN,BBSE3,01-10-2020
1099,23.680000,29.799999,23.680000,28.559999,120982300,18.952745,0.000000,NaN,BBSE3,01-11-2020
1100,29.000000,30.760000,28.260000,29.629999,70198700,19.662809,0.000000,NaN,BBSE3,01-12-2020
1101,29.629999,30.450001,27.660000,27.660000,86915800,18.355495,0.000000,NaN,BBSE3,01-01-2021
1102,28.000000,29.000000,25.430000,25.430000,89982600,16.875643,0.476121,NaN,BBSE3,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
2743,35.360001,35.529999,33.669998,34.930000,31750500,34.043571,0.000000,NaN,TAEE11,01-06-2025
2744,34.810001,35.169998,33.160000,33.360001,26490900,32.513416,0.000000,NaN,TAEE11,01-07-2025
2745,33.560001,34.919998,32.840000,34.869999,47238700,33.985092,0.869171,NaN,TAEE11,01-08-2025
2746,34.880001,35.220001,34.180000,34.900002,10775000,34.900002,0.000000,NaN,TAEE11,01-09-2025
2747,34.950001,35.150002,34.849998,34.980000,750000,34.980000,0.000000,NaN,TAEE11,11-09-2025

In [275]:
df_fiis = pd.read_csv('Dados Modelados/historico_Fii.csv')
df_fiis = df_fiis.loc[df_fiis["Ativo"].isin(lista_ativos_selecionados)]
# df_fiis.index = range(0, len(df_fiis))
# df_fiis['Tipo Ativo'] = "FII"
df_fiis

,open,high,low,close,volume,adjclose,dividends,splits,Ativo,Data
674,89.930000,94.480003,88.019997,91.949997,913427.0,58.732109,0.00,NaN,KNCR11,01-10-2020
675,91.949997,92.989998,87.910004,88.699997,863036.0,56.656181,0.00,NaN,KNCR11,01-11-2020
676,88.250000,88.599998,85.500000,87.050003,1348549.0,55.602295,0.00,NaN,KNCR11,01-12-2020
677,87.050003,89.769997,86.699997,88.820000,832932.0,56.732868,0.00,NaN,KNCR11,01-01-2021
678,88.699997,91.489998,87.000000,89.410004,924011.0,57.109722,0.00,NaN,KNCR11,01-02-2021
...,...,...,...,...,...,...,...,...,...,...
5210,141.600006,147.000000,140.600006,145.300003,78781.0,139.966797,1.54,NaN,HTMX11,01-06-2025
5211,145.160004,146.169998,141.410004,145.470001,71302.0,141.689133,1.50,NaN,HTMX11,01-07-2025
5212,141.020004,143.699997,139.000000,139.869995,75358.0,137.655762,1.22,NaN,HTMX11,01-08-2025
5213,138.949997,139.000000,136.500000,138.399994,48631.0,137.361023,1.05,NaN,HTMX11,01-09-2025
5214,0.000000,0.000000,0.000000,138.399994,0.0,138.399994,0.00,NaN,HTMX11,15-09-2025

In [276]:
df_historico = pd.concat([df_ativos, df_fiis])
df_historico = df_historico.filter(["Ativo", "Data", "close"])
df_historico.rename(columns={"close": "Valor"}, inplace=True)
df_historico["Data"] = pd.to_datetime(df_historico["Data"], format="%d-%m-%Y")
df_historico.index = range(0, len(df_historico))
df_historico

      Ativo       Data       Valor
0     BBSE3 2020-10-01   23.680000
1     BBSE3 2020-11-01   28.559999
2     BBSE3 2020-12-01   29.629999
3     BBSE3 2021-01-01   27.660000
4     BBSE3 2021-02-01   25.430000
..      ...        ...         ...
537  HTMX11 2025-06-01  145.300003
538  HTMX11 2025-07-01  145.470001
539  HTMX11 2025-08-01  139.869995
540  HTMX11 2025-09-01  138.399994
541  HTMX11 2025-09-15  138.399994

[542 rows x 3 columns]

In [277]:
df_historico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ativo   542 non-null    object
 1   Data    542 non-null    datetime64[ns]
 2   Valor   542 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 12.8+ KB

## Aquisição

In [289]:
df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono
0    PETR4 2024-04-01   32.00                1    Luis
1    PETR4 2024-08-01   31.00                2    Luis
2    PETR4 2024-11-01   29.31                3    Luis
3    VALE3 2024-11-01   34.87                2    Luis
4   TAEE11 2025-07-01   28.96                1    Luis
6    PETR4 2025-07-01   32.87                2  Heitor
7    PETR4 2025-07-01   31.79                3  Heitor
8    VALE3 2025-08-01   33.89                2  Heitor
9   HGLG11 2025-08-01  152.89                1  Heitor
5    PETR4 2025-09-01   31.09                1    Luis
10   PETR4 2025-09-01   31.34                1  Heitor
11   PETR4 2025-09-01   31.75                2  Heitor

In [290]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            12 non-null     object
 1   Data             12 non-null     datetime64[ns]
 2   Valor            12 non-null     float64
 3   Número de Cotas  12 non-null     int64
 4   Dono             12 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 576.0+ bytes

### Acumula cotas e agrupa aquisições no mesmo dia

In [291]:
# Acumula as cotas por ativo e dono

dic_cotas_acum = {
    "Heitor": {},
    "Luis": {}
}

lista_cotas_acum = []

for i in df_aquisicao.index:
    ativo = df_aquisicao.loc[i, "Ativo"]
    cotas = df_aquisicao.loc[i, "Número de Cotas"]
    dono = df_aquisicao.loc[i, "Dono"]
    if ativo not in dic_cotas_acum[dono]:
        dic_cotas_acum[dono][ativo] = cotas
    else:
        dic_cotas_acum[dono][ativo] += cotas
    lista_cotas_acum.append(dic_cotas_acum[dono][ativo])

df_aquisicao["Cotas Acumuladas"] = lista_cotas_acum
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Cotas Acumuladas", "Dono"])
df_aquisicao

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    PETR4 2024-04-01   32.00                1                 1    Luis
1    PETR4 2024-08-01   31.00                2                 3    Luis
2    PETR4 2024-11-01   29.31                3                 6    Luis
3    VALE3 2024-11-01   34.87                2                 2    Luis
4   TAEE11 2025-07-01   28.96                1                 1    Luis
6    PETR4 2025-07-01   32.87                2                 2  Heitor
7    PETR4 2025-07-01   31.79                3                 5  Heitor
8    VALE3 2025-08-01   33.89                2                 2  Heitor
9   HGLG11 2025-08-01  152.89                1                 1  Heitor
5    PETR4 2025-09-01   31.09                1                 7    Luis
10   PETR4 2025-09-01   31.34                1                 6  Heitor
11   PETR4 2025-09-01   31.75                2                 8  Heitor

In [293]:
df_compras_mesmo_dia = df_aquisicao.loc[df_aquisicao.duplicated(subset=["Ativo", "Data", "Dono"], keep=False)]
df_compras_mesmo_dia

    Ativo       Data  Valor  Número de Cotas  Cotas Acumuladas    Dono
6   PETR4 2025-07-01  32.87                2                 2  Heitor
7   PETR4 2025-07-01  31.79                3                 5  Heitor
10  PETR4 2025-09-01  31.34                1                 6  Heitor
11  PETR4 2025-09-01  31.75                2                 8  Heitor

In [294]:
# Unifica as aquisições do mesmo dono no mesmo dia

indices_mesmo_dia = list(df_compras_mesmo_dia.index)

dicionario_novo = {"Ativo": [], "Data": [], "Valor": [], "Número de Cotas": [], "Cotas Acumuladas": [], "Dono": []}

ativo_anterior = None
data_anterior = None
dono_anterior = None
valor_total = 0
cotas_totais = 0
maior_cota_acumulada = -1
primeiro = True

for i in df_compras_mesmo_dia.index:
    ativo = df_compras_mesmo_dia.loc[i, "Ativo"]
    data = df_compras_mesmo_dia.loc[i, "Data"]
    valor = df_compras_mesmo_dia.loc[i, "Valor"]
    num_cotas = df_compras_mesmo_dia.loc[i, "Número de Cotas"]
    num_cotas_acumul = df_compras_mesmo_dia.loc[i, "Cotas Acumuladas"]
    dono = df_compras_mesmo_dia.loc[i, "Dono"]

    if (not primeiro) and ((ativo != ativo_anterior) or (data != data_anterior) or (dono != dono_anterior)):
        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)

        valor_total = valor * num_cotas
        cotas_totais = num_cotas
        maior_cota_acumulada = num_cotas_acumul
    elif i == df_compras_mesmo_dia.index[-1]:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

        if num_cotas_acumul > maior_cota_acumulada:
            maior_cota_acumulada = num_cotas_acumul

        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
    else:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

    if num_cotas_acumul > maior_cota_acumulada:
        maior_cota_acumulada = num_cotas_acumul
    
    ativo_anterior = ativo
    data_anterior = data
    dono_anterior = dono
    primeiro = False

pd.DataFrame(dicionario_novo)

   Ativo       Data      Valor  Número de Cotas  Cotas Acumuladas    Dono
0  PETR4 2025-07-01  32.222000                5                 5  Heitor
1  PETR4 2025-09-01  31.613333                3                 8  Heitor

In [295]:
# Remove as aquisições do mesmo dia e adiciona a média ponderada da compra

df_aquisicao.drop(indices_mesmo_dia, inplace=True)
df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao.index = range(len(df_aquisicao))
df_aquisicao

    Ativo       Data       Valor  Número de Cotas  Cotas Acumuladas    Dono
0   PETR4 2024-04-01   32.000000                1                 1    Luis
1   PETR4 2024-08-01   31.000000                2                 3    Luis
2   PETR4 2024-11-01   29.310000                3                 6    Luis
3   VALE3 2024-11-01   34.870000                2                 2    Luis
4  TAEE11 2025-07-01   28.960000                1                 1    Luis
5   PETR4 2025-07-01   32.222000                5                 5  Heitor
6   VALE3 2025-08-01   33.890000                2                 2  Heitor
7  HGLG11 2025-08-01  152.890000                1                 1  Heitor
8   PETR4 2025-09-01   31.090000                1                 7    Luis
9   PETR4 2025-09-01   31.613333                3                 8  Heitor

### Replica ativos para todas as datas

In [247]:
ativos = pd.unique(df_aquisicao["Ativo"])
data = pd.unique(df_aquisicao["Data"])
dono = pd.unique(df_aquisicao["Dono"])

permutacao = list(product(ativos, data, dono))
df_permutacao = pd.DataFrame(permutacao, columns=["Ativo", "Data", "Dono"])
df_permutacao

     Ativo       Data    Dono
0    PETR4 2024-04-01    Luis
1    PETR4 2024-04-01  Heitor
2    PETR4 2024-08-01    Luis
3    PETR4 2024-08-01  Heitor
4    PETR4 2024-11-01    Luis
5    PETR4 2024-11-01  Heitor
6    PETR4 2025-07-01    Luis
7    PETR4 2025-07-01  Heitor
8    PETR4 2025-08-01    Luis
9    PETR4 2025-08-01  Heitor
10   PETR4 2025-09-01    Luis
11   PETR4 2025-09-01  Heitor
12   VALE3 2024-04-01    Luis
13   VALE3 2024-04-01  Heitor
14   VALE3 2024-08-01    Luis
15   VALE3 2024-08-01  Heitor
16   VALE3 2024-11-01    Luis
17   VALE3 2024-11-01  Heitor
18   VALE3 2025-07-01    Luis
19   VALE3 2025-07-01  Heitor
20   VALE3 2025-08-01    Luis
21   VALE3 2025-08-01  Heitor
22   VALE3 2025-09-01    Luis
23   VALE3 2025-09-01  Heitor
24  TAEE11 2024-04-01    Luis
25  TAEE11 2024-04-01  Heitor
26  TAEE11 2024-08-01    Luis
27  TAEE11 2024-08-01  Heitor
28  TAEE11 2024-11-01    Luis
29  TAEE11 2024-11-01  Heitor
30  TAEE11 2025-07-01    Luis
31  TAEE11 2025-07-01  Heitor
32  TAEE11 2025-08-01    Luis
33  TAEE11 2025-08-01  Heitor
34  TAEE11 2025-09-01    Luis
35  TAEE11 2025-09-01  Heitor
36  HGLG11 2024-04-01    Luis
37  HGLG11 2024-04-01  Heitor
38  HGLG11 2024-08-01    Luis
39  HGLG11 2024-08-01  Heitor
40  HGLG11 2024-11-01    Luis
41  HGLG11 2024-11-01  Heitor
42  HGLG11 2025-07-01    Luis
43  HGLG11 2025-07-01  Heitor
44  HGLG11 2025-08-01    Luis
45  HGLG11 2025-08-01  Heitor
46  HGLG11 2025-09-01    Luis
47  HGLG11 2025-09-01  Heitor

In [264]:
df_aquisicao_geral = pd.DataFrame()

for i in df_permutacao.index:
    ativo = df_permutacao.loc[i, "Ativo"]
    data = df_permutacao.loc[i, "Data"]
    dono = df_permutacao.loc[i, "Dono"]

    serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] == data) & (df_aquisicao["Dono"] == dono)]
    if len(serie_aquisicao) >= 1:
        df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
    else:
        serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)]
        if len(serie_aquisicao) < 1:
            serie_aquisicao = pd.Series(
                {
                    "Ativo": ativo, 
                    "Data": data,
                    "Valor": 0,
                    "Número de Cotas": 0,
                    "Cotas Acumuladas": 0,
                    "Dono": dono
                }
            ).to_frame().T

            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
        else:
            serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)].iloc[-1, :]
            serie_aquisicao.loc["Data"] = data
            serie_aquisicao.loc["Valor"] = 0
            serie_aquisicao.loc["Número de Cotas"] = 0
            serie_aquisicao = serie_aquisicao.to_frame().T
            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])

df_aquisicao_geral.index = range(len(df_aquisicao_geral))
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor
2,PETR4,2024-08-01 00:00:00,31.0,2,3,Luis
3,PETR4,2024-08-01 00:00:00,0,0,0,Heitor
4,PETR4,2024-11-01 00:00:00,29.31,3,6,Luis
5,PETR4,2024-11-01 00:00:00,0,0,0,Heitor
6,PETR4,2025-07-01 00:00:00,0,0,6,Luis
7,PETR4,2025-07-01 00:00:00,32.222,5,5,Heitor
8,PETR4,2025-08-01 00:00:00,0,0,6,Luis
9,PETR4,2025-08-01 00:00:00,0,0,5,Heitor
10,PETR4,2025-09-01 00:00:00,31.09,1,7,Luis
11,PETR4,2025-09-01 00:00:00,31.613333,3,8,Heitor
12,VALE3,2024-04-01 00:00:00,0,0,0,Luis
13,VALE3,2024-04-01 00:00:00,0,0,0,Heitor
14,VALE3,2024-08-01 00:00:00,0,0,0,Luis
15,VALE3,2024-08-01 00:00:00,0,0,0,Heitor
16,VALE3,2024-11-01 00:00:00,34.87,2,2,Luis
17,VALE3,2024-11-01 00:00:00,0,0,0,Heitor
18,VALE3,2025-07-01 00:00:00,0,0,2,Luis
19,VALE3,2025-07-01 00:00:00,0,0,0,Heitor
20,VALE3,2025-08-01 00:00:00,0,0,2,Luis
21,VALE3,2025-08-01 00:00:00,33.89,2,2,Heitor
22,VALE3,2025-09-01 00:00:00,0,0,2,Luis
23,VALE3,2025-09-01 00:00:00,0,0,2,Heitor
24,TAEE11,2024-04-01 00:00:00,0,0,0,Luis
25,TAEE11,2024-04-01 00:00:00,0,0,0,Heitor
26,TAEE11,2024-08-01 00:00:00,0,0,0,Luis
27,TAEE11,2024-08-01 00:00:00,0,0,0,Heitor
28,TAEE11,2024-11-01 00:00:00,0,0,0,Luis
29,TAEE11,2024-11-01 00:00:00,0,0,0,Heitor
30,TAEE11,2025-07-01 00:00:00,28.96,1,1,Luis
31,TAEE11,2025-07-01 00:00:00,0,0,0,Heitor
32,TAEE11,2025-08-01 00:00:00,0,0,1,Luis
33,TAEE11,2025-08-01 00:00:00,0,0,0,Heitor
34,TAEE11,2025-09-01 00:00:00,0,0,1,Luis
35,TAEE11,2025-09-01 00:00:00,0,0,0,Heitor
36,HGLG11,2024-04-01 00:00:00,0,0,0,Luis
37,HGLG11,2024-04-01 00:00:00,0,0,0,Heitor
38,HGLG11,2024-08-01 00:00:00,0,0,0,Luis
39,HGLG11,2024-08-01 00:00:00,0,0,0,Heitor
40,HGLG11,2024-11-01 00:00:00,0,0,0,Luis
41,HGLG11,2024-11-01 00:00:00,0,0,0,Heitor
42,HGLG11,2025-07-01 00:00:00,0,0,0,Luis
43,HGLG11,2025-07-01 00:00:00,0,0,0,Heitor
44,HGLG11,2025-08-01 00:00:00,0,0,0,Luis
45,HGLG11,2025-08-01 00:00:00,152.89,1,1,Heitor
46,HGLG11,2025-09-01 00:00:00,0,0,0,Luis
47,HGLG11,2025-09-01 00:00:00,0,0,1,Heitor

In [265]:
dicionario_preco_medio = {
    "Luis": {},
    "Heitor": {}
}

lista_preco_medio = []
lista_valor_investido = []
lista_valor_investido_total = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    dono = df_aquisicao_geral.loc[i, "Dono"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    num_cotas = df_aquisicao_geral.loc[i, "Número de Cotas"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]

    if cotas_acumuladas == 0:
        lista_preco_medio.append(0)
        lista_valor_investido.append(0)
        lista_valor_investido_total.append(0)
    elif valor == 0:
        lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)
    else:
        if ativo in dicionario_preco_medio[dono]:
            dicionario_preco_medio[dono][ativo][0] += valor * num_cotas
            dicionario_preco_medio[dono][ativo][1] += num_cotas
            lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        else:
            dicionario_preco_medio[dono][ativo] = [valor * num_cotas, num_cotas]
            lista_preco_medio.append((valor * num_cotas) / num_cotas)
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)

df_aquisicao_geral["Preço Médio"] = lista_preco_medio
df_aquisicao_geral["Valor Investido"] = lista_valor_investido
df_aquisicao_geral["Valor Investido Total"] = lista_valor_investido_total
df_aquisicao_geral["Ano Mês"] = df_aquisicao_geral["Data"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis,32.000000,32.00,32.00,2024_04
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04
2,PETR4,2024-08-01 00:00:00,31.0,2,3,Luis,31.333333,62.00,94.00,2024_08
3,PETR4,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08
4,PETR4,2024-11-01 00:00:00,29.31,3,6,Luis,30.321667,87.93,181.93,2024_11
5,PETR4,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11
6,PETR4,2025-07-01 00:00:00,0,0,6,Luis,30.321667,0.00,181.93,2025_07
7,PETR4,2025-07-01 00:00:00,32.222,5,5,Heitor,32.222000,161.11,161.11,2025_07
8,PETR4,2025-08-01 00:00:00,0,0,6,Luis,30.321667,0.00,181.93,2025_08
9,PETR4,2025-08-01 00:00:00,0,0,5,Heitor,32.222000,0.00,161.11,2025_08
10,PETR4,2025-09-01 00:00:00,31.09,1,7,Luis,30.431429,31.09,213.02,2025_09
11,PETR4,2025-09-01 00:00:00,31.613333,3,8,Heitor,31.993750,94.84,255.95,2025_09
12,VALE3,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04
13,VALE3,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04
14,VALE3,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08
15,VALE3,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08
16,VALE3,2024-11-01 00:00:00,34.87,2,2,Luis,34.870000,69.74,69.74,2024_11
17,VALE3,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11
18,VALE3,2025-07-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_07
19,VALE3,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07
20,VALE3,2025-08-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_08
21,VALE3,2025-08-01 00:00:00,33.89,2,2,Heitor,33.890000,67.78,67.78,2025_08
22,VALE3,2025-09-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_09
23,VALE3,2025-09-01 00:00:00,0,0,2,Heitor,33.890000,0.00,67.78,2025_09
24,TAEE11,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04
25,TAEE11,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04
26,TAEE11,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08
27,TAEE11,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08
28,TAEE11,2024-11-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_11
29,TAEE11,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11
30,TAEE11,2025-07-01 00:00:00,28.96,1,1,Luis,28.960000,28.96,28.96,2025_07
31,TAEE11,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07
32,TAEE11,2025-08-01 00:00:00,0,0,1,Luis,28.960000,0.00,28.96,2025_08
33,TAEE11,2025-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_08
34,TAEE11,2025-09-01 00:00:00,0,0,1,Luis,28.960000,0.00,28.96,2025_09
35,TAEE11,2025-09-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_09
36,HGLG11,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04
37,HGLG11,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04
38,HGLG11,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08
39,HGLG11,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08
40,HGLG11,2024-11-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_11
41,HGLG11,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11
42,HGLG11,2025-07-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_07
43,HGLG11,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07
44,HGLG11,2025-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_08
45,HGLG11,2025-08-01 00:00:00,152.89,1,1,Heitor,152.890000,152.89,152.89,2025_08
46,HGLG11,2025-09-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_09
47,HGLG11,2025-09-01 00:00:00,0,0,1,Heitor,152.890000,0.00,152.89,2025_09

### Lucro e Rendimento

#### Captura Preço Histórico

In [251]:
data_minima = df_aquisicao_geral["Data"].min().strftime("%Y-%m-%d")
data_maxima = df_aquisicao_geral["Data"].max().strftime("%Y-%m-%d")
ano = int(data_maxima[:4])
mes = int(data_maxima[5:7])
if mes < 12:
    mes += 1
else:
    ano += 1
    mes = 1
data_maxima = f"{ano}-{mes}-01"
ativos = pd.unique(df_aquisicao_geral["Ativo"]).tolist()

lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))

df_precos_historicos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])

df_precos_historicos.reset_index(inplace=True)
df_precos_historicos["symbol"] = df_precos_historicos["symbol"].str.replace(".SA", "")
df_precos_historicos["Ano Mês"] = df_precos_historicos["date"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_precos_historicos

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
0,PETR4,2024-04-01,37.500000,37.709999,37.209999,37.650002,23697800,28.460197,0.0,2024_04
1,PETR4,2024-04-02,37.820000,38.650002,37.770000,38.619999,45930700,29.193436,0.0,2024_04
2,PETR4,2024-04-03,38.700001,39.009998,38.220001,38.419998,31437200,29.042253,0.0,2024_04
3,PETR4,2024-04-04,38.470001,39.480000,37.430000,37.980000,165566800,28.709646,0.0,2024_04
4,PETR4,2024-04-05,37.900002,38.570000,37.169998,38.099998,65469200,28.800358,0.0,2024_04
...,...,...,...,...,...,...,...,...,...,...
1507,HGLG11,2025-09-24,159.440002,159.630005,159.009995,159.600006,37907,158.516373,0.0,2025_09
1508,HGLG11,2025-09-25,159.619995,160.600006,159.490005,160.559998,46022,159.469849,0.0,2025_09
1509,HGLG11,2025-09-26,160.649994,160.990005,160.080002,160.160004,42971,159.072571,0.0,2025_09
1510,HGLG11,2025-09-29,161.000000,161.789993,159.500000,161.020004,62449,159.926727,0.0,2025_09
1511,HGLG11,2025-09-30,161.020004,163.300003,161.020004,162.009995,59600,160.910004,0.0,2025_09

In [252]:
df_precos_historicos.loc[df_precos_historicos["Ano Mês"] == "2025_09"]#.iloc[-1, :]

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
356,PETR4,2025-09-01,31.200001,31.370001,31.049999,31.170000,9889700,31.170000,0.0,2025_09
357,PETR4,2025-09-02,31.000000,31.440001,31.000000,31.330000,19812000,31.330000,0.0,2025_09
358,PETR4,2025-09-03,31.120001,31.350000,30.920000,31.059999,29788800,31.059999,0.0,2025_09
359,PETR4,2025-09-04,31.000000,31.320000,30.930000,31.059999,24816500,31.059999,0.0,2025_09
360,PETR4,2025-09-05,31.080000,31.090000,30.190001,30.590000,46121900,30.590000,0.0,2025_09
...,...,...,...,...,...,...,...,...,...,...
1507,HGLG11,2025-09-24,159.440002,159.630005,159.009995,159.600006,37907,158.516373,0.0,2025_09
1508,HGLG11,2025-09-25,159.619995,160.600006,159.490005,160.559998,46022,159.469849,0.0,2025_09
1509,HGLG11,2025-09-26,160.649994,160.990005,160.080002,160.160004,42971,159.072571,0.0,2025_09
1510,HGLG11,2025-09-29,161.000000,161.789993,159.500000,161.020004,62449,159.926727,0.0,2025_09
1511,HGLG11,2025-09-30,161.020004,163.300003,161.020004,162.009995,59600,160.910004,0.0,2025_09

In [253]:
df_precos_historicos.loc[(df_precos_historicos["symbol"] == "PETR4") & (df_precos_historicos["Ano Mês"] == "2024_04")].iloc[-1, :]["close"]

42.02000045776367

#### Calcula Lucro

In [266]:
lista_preco_fechamento = []
lista_preco_fechamento_total = []
lista_lucro = []
# lista_rendimento = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]
    valor_investido_total = df_aquisicao_geral.loc[i, "Valor Investido Total"]
    ano_mes = df_aquisicao_geral.loc[i, "Ano Mês"]

    preco_fechamento = df_precos_historicos.loc[(df_precos_historicos["symbol"] == ativo) & (df_precos_historicos["Ano Mês"] == ano_mes)].iloc[-1, :]["close"]

    lista_preco_fechamento.append(preco_fechamento)
    lista_preco_fechamento_total.append(preco_fechamento * cotas_acumuladas)
    if cotas_acumuladas > 0:
        lucro = (preco_fechamento * cotas_acumuladas) - valor_investido_total
        lista_lucro.append(lucro)
        # lista_rendimento.append((lucro / valor_investido_total) * 100)
    else:
        lista_lucro.append(0)
        # lista_rendimento.append(0)

df_aquisicao_geral["Preço de Fechamento"] = lista_preco_fechamento
df_aquisicao_geral["Preço de Fechamento Total"] = lista_preco_fechamento_total
df_aquisicao_geral["Lucro"] = lista_lucro
# df_aquisicao_geral["Rendimento"] = lista_rendimento
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis,32.000000,32.00,32.00,2024_04,42.020000,42.020000,10.020000
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04,42.020000,0.000000,0.000000
2,PETR4,2024-08-01 00:00:00,31.0,2,3,Luis,31.333333,62.00,94.00,2024_08,39.369999,118.109997,24.109997
3,PETR4,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08,39.369999,0.000000,0.000000
4,PETR4,2024-11-01 00:00:00,29.31,3,6,Luis,30.321667,87.93,181.93,2024_11,38.900002,233.400009,51.470009
5,PETR4,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11,38.900002,0.000000,0.000000
6,PETR4,2025-07-01 00:00:00,0,0,6,Luis,30.321667,0.00,181.93,2025_07,32.639999,195.839996,13.909996
7,PETR4,2025-07-01 00:00:00,32.222,5,5,Heitor,32.222000,161.11,161.11,2025_07,32.639999,163.199997,2.089997
8,PETR4,2025-08-01 00:00:00,0,0,6,Luis,30.321667,0.00,181.93,2025_08,31.100000,186.600002,4.670002
9,PETR4,2025-08-01 00:00:00,0,0,5,Heitor,32.222000,0.00,161.11,2025_08,31.100000,155.500002,-5.609998
10,PETR4,2025-09-01 00:00:00,31.09,1,7,Luis,30.431429,31.09,213.02,2025_09,31.459999,220.219994,7.199994
11,PETR4,2025-09-01 00:00:00,31.613333,3,8,Heitor,31.993750,94.84,255.95,2025_09,31.459999,251.679993,-4.270007
12,VALE3,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04,63.290001,0.000000,0.000000
13,VALE3,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04,63.290001,0.000000,0.000000
14,VALE3,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08,59.580002,0.000000,0.000000
15,VALE3,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08,59.580002,0.000000,0.000000
16,VALE3,2024-11-01 00:00:00,34.87,2,2,Luis,34.870000,69.74,69.74,2024_11,58.779999,117.559998,47.819998
17,VALE3,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11,58.779999,0.000000,0.000000
18,VALE3,2025-07-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_07,53.459999,106.919998,37.179998
19,VALE3,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07,53.459999,0.000000,0.000000
20,VALE3,2025-08-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_08,55.560001,111.120003,41.380003
21,VALE3,2025-08-01 00:00:00,33.89,2,2,Heitor,33.890000,67.78,67.78,2025_08,55.560001,111.120003,43.340003
22,VALE3,2025-09-01 00:00:00,0,0,2,Luis,34.870000,0.00,69.74,2025_09,57.580002,115.160004,45.420004
23,VALE3,2025-09-01 00:00:00,0,0,2,Heitor,33.890000,0.00,67.78,2025_09,57.580002,115.160004,47.380004
24,TAEE11,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04,35.220001,0.000000,0.000000
25,TAEE11,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04,35.220001,0.000000,0.000000
26,TAEE11,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08,35.450001,0.000000,0.000000
27,TAEE11,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08,35.450001,0.000000,0.000000
28,TAEE11,2024-11-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_11,34.090000,0.000000,0.000000
29,TAEE11,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11,34.090000,0.000000,0.000000
30,TAEE11,2025-07-01 00:00:00,28.96,1,1,Luis,28.960000,28.96,28.96,2025_07,33.360001,33.360001,4.400001
31,TAEE11,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07,33.360001,0.000000,0.000000
32,TAEE11,2025-08-01 00:00:00,0,0,1,Luis,28.960000,0.00,28.96,2025_08,34.869999,34.869999,5.909999
33,TAEE11,2025-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_08,34.869999,0.000000,0.000000
34,TAEE11,2025-09-01 00:00:00,0,0,1,Luis,28.960000,0.00,28.96,2025_09,36.660000,36.660000,7.700000
35,TAEE11,2025-09-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_09,36.660000,0.000000,0.000000
36,HGLG11,2024-04-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_04,166.630005,0.000000,0.000000
37,HGLG11,2024-04-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_04,166.630005,0.000000,0.000000
38,HGLG11,2024-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_08,161.199997,0.000000,0.000000
39,HGLG11,2024-08-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_08,161.199997,0.000000,0.000000
40,HGLG11,2024-11-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2024_11,152.250000,0.000000,0.000000
41,HGLG11,2024-11-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2024_11,152.250000,0.000000,0.000000
42,HGLG11,2025-07-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_07,154.240005,0.000000,0.000000
43,HGLG11,2025-07-01 00:00:00,0,0,0,Heitor,0.000000,0.00,0.00,2025_07,154.240005,0.000000,0.000000
44,HGLG11,2025-08-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_08,154.990005,0.000000,0.000000
45,HGLG11,2025-08-01 00:00:00,152.89,1,1,Heitor,152.890000,152.89,152.89,2025_08,154.990005,154.990005,2.100005
46,HGLG11,2025-09-01 00:00:00,0,0,0,Luis,0.000000,0.00,0.00,2025_09,162.009995,0.000000,0.000000
47,HGLG11,2025-09-01 00:00:00,0,0,1,Heitor,152.890000,0.00,152.89,2025_09,162.009995,162.009995,9.119995

In [267]:
df_aquisicao_geral["Data"] = pd.to_datetime(df_aquisicao_geral["Data"], format="%d-%m-%Y")
df_aquisicao_geral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ativo                      48 non-null     object
 1   Data                       48 non-null     datetime64[ns]
 2   Valor                      48 non-null     object
 3   Número de Cotas            48 non-null     object
 4   Cotas Acumuladas           48 non-null     object
 5   Dono                       48 non-null     object
 6   Preço Médio                48 non-null     float64
 7   Valor Investido            48 non-null     float64
 8   Valor Investido Total      48 non-null     float64
 9   Ano Mês                    48 non-null     object
 10  Preço de Fechamento        48 non-null     float64
 11  Preço de Fechamento Total  48 non-null     float64
 12  Lucro                      48 non-null     float64
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 5.0+ KB

In [268]:
df_aquisicao_geral.to_csv("Aquisições Realizadas.csv", index=False)

## Dividendos

In [296]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(lista_ativos_selecionados)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos.sort_values(by="Data", inplace=True)
df_dividendos

       Ativo       Data  Valor   DATA COM Tipo Receita    DY
12    KNCR11 2021-01-14   0.43 2020-12-30   Rendimento  0,49
55    XPCI11 2021-01-15   0.75 2020-12-30   Rendimento  0,81
29    HGLG11 2021-01-15   2.63 2020-12-30   Rendimento  1,45
74    XPML11 2021-01-22   0.67 2021-01-15   Rendimento  0,59
89    KNCR11 2021-02-11   0.28 2021-01-29   Rendimento  0,32
...      ...        ...    ...        ...          ...   ...
1443  TAEE11 2025-11-27   0.32 2025-04-29    Dividendo  0.89
1444  TAEE11 2025-11-27   0.23 2025-08-18    Dividendo  0.68
1445  TAEE11 2025-11-27   0.63 2025-08-18          JCP  1.87
1454   PETR4 2025-12-22   0.20 2025-08-21    Dividendo  0.66
1455   PETR4 2025-12-22   0.13 2025-08-21          JCP  0.45

[394 rows x 6 columns]

In [297]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 394 entries, 12 to 1455
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         394 non-null    object
 1   Data          394 non-null    datetime64[ns]
 2   Valor         394 non-null    float64
 3   DATA COM      394 non-null    datetime64[ns]
 4   Tipo Receita  394 non-null    object
 5   DY            394 non-null    object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 21.5+ KB

### Relaciona Dividendos com Aquisições para multiplicar o valor de dividendo pela quantidade total de cotas válidas

In [298]:
# Junta valores pelo dia

df_dividendos = df_dividendos.groupby(["Ativo", "Data", "DATA COM", "Tipo Receita"]).agg("sum")
df_dividendos = df_dividendos.reset_index()
df_dividendos

      Ativo       Data   DATA COM     Tipo Receita  Valor    DY
0     BBSE3 2021-02-25 2021-02-11        Dividendo   0.47  1.64
1     BBSE3 2021-02-25 2021-02-11  Rend. Tributado   0.00   0.0
2     BBSE3 2021-08-23 2021-08-11        Dividendo   0.52   2.4
3     BBSE3 2022-02-23 2022-02-10        Dividendo   0.91  3.76
4     BBSE3 2022-02-23 2022-02-10  Rend. Tributado   0.01  0.05
..      ...        ...        ...              ...    ...   ...
383  XPML11 2025-04-25 2025-04-16       Rendimento   0.92  0,88
384  XPML11 2025-05-23 2025-05-19       Rendimento   0.92  0,87
385  XPML11 2025-06-25 2025-06-17       Rendimento   0.92  0,89
386  XPML11 2025-07-25 2025-07-18       Rendimento   0.92  0,89
387  XPML11 2025-08-25 2025-08-18       Rendimento   0.92  0,92

[388 rows x 6 columns]

In [299]:
# Filtra apenas os dividendos válidos para as cotas adquiridas
# Separa cada dividendo por dono

df_dividendos_adquiridos = pd.merge(df_dividendos, df_aquisicao, on="Ativo", suffixes=[" Dividendos", " Aquisição"])
df_dividendos_adquiridos = df_dividendos_adquiridos.loc[df_dividendos_adquiridos["DATA COM"] >= df_dividendos_adquiridos["Data Aquisição"]]
df_dividendos_adquiridos

,Ativo,Data Dividendos,DATA COM,Tipo Receita,Valor Dividendos,DY,Data Aquisição,Valor Aquisição,Número de Cotas,Cotas Acumuladas,Dono
56,HGLG11,2025-09-12,2025-08-29,Rendimento,1.10,"0,71",2025-08-01,152.89,1,1,Heitor
267,PETR4,2024-05-20,2024-04-25,Dividendo,1.10,2.6,2024-04-01,32.00,1,1,Luis
273,PETR4,2024-05-20,2024-04-25,Rend. Tributado,0.02,0.05,2024-04-01,32.00,1,1,Luis
279,PETR4,2024-05-20,2024-05-02,Dividendo,0.84,2.02,2024-04-01,32.00,1,1,Luis
285,PETR4,2024-05-20,2024-05-02,Rend. Tributado,0.03,0.08,2024-04-01,32.00,1,1,Luis
...,...,...,...,...,...,...,...,...,...,...,...
468,TAEE11,2025-11-27,2025-08-18,JCP,0.63,1.87,2025-07-01,28.96,1,1,Luis
497,VALE3,2025-03-14,2024-12-11,JCP,0.52,0.89,2024-11-01,34.87,2,2,Luis
499,VALE3,2025-03-14,2025-03-07,Dividendo,2.14,3.79,2024-11-01,34.87,2,2,Luis
501,VALE3,2025-09-03,2025-08-12,JCP,1.89,3.39,2024-11-01,34.87,2,2,Luis
502,VALE3,2025-09-03,2025-08-12,JCP,1.89,3.39,2025-08-01,33.89,2,2,Heitor

In [282]:
df_dividendos_adquiridos = df_dividendos_adquiridos.filter(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Cotas Acumuladas', 'Dono'])
df_dividendos_adquiridos

,Ativo,Data Dividendos,Valor Dividendos,DATA COM,Tipo Receita,DY,Cotas Acumuladas,Dono
56,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",1,Heitor
267,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,1,Luis
273,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,1,Luis
279,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,1,Luis
285,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,1,Luis
...,...,...,...,...,...,...,...,...
468,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,1,Luis
497,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,2,Luis
499,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,2,Luis
501,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,2,Luis
502,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,2,Heitor

In [283]:
# Agrupa os dividendos, capturando o valor máximo de cotas do ativo válidas para multiplicar pelo dividendo

df_dividendos_adquiridos = df_dividendos_adquiridos.groupby(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Dono']).agg("max")
df_dividendos_adquiridos = df_dividendos_adquiridos.reset_index()
df_dividendos_adquiridos.rename(columns={"Data Dividendos": "Data", "Valor Dividendos": "Valor"}, inplace=True)
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Heitor,1
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Luis,1
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Luis,1
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Luis,1
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Luis,1
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Luis,1
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Luis,1
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Luis,1
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Luis,1
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Luis,1
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Luis,1
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Luis,3
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Luis,3
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Luis,3
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Luis,6
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Luis,6
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Luis,6
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Luis,6
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Luis,6
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Luis,6
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Luis,6
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Luis,6
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Luis,6
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Luis,6
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Luis,6
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Luis,6
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Luis,6
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Heitor,5
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Luis,6
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Heitor,5
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Luis,6
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Heitor,5
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Luis,6
33,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Luis,1
34,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Luis,1
35,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Luis,2
36,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Luis,2
37,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Heitor,2
38,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Luis,2

In [284]:
# Calcula dividendo total, valor x número de cotas válidas e acumula os dividendos

lista_dividendos_totais = []
# lista_dividendos_acumulados = []

dividendo_acumulado = 0
for i in df_dividendos_adquiridos.index:
    valor = df_dividendos_adquiridos.loc[i, "Valor"]
    cotas_acumul = df_dividendos_adquiridos.loc[i, "Cotas Acumuladas"]
    dividendo_acumulado += valor * cotas_acumul

    lista_dividendos_totais.append(valor * cotas_acumul)
    # lista_dividendos_acumulados.append(dividendo_acumulado)

df_dividendos_adquiridos["Dividendos Totais"] = lista_dividendos_totais
# df_dividendos_adquiridos["Dividendos Acumulados"] = lista_dividendos_acumulados
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Heitor,1,1.10
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Luis,1,0.02
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Luis,1,0.03
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Luis,1,0.84
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Luis,1,1.10
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Luis,1,0.02
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Luis,1,0.04
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Luis,1,0.84
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Luis,1,0.52
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Luis,1,0.07
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Luis,1,0.44
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Luis,3,0.33
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Luis,3,1.23
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Luis,3,1.56
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Luis,6,9.30
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Luis,6,0.06
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Luis,6,3.96
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Luis,6,0.06
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Luis,6,0.06
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Luis,6,3.90
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Luis,6,0.06
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Luis,6,2.10
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Luis,6,0.12
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Luis,6,2.10
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Luis,6,2.70
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Luis,6,0.84
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Luis,6,1.80
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Heitor,5,1.65
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Luis,6,1.98
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Heitor,5,0.65
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Luis,6,0.78
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Heitor,5,1.00
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Luis,6,1.20
33,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Luis,1,0.23
34,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Luis,1,0.63
35,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Luis,2,1.04
36,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Luis,2,4.28
37,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Heitor,2,3.78
38,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Luis,2,3.78

In [285]:
df_dividendos_adquiridos.to_csv("Dividendos Recebidos.csv", index=False)