# Bibliotecas

In [3]:
import pandas as pd
import yahooquery as yq
from itertools import product
from datetime import datetime
from time import sleep

# Ativos da Carteira

In [5]:
carteira_1 = [
    # Ações
    ("BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3"),

    # FIIs
    ("HGLG11",
    "HTMX11",
    "KNCR11",
    "XPCI11",
    "XPML11")

]

carteira_2 = [
    # Ações
    "EMBR3",
	"GOAU3",
	"RAIL3",
	"SUZB3",
    "WEGE3"
]

ativos = list(carteira_1[0]) + list(carteira_1[1]) + carteira_2
lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))
    sleep(17)

idx = 0
df_ativos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_ativos.loc[idx, 'Ativo'] = nome
    df_ativos.loc[idx, 'Setor'] = ticker.asset_profile[nome+'.SA']['industry']
    df_ativos.loc[idx, 'Indústria'] = ticker.asset_profile[nome+'.SA']['sector']
    df_ativos.loc[idx, 'Data Recomendação'] = datetime.now().strftime('%d-%m-%Y')
    df_ativos.loc[idx, 'Recomendação'] = ticker.financial_data[nome+'.SA']['recommendationKey']

    if nome in carteira_1[0]:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 1
    elif nome in carteira_1[1]:
        df_ativos.loc[idx, 'Tipo'] = "FII"
        df_ativos.loc[idx, 'Carteira'] = 1
    else:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 2
    idx += 1

df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira
0,BBSE3,Insurance - Diversified,Financial Services,10-11-2025,buy,Ação,1.0
1,PETR4,Oil & Gas Integrated,Energy,10-11-2025,buy,Ação,1.0
2,TAEE11,Utilities - Regulated Electric,Utilities,10-11-2025,underperform,Ação,1.0
3,VALE3,Other Industrial Metals & Mining,Basic Materials,10-11-2025,buy,Ação,1.0
4,HGLG11,REIT - Diversified,Real Estate,10-11-2025,none,FII,1.0
5,HTMX11,REIT - Hotel & Motel,Real Estate,10-11-2025,none,FII,1.0
6,KNCR11,REIT - Mortgage,Real Estate,10-11-2025,none,FII,1.0
7,XPCI11,REIT - Mortgage,Real Estate,10-11-2025,none,FII,1.0
8,XPML11,REIT - Retail,Real Estate,10-11-2025,none,FII,1.0
9,EMBR3,Aerospace & Defense,Industrials,10-11-2025,buy,Ação,2.0
10,GOAU3,Steel,Basic Materials,10-11-2025,none,Ação,2.0
11,RAIL3,Railroads,Industrials,10-11-2025,buy,Ação,2.0
12,SUZB3,Paper & Paper Products,Basic Materials,10-11-2025,strong_buy,Ação,2.0
13,WEGE3,Electrical Equipment & Parts,Industrials,10-11-2025,hold,Ação,2.0

In [6]:
acoes1 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 1)]['Ativo'].values
acoes1.sort()
print("Ações Carteira 1: ", acoes1)

fundos = df_ativos.loc[df_ativos['Tipo'] == "FII"]['Ativo'].values
fundos.sort()
print("Fundos Carteira 1: ", fundos)

acoes2 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 2)]['Ativo'].values
acoes2.sort()
print("Ações Carteira 2: ", acoes2)

assert tuple(acoes1) == carteira_1[0]
assert tuple(fundos) == carteira_1[1]
assert list(acoes2) == carteira_2

Ações Carteira 1:  ['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
Fundos Carteira 1:  ['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']
Ações Carteira 2:  ['EMBR3' 'GOAU3' 'RAIL3' 'SUZB3' 'WEGE3']

In [7]:
df_ativos["Data Recomendação"] = pd.to_datetime(df_ativos["Data Recomendação"], format="%d-%m-%Y")
df_ativos["Carteira"] = df_ativos["Carteira"].astype(int)

for i in df_ativos.index:
    recomendacao = df_ativos.loc[i, "Recomendação"]
    if recomendacao == "none":
        df_ativos.loc[i, "Recomendação"] = None
        df_ativos.loc[i, "Data Recomendação"] = None

df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira
0,BBSE3,Insurance - Diversified,Financial Services,2025-11-10,buy,Ação,1
1,PETR4,Oil & Gas Integrated,Energy,2025-11-10,buy,Ação,1
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-11-10,underperform,Ação,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-11-10,buy,Ação,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1
9,EMBR3,Aerospace & Defense,Industrials,2025-11-10,buy,Ação,2
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2
11,RAIL3,Railroads,Industrials,2025-11-10,buy,Ação,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-11-10,strong_buy,Ação,2
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-11-10,hold,Ação,2

In [8]:
df_ativos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Ativo              14 non-null     object
 1   Setor              14 non-null     object
 2   Indústria          14 non-null     object
 3   Data Recomendação  8 non-null      datetime64[ns]
 4   Recomendação       8 non-null      object
 5   Tipo               14 non-null     object
 6   Carteira           14 non-null     int32
dtypes: datetime64[ns](1), int32(1), object(5)
memory usage: 1.4+ KB

In [9]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1,

    "EMBR3": 1,
	"GOAU3": 3,
	"RAIL3": 2,
	"SUZB3": 1,
    "WEGE3": 3
}

balanco_ativos = []
for i in df_ativos.index:
    balanco_ativos.append(
        balanco[df_ativos.loc[[i], "Ativo"].values[0]]
    )

df_ativos["Balanço de Cotas"] = balanco_ativos
df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,2025-11-10,buy,Ação,1,1
1,PETR4,Oil & Gas Integrated,Energy,2025-11-10,buy,Ação,1,10
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-11-10,underperform,Ação,1,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-11-10,buy,Ação,1,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1,1
9,EMBR3,Aerospace & Defense,Industrials,2025-11-10,buy,Ação,2,1
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2,3
11,RAIL3,Railroads,Industrials,2025-11-10,buy,Ação,2,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-11-10,strong_buy,Ação,2,1
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-11-10,hold,Ação,2,3

In [10]:
df_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Aquisição

In [12]:
# df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao = pd.read_csv("Aquisições.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono
0    BBSE3 2025-10-01   33.48                1    Luis
17  XPCI11 2025-10-01   84.00                1  Heitor
16  XPML11 2025-10-01  105.21                1  Heitor
15  KNCR11 2025-10-01  103.66                1  Heitor
14  HTMX11 2025-10-01  139.55                1  Heitor
12   VALE3 2025-10-01   58.16                1  Heitor
11  TAEE11 2025-10-01   36.75                1  Heitor
10   PETR4 2025-10-01   31.42               10  Heitor
9    BBSE3 2025-10-01   33.48                1  Heitor
13  HGLG11 2025-10-01  160.30                1  Heitor
7   XPML11 2025-10-01  105.21                1    Luis
6   KNCR11 2025-10-01  103.57                1    Luis
5   HTMX11 2025-10-01  139.55                1    Luis
4   HGLG11 2025-10-01  160.32                1    Luis
3    VALE3 2025-10-01   58.16                1    Luis
2   TAEE11 2025-10-01   36.75                1    Luis
1    PETR4 2025-10-01   31.41               10    Luis
8   XPCI11 2025-10-01   84.03                1    Luis
22   WEGE3 2025-10-06   36.05                3    Luis
21   SUZB3 2025-10-06   49.46                1    Luis
18   EMBR3 2025-10-06   78.97                1    Luis
19   GOAU3 2025-10-06   10.02                3    Luis
20   RAIL3 2025-10-06   15.83                2    Luis
26   SUZB3 2025-10-09   48.24                1  Heitor
23   EMBR3 2025-10-09   78.17                1  Heitor
24   GOAU3 2025-10-09   10.18                3  Heitor
25   RAIL3 2025-10-09   15.90                2  Heitor
27   WEGE3 2025-10-09   35.94                3  Heitor

In [13]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 27
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            28 non-null     object
 1   Data             28 non-null     datetime64[ns]
 2   Valor            28 non-null     float64
 3   Número de Cotas  28 non-null     int64
 4   Dono             28 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 1.3+ KB

### Acumula cotas e agrupa aquisições no mesmo dia

In [14]:
# Acumula as cotas por ativo e dono

dic_cotas_acum = {
    "Heitor": {},
    "Luis": {}
}

lista_cotas_acum = []

for i in df_aquisicao.index:
    ativo = df_aquisicao.loc[i, "Ativo"]
    cotas = df_aquisicao.loc[i, "Número de Cotas"]
    dono = df_aquisicao.loc[i, "Dono"]
    if ativo not in dic_cotas_acum[dono]:
        dic_cotas_acum[dono][ativo] = cotas
    else:
        dic_cotas_acum[dono][ativo] += cotas
    lista_cotas_acum.append(dic_cotas_acum[dono][ativo])

df_aquisicao["Cotas Acumuladas"] = lista_cotas_acum
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Cotas Acumuladas", "Dono"])
df_aquisicao

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    BBSE3 2025-10-01   33.48                1                 1    Luis
17  XPCI11 2025-10-01   84.00                1                 1  Heitor
16  XPML11 2025-10-01  105.21                1                 1  Heitor
15  KNCR11 2025-10-01  103.66                1                 1  Heitor
14  HTMX11 2025-10-01  139.55                1                 1  Heitor
12   VALE3 2025-10-01   58.16                1                 1  Heitor
11  TAEE11 2025-10-01   36.75                1                 1  Heitor
10   PETR4 2025-10-01   31.42               10                10  Heitor
9    BBSE3 2025-10-01   33.48                1                 1  Heitor
13  HGLG11 2025-10-01  160.30                1                 1  Heitor
7   XPML11 2025-10-01  105.21                1                 1    Luis
6   KNCR11 2025-10-01  103.57                1                 1    Luis
5   HTMX11 2025-10-01  139.55                1                 1    Luis
4   HGLG11 2025-10-01  160.32                1                 1    Luis
3    VALE3 2025-10-01   58.16                1                 1    Luis
2   TAEE11 2025-10-01   36.75                1                 1    Luis
1    PETR4 2025-10-01   31.41               10                10    Luis
8   XPCI11 2025-10-01   84.03                1                 1    Luis
22   WEGE3 2025-10-06   36.05                3                 3    Luis
21   SUZB3 2025-10-06   49.46                1                 1    Luis
18   EMBR3 2025-10-06   78.97                1                 1    Luis
19   GOAU3 2025-10-06   10.02                3                 3    Luis
20   RAIL3 2025-10-06   15.83                2                 2    Luis
26   SUZB3 2025-10-09   48.24                1                 1  Heitor
23   EMBR3 2025-10-09   78.17                1                 1  Heitor
24   GOAU3 2025-10-09   10.18                3                 3  Heitor
25   RAIL3 2025-10-09   15.90                2                 2  Heitor
27   WEGE3 2025-10-09   35.94                3                 3  Heitor

In [15]:
df_compras_mesmo_dia = df_aquisicao.loc[df_aquisicao.duplicated(subset=["Ativo", "Data", "Dono"], keep=False)]
df_compras_mesmo_dia

Empty DataFrame
Columns: [Ativo, Data, Valor, Número de Cotas, Cotas Acumuladas, Dono]
Index: []

In [16]:
# Unifica as aquisições do mesmo dono no mesmo dia

indices_mesmo_dia = list(df_compras_mesmo_dia.index)

dicionario_novo = {"Ativo": [], "Data": [], "Valor": [], "Número de Cotas": [], "Cotas Acumuladas": [], "Dono": []}

ativo_anterior = None
data_anterior = None
dono_anterior = None
valor_total = 0
cotas_totais = 0
maior_cota_acumulada = -1
primeiro = True

for i in df_compras_mesmo_dia.index:
    ativo = df_compras_mesmo_dia.loc[i, "Ativo"]
    data = df_compras_mesmo_dia.loc[i, "Data"]
    valor = df_compras_mesmo_dia.loc[i, "Valor"]
    num_cotas = df_compras_mesmo_dia.loc[i, "Número de Cotas"]
    num_cotas_acumul = df_compras_mesmo_dia.loc[i, "Cotas Acumuladas"]
    dono = df_compras_mesmo_dia.loc[i, "Dono"]

    if (not primeiro) and ((ativo != ativo_anterior) or (data != data_anterior) or (dono != dono_anterior)):
        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)

        valor_total = valor * num_cotas
        cotas_totais = num_cotas
        maior_cota_acumulada = num_cotas_acumul
    elif i == df_compras_mesmo_dia.index[-1]:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

        if num_cotas_acumul > maior_cota_acumulada:
            maior_cota_acumulada = num_cotas_acumul

        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
    else:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

    if num_cotas_acumul > maior_cota_acumulada:
        maior_cota_acumulada = num_cotas_acumul
    
    ativo_anterior = ativo
    data_anterior = data
    dono_anterior = dono
    primeiro = False

pd.DataFrame(dicionario_novo)

Empty DataFrame
Columns: [Ativo, Data, Valor, Número de Cotas, Cotas Acumuladas, Dono]
Index: []

In [17]:
# Remove as aquisições do mesmo dia e adiciona a média ponderada da compra

df_aquisicao.drop(indices_mesmo_dia, inplace=True)
df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao.index = range(len(df_aquisicao))
df_aquisicao

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_17060\2954683775.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    BBSE3 2025-10-01   33.48              1.0               1.0    Luis
1   XPCI11 2025-10-01   84.03              1.0               1.0    Luis
2    PETR4 2025-10-01   31.41             10.0              10.0    Luis
3   TAEE11 2025-10-01   36.75              1.0               1.0    Luis
4    VALE3 2025-10-01   58.16              1.0               1.0    Luis
5   HTMX11 2025-10-01  139.55              1.0               1.0    Luis
6   KNCR11 2025-10-01  103.57              1.0               1.0    Luis
7   XPML11 2025-10-01  105.21              1.0               1.0    Luis
8   HGLG11 2025-10-01  160.30              1.0               1.0  Heitor
9   HGLG11 2025-10-01  160.32              1.0               1.0    Luis
10   PETR4 2025-10-01   31.42             10.0              10.0  Heitor
11  TAEE11 2025-10-01   36.75              1.0               1.0  Heitor
12   VALE3 2025-10-01   58.16              1.0               1.0  Heitor
13  HTMX11 2025-10-01  139.55              1.0               1.0  Heitor
14  KNCR11 2025-10-01  103.66              1.0               1.0  Heitor
15  XPML11 2025-10-01  105.21              1.0               1.0  Heitor
16  XPCI11 2025-10-01   84.00              1.0               1.0  Heitor
17   BBSE3 2025-10-01   33.48              1.0               1.0  Heitor
18   RAIL3 2025-10-06   15.83              2.0               2.0    Luis
19   GOAU3 2025-10-06   10.02              3.0               3.0    Luis
20   WEGE3 2025-10-06   36.05              3.0               3.0    Luis
21   SUZB3 2025-10-06   49.46              1.0               1.0    Luis
22   EMBR3 2025-10-06   78.97              1.0               1.0    Luis
23   RAIL3 2025-10-09   15.90              2.0               2.0  Heitor
24   SUZB3 2025-10-09   48.24              1.0               1.0  Heitor
25   EMBR3 2025-10-09   78.17              1.0               1.0  Heitor
26   GOAU3 2025-10-09   10.18              3.0               3.0  Heitor
27   WEGE3 2025-10-09   35.94              3.0               3.0  Heitor

### Replica ativos para todas as datas

In [18]:
ativos = pd.unique(df_aquisicao["Ativo"])
data = pd.unique(df_aquisicao["Data"])
dono = pd.unique(df_aquisicao["Dono"])

permutacao = list(product(ativos, data, dono))
df_permutacao = pd.DataFrame(permutacao, columns=["Ativo", "Data", "Dono"])
df_permutacao

    Ativo       Data    Dono
0   BBSE3 2025-10-01    Luis
1   BBSE3 2025-10-01  Heitor
2   BBSE3 2025-10-06    Luis
3   BBSE3 2025-10-06  Heitor
4   BBSE3 2025-10-09    Luis
..    ...        ...     ...
79  EMBR3 2025-10-01  Heitor
80  EMBR3 2025-10-06    Luis
81  EMBR3 2025-10-06  Heitor
82  EMBR3 2025-10-09    Luis
83  EMBR3 2025-10-09  Heitor

[84 rows x 3 columns]

In [19]:
df_aquisicao_geral = pd.DataFrame()

for i in df_permutacao.index:
    ativo = df_permutacao.loc[i, "Ativo"]
    data = df_permutacao.loc[i, "Data"]
    dono = df_permutacao.loc[i, "Dono"]

    serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] == data) & (df_aquisicao["Dono"] == dono)]
    if len(serie_aquisicao) >= 1:
        df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
    else:
        serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)]
        if len(serie_aquisicao) < 1:
            serie_aquisicao = pd.Series(
                {
                    "Ativo": ativo, 
                    "Data": data,
                    "Valor": 0,
                    "Número de Cotas": 0,
                    "Cotas Acumuladas": 0,
                    "Dono": dono
                }
            ).to_frame().T

            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
        else:
            serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)].iloc[-1, :]
            serie_aquisicao.loc["Data"] = data
            serie_aquisicao.loc["Valor"] = 0
            serie_aquisicao.loc["Número de Cotas"] = 0
            serie_aquisicao = serie_aquisicao.to_frame().T
            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])

df_aquisicao_geral.index = range(len(df_aquisicao_geral))
df_aquisicao_geral

    Ativo                 Data  Valor Número de Cotas Cotas Acumuladas    Dono
0   BBSE3  2025-10-01 00:00:00  33.48             1.0              1.0    Luis
1   BBSE3  2025-10-01 00:00:00  33.48             1.0              1.0  Heitor
2   BBSE3  2025-10-06 00:00:00      0               0              1.0    Luis
3   BBSE3  2025-10-06 00:00:00      0               0              1.0  Heitor
4   BBSE3  2025-10-09 00:00:00      0               0              1.0    Luis
..    ...                  ...    ...             ...              ...     ...
79  EMBR3  2025-10-01 00:00:00      0               0                0  Heitor
80  EMBR3  2025-10-06 00:00:00  78.97             1.0              1.0    Luis
81  EMBR3  2025-10-06 00:00:00      0               0                0  Heitor
82  EMBR3  2025-10-09 00:00:00      0               0              1.0    Luis
83  EMBR3  2025-10-09 00:00:00  78.17             1.0              1.0  Heitor

[84 rows x 6 columns]

In [20]:
dicionario_preco_medio = {
    "Luis": {},
    "Heitor": {}
}

lista_preco_medio = []
lista_valor_investido = []
lista_valor_investido_total = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    dono = df_aquisicao_geral.loc[i, "Dono"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    num_cotas = df_aquisicao_geral.loc[i, "Número de Cotas"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]

    if cotas_acumuladas == 0:
        lista_preco_medio.append(0)
        lista_valor_investido.append(0)
        lista_valor_investido_total.append(0)
    elif valor == 0:
        lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)
    else:
        if ativo in dicionario_preco_medio[dono]:
            dicionario_preco_medio[dono][ativo][0] += valor * num_cotas
            dicionario_preco_medio[dono][ativo][1] += num_cotas
            lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        else:
            dicionario_preco_medio[dono][ativo] = [valor * num_cotas, num_cotas]
            lista_preco_medio.append((valor * num_cotas) / num_cotas)
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)

df_aquisicao_geral["Preço Médio"] = lista_preco_medio
df_aquisicao_geral["Valor Investido"] = lista_valor_investido
df_aquisicao_geral["Valor Investido Total"] = lista_valor_investido_total
df_aquisicao_geral["Ano Mês"] = df_aquisicao_geral["Data"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês
0,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Luis,33.48,33.48,33.48,2025_10
1,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Heitor,33.48,33.48,33.48,2025_10
2,BBSE3,2025-10-06 00:00:00,0,0,1.0,Luis,33.48,0.00,33.48,2025_10
3,BBSE3,2025-10-06 00:00:00,0,0,1.0,Heitor,33.48,0.00,33.48,2025_10
4,BBSE3,2025-10-09 00:00:00,0,0,1.0,Luis,33.48,0.00,33.48,2025_10
...,...,...,...,...,...,...,...,...,...,...
79,EMBR3,2025-10-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_10
80,EMBR3,2025-10-06 00:00:00,78.97,1.0,1.0,Luis,78.97,78.97,78.97,2025_10
81,EMBR3,2025-10-06 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_10
82,EMBR3,2025-10-09 00:00:00,0,0,1.0,Luis,78.97,0.00,78.97,2025_10
83,EMBR3,2025-10-09 00:00:00,78.17,1.0,1.0,Heitor,78.17,78.17,78.17,2025_10

### Lucro e Rendimento

#### Captura Preço Histórico

In [21]:
data_minima = df_aquisicao_geral["Data"].min().strftime("%Y-%m-%d")
data_maxima = df_aquisicao_geral["Data"].max().strftime("%Y-%m-%d")
ano = int(data_maxima[:4])
mes = int(data_maxima[5:7])
if mes < 12:
    mes += 1
else:
    ano += 1
    mes = 1
data_maxima = f"{ano}-{mes}-01"
ativos = pd.unique(df_aquisicao_geral["Ativo"]).tolist()

lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))
    sleep(15)

df_precos_historicos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])

df_precos_historicos.reset_index(inplace=True)
df_precos_historicos["symbol"] = df_precos_historicos["symbol"].str.replace(".SA", "")
df_precos_historicos["Ano Mês"] = df_precos_historicos["date"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_precos_historicos

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
0,BBSE3,2025-10-01,33.330002,33.599998,33.119999,33.410000,3936600,33.410000,NaN,2025_10
1,BBSE3,2025-10-02,33.459999,33.490002,32.750000,33.080002,4818200,33.080002,NaN,2025_10
2,BBSE3,2025-10-03,33.000000,33.209999,32.820000,32.820000,2607700,32.820000,NaN,2025_10
3,BBSE3,2025-10-06,33.000000,33.000000,32.439999,32.799999,3747100,32.799999,NaN,2025_10
4,BBSE3,2025-10-07,32.820000,33.349998,32.740002,33.060001,6761600,33.060001,NaN,2025_10
...,...,...,...,...,...,...,...,...,...,...
317,EMBR3,2025-10-27,86.639999,87.550003,86.459999,86.680000,2770000,86.680000,NaN,2025_10
318,EMBR3,2025-10-28,86.510002,89.860001,86.510002,89.370003,7396400,89.370003,NaN,2025_10
319,EMBR3,2025-10-29,89.519997,89.879997,87.650002,88.010002,3810100,88.010002,NaN,2025_10
320,EMBR3,2025-10-30,87.650002,88.379997,87.260002,87.889999,6212200,87.889999,NaN,2025_10
321,EMBR3,2025-10-31,88.430000,88.500000,86.440002,86.989998,3652100,86.989998,NaN,2025_10

In [22]:
df_precos_historicos.loc[df_precos_historicos["Ano Mês"] == "2025_09"]#.iloc[-1, :]

Empty DataFrame
Columns: [symbol, date, open, high, low, close, volume, adjclose, dividends, Ano Mês]
Index: []

In [23]:
df_precos_historicos.loc[(df_precos_historicos["symbol"] == "PETR4") & (df_precos_historicos["Ano Mês"] == "2024_04")].iloc[-1, :]["close"]

IndexError: single positional indexer is out-of-bounds

#### Calcula Lucro

In [24]:
lista_preco_fechamento = []
lista_preco_fechamento_total = []
lista_lucro = []
# lista_rendimento = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]
    valor_investido_total = df_aquisicao_geral.loc[i, "Valor Investido Total"]
    ano_mes = df_aquisicao_geral.loc[i, "Ano Mês"]

    preco_fechamento = df_precos_historicos.loc[(df_precos_historicos["symbol"] == ativo) & (df_precos_historicos["Ano Mês"] == ano_mes)].iloc[-1, :]["close"]

    lista_preco_fechamento.append(preco_fechamento)
    lista_preco_fechamento_total.append(preco_fechamento * cotas_acumuladas)
    if cotas_acumuladas > 0:
        lucro = (preco_fechamento * cotas_acumuladas) - valor_investido_total
        lista_lucro.append(lucro)
        # lista_rendimento.append((lucro / valor_investido_total) * 100)
    else:
        lista_lucro.append(0)
        # lista_rendimento.append(0)

df_aquisicao_geral["Preço de Fechamento"] = lista_preco_fechamento
df_aquisicao_geral["Preço de Fechamento Total"] = lista_preco_fechamento_total
df_aquisicao_geral["Lucro"] = lista_lucro
# df_aquisicao_geral["Rendimento"] = lista_rendimento
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
0,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Luis,33.48,33.48,33.48,2025_10,32.849998,32.849998,-0.630002
1,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Heitor,33.48,33.48,33.48,2025_10,32.849998,32.849998,-0.630002
2,BBSE3,2025-10-06 00:00:00,0,0,1.0,Luis,33.48,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
3,BBSE3,2025-10-06 00:00:00,0,0,1.0,Heitor,33.48,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
4,BBSE3,2025-10-09 00:00:00,0,0,1.0,Luis,33.48,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,EMBR3,2025-10-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_10,86.989998,0.000000,0.000000
80,EMBR3,2025-10-06 00:00:00,78.97,1.0,1.0,Luis,78.97,78.97,78.97,2025_10,86.989998,86.989998,8.019998
81,EMBR3,2025-10-06 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_10,86.989998,0.000000,0.000000
82,EMBR3,2025-10-09 00:00:00,0,0,1.0,Luis,78.97,0.00,78.97,2025_10,86.989998,86.989998,8.019998
83,EMBR3,2025-10-09 00:00:00,78.17,1.0,1.0,Heitor,78.17,78.17,78.17,2025_10,86.989998,86.989998,8.819998

In [25]:
df_aquisicao_geral["Data"] = pd.to_datetime(df_aquisicao_geral["Data"], format="%d-%m-%Y")
df_aquisicao_geral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ativo                      84 non-null     object
 1   Data                       84 non-null     datetime64[ns]
 2   Valor                      84 non-null     object
 3   Número de Cotas            84 non-null     object
 4   Cotas Acumuladas           84 non-null     object
 5   Dono                       84 non-null     object
 6   Preço Médio                84 non-null     float64
 7   Valor Investido            84 non-null     float64
 8   Valor Investido Total      84 non-null     float64
 9   Ano Mês                    84 non-null     object
 10  Preço de Fechamento        84 non-null     float64
 11  Preço de Fechamento Total  84 non-null     float64
 12  Lucro                      84 non-null     float64
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 8.7+ KB

In [26]:
df_aquisicao_geral.to_csv("Dados Modelados/Aquisições Realizadas.csv", index=False)

## Dividendos

In [27]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(ativos)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos.sort_values(by="Data", inplace=True)
df_dividendos

       Ativo       Data  Valor   DATA COM Tipo Receita    DY
12    KNCR11 2021-01-14   0.43 2020-12-30   Rendimento  0,49
55    XPCI11 2021-01-15   0.75 2020-12-30   Rendimento  0,81
29    HGLG11 2021-01-15   2.63 2020-12-30   Rendimento  1,45
74    XPML11 2021-01-22   0.67 2021-01-15   Rendimento  0,59
89    KNCR11 2021-02-11   0.28 2021-01-29   Rendimento  0,32
...      ...        ...    ...        ...          ...   ...
1443  TAEE11 2025-11-27   0.32 2025-04-29    Dividendo  0.89
1444  TAEE11 2025-11-27   0.23 2025-08-18    Dividendo  0.68
1445  TAEE11 2025-11-27   0.63 2025-08-18          JCP  1.87
1455   PETR4 2025-12-22   0.13 2025-08-21          JCP  0.45
1454   PETR4 2025-12-22   0.20 2025-08-21    Dividendo  0.66

[434 rows x 6 columns]

In [28]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 434 entries, 12 to 1454
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         434 non-null    object
 1   Data          434 non-null    datetime64[ns]
 2   Valor         434 non-null    float64
 3   DATA COM      434 non-null    datetime64[ns]
 4   Tipo Receita  434 non-null    object
 5   DY            434 non-null    object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 23.7+ KB

### Relaciona Dividendos com Aquisições para multiplicar o valor de dividendo pela quantidade total de cotas válidas

In [29]:
# Junta valores pelo dia

df_dividendos = df_dividendos.groupby(["Ativo", "Data", "DATA COM", "Tipo Receita"]).agg("sum")
df_dividendos = df_dividendos.reset_index()
df_dividendos

      Ativo       Data   DATA COM     Tipo Receita  Valor    DY
0     BBSE3 2021-02-25 2021-02-11        Dividendo   0.47  1.64
1     BBSE3 2021-02-25 2021-02-11  Rend. Tributado   0.00   0.0
2     BBSE3 2021-08-23 2021-08-11        Dividendo   0.52   2.4
3     BBSE3 2022-02-23 2022-02-10        Dividendo   0.91  3.76
4     BBSE3 2022-02-23 2022-02-10  Rend. Tributado   0.01  0.05
..      ...        ...        ...              ...    ...   ...
423  XPML11 2025-04-25 2025-04-16       Rendimento   0.92  0,88
424  XPML11 2025-05-23 2025-05-19       Rendimento   0.92  0,87
425  XPML11 2025-06-25 2025-06-17       Rendimento   0.92  0,89
426  XPML11 2025-07-25 2025-07-18       Rendimento   0.92  0,89
427  XPML11 2025-08-25 2025-08-18       Rendimento   0.92  0,92

[428 rows x 6 columns]

In [30]:
# Filtra apenas os dividendos válidos para as cotas adquiridas
# Separa cada dividendo por dono

df_dividendos_adquiridos = pd.merge(df_dividendos, df_aquisicao, on="Ativo", suffixes=[" Dividendos", " Aquisição"])
df_dividendos_adquiridos = df_dividendos_adquiridos.loc[df_dividendos_adquiridos["DATA COM"] >= df_dividendos_adquiridos["Data Aquisição"]]
df_dividendos_adquiridos

Empty DataFrame
Columns: [Ativo, Data Dividendos, DATA COM, Tipo Receita, Valor Dividendos, DY, Data Aquisição, Valor Aquisição, Número de Cotas, Cotas Acumuladas, Dono]
Index: []

In [31]:
df_dividendos_adquiridos = df_dividendos_adquiridos.filter(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Cotas Acumuladas', 'Dono'])
df_dividendos_adquiridos

Empty DataFrame
Columns: [Ativo, Data Dividendos, Valor Dividendos, DATA COM, Tipo Receita, DY, Cotas Acumuladas, Dono]
Index: []

In [32]:
# Agrupa os dividendos, capturando o valor máximo de cotas do ativo válidas para multiplicar pelo dividendo

df_dividendos_adquiridos = df_dividendos_adquiridos.groupby(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Dono']).agg("max")
df_dividendos_adquiridos = df_dividendos_adquiridos.reset_index()
df_dividendos_adquiridos.rename(columns={"Data Dividendos": "Data", "Valor Dividendos": "Valor"}, inplace=True)
df_dividendos_adquiridos

Empty DataFrame
Columns: [Ativo, Data, Valor, DATA COM, Tipo Receita, DY, Dono, Cotas Acumuladas]
Index: []

In [33]:
# Calcula dividendo total, valor x número de cotas válidas e acumula os dividendos

lista_dividendos_totais = []
# lista_dividendos_acumulados = []

dividendo_acumulado = 0
for i in df_dividendos_adquiridos.index:
    valor = df_dividendos_adquiridos.loc[i, "Valor"]
    cotas_acumul = df_dividendos_adquiridos.loc[i, "Cotas Acumuladas"]
    dividendo_acumulado += valor * cotas_acumul

    lista_dividendos_totais.append(valor * cotas_acumul)
    # lista_dividendos_acumulados.append(dividendo_acumulado)

df_dividendos_adquiridos["Dividendos Totais"] = lista_dividendos_totais
# df_dividendos_adquiridos["Dividendos Acumulados"] = lista_dividendos_acumulados
df_dividendos_adquiridos

Empty DataFrame
Columns: [Ativo, Data, Valor, DATA COM, Tipo Receita, DY, Dono, Cotas Acumuladas, Dividendos Totais]
Index: []

In [34]:
df_dividendos_adquiridos.to_csv("Dados Modelados/Dividendos Recebidos.csv", index=False)