# Bibliotecas

In [1]:
import pandas as pd
import yahooquery as yq
from itertools import product
from datetime import datetime
from time import sleep

# Ativos da Carteira

In [ ]:
carteira_1 = [
    # Ações
    ("BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3"),

    # FIIs
    ("HGLG11",
    "HTMX11",
    "KNCR11",
    "XPCI11",
    "XPML11")

]

carteira_2 = [
    # Ações
    "EMBR3",
	"GOAU3",
	"RAIL3",
	"SUZB3",
    "WEGE3"
]

ativos = list(carteira_1[0]) + list(carteira_1[1]) + carteira_2
lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))
    sleep(17)

idx = 0
df_ativos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_ativos.loc[idx, 'Ativo'] = nome
    df_ativos.loc[idx, 'Setor'] = ticker.asset_profile[nome+'.SA']['industry']
    df_ativos.loc[idx, 'Indústria'] = ticker.asset_profile[nome+'.SA']['sector']
    df_ativos.loc[idx, 'Data Recomendação'] = datetime.now().strftime('%d-%m-%Y')
    df_ativos.loc[idx, 'Recomendação'] = ticker.financial_data[nome+'.SA']['recommendationKey']

    if nome in carteira_1[0]:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 1
    elif nome in carteira_1[1]:
        df_ativos.loc[idx, 'Tipo'] = "FII"
        df_ativos.loc[idx, 'Carteira'] = 1
    else:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 2
    idx += 1

df_ativos # 5 min

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira
0,BBSE3,Insurance - Diversified,Financial Services,16-12-2025,hold,Ação,1.0
1,PETR4,Oil & Gas Integrated,Energy,16-12-2025,buy,Ação,1.0
2,TAEE11,Utilities - Regulated Electric,Utilities,16-12-2025,underperform,Ação,1.0
3,VALE3,Other Industrial Metals & Mining,Basic Materials,16-12-2025,buy,Ação,1.0
4,HGLG11,REIT - Diversified,Real Estate,16-12-2025,none,FII,1.0
5,HTMX11,REIT - Hotel & Motel,Real Estate,16-12-2025,none,FII,1.0
6,KNCR11,REIT - Mortgage,Real Estate,16-12-2025,none,FII,1.0
7,XPCI11,REIT - Mortgage,Real Estate,16-12-2025,none,FII,1.0
8,XPML11,REIT - Retail,Real Estate,16-12-2025,none,FII,1.0
9,EMBR3,Aerospace & Defense,Industrials,16-12-2025,buy,Ação,2.0
10,GOAU3,Steel,Basic Materials,16-12-2025,none,Ação,2.0
11,RAIL3,Railroads,Industrials,16-12-2025,buy,Ação,2.0
12,SUZB3,Paper & Paper Products,Basic Materials,16-12-2025,strong_buy,Ação,2.0
13,WEGE3,Electrical Equipment & Parts,Industrials,16-12-2025,hold,Ação,2.0

In [8]:
acoes1 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 1)]['Ativo'].values
acoes1.sort()
print("Ações Carteira 1: ", acoes1)

fundos = df_ativos.loc[df_ativos['Tipo'] == "FII"]['Ativo'].values
fundos.sort()
print("Fundos Carteira 1: ", fundos)

acoes2 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 2)]['Ativo'].values
acoes2.sort()
print("Ações Carteira 2: ", acoes2)

assert tuple(acoes1) == carteira_1[0]
assert tuple(fundos) == carteira_1[1]
assert list(acoes2) == carteira_2

Ações Carteira 1:  ['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
Fundos Carteira 1:  ['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']
Ações Carteira 2:  ['EMBR3' 'GOAU3' 'RAIL3' 'SUZB3' 'WEGE3']

In [9]:
df_ativos["Data Recomendação"] = pd.to_datetime(df_ativos["Data Recomendação"], format="%d-%m-%Y")
df_ativos["Carteira"] = df_ativos["Carteira"].astype(int)

for i in df_ativos.index:
    recomendacao = df_ativos.loc[i, "Recomendação"]
    if recomendacao == "none":
        df_ativos.loc[i, "Recomendação"] = None
        df_ativos.loc[i, "Data Recomendação"] = None

df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,2025-12-16,hold,Ação,1,1
1,PETR4,Oil & Gas Integrated,Energy,2025-12-16,buy,Ação,1,10
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-12-16,underperform,Ação,1,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-12-16,buy,Ação,1,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1,1
9,EMBR3,Aerospace & Defense,Industrials,2025-12-16,buy,Ação,2,1
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2,3
11,RAIL3,Railroads,Industrials,2025-12-16,buy,Ação,2,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-12-16,strong_buy,Ação,2,1
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-12-16,hold,Ação,2,3

In [10]:
df_ativos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Ativo              14 non-null     object
 1   Setor              14 non-null     object
 2   Indústria          14 non-null     object
 3   Data Recomendação  8 non-null      datetime64[ns]
 4   Recomendação       8 non-null      object
 5   Tipo               14 non-null     object
 6   Carteira           14 non-null     int32
 7   Balanço de Cotas   14 non-null     int64
dtypes: datetime64[ns](1), int32(1), int64(1), object(5)
memory usage: 1.5+ KB

In [11]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1,

    "EMBR3": 1,
	"GOAU3": 3,
	"RAIL3": 2,
	"SUZB3": 1,
    "WEGE3": 3
}

balanco_ativos = []
for i in df_ativos.index:
    balanco_ativos.append(
        balanco[df_ativos.loc[[i], "Ativo"].values[0]]
    )

df_ativos["Balanço de Cotas"] = balanco_ativos
df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,2025-12-16,hold,Ação,1,1
1,PETR4,Oil & Gas Integrated,Energy,2025-12-16,buy,Ação,1,10
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-12-16,underperform,Ação,1,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-12-16,buy,Ação,1,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1,1
9,EMBR3,Aerospace & Defense,Industrials,2025-12-16,buy,Ação,2,1
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2,3
11,RAIL3,Railroads,Industrials,2025-12-16,buy,Ação,2,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-12-16,strong_buy,Ação,2,1
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-12-16,hold,Ação,2,3

In [12]:
df_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Aquisição

In [13]:
# df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao = pd.read_csv("Aquisições.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao.sort_values(by=["Data", "Ativo"], inplace=True)
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono
0    BBSE3 2025-10-01   33.48                1    Luis
9    BBSE3 2025-10-01   33.48                1  Heitor
4   HGLG11 2025-10-01  160.32                1    Luis
13  HGLG11 2025-10-01  160.30                1  Heitor
5   HTMX11 2025-10-01  139.55                1    Luis
14  HTMX11 2025-10-01  139.55                1  Heitor
6   KNCR11 2025-10-01  103.57                1    Luis
15  KNCR11 2025-10-01  103.66                1  Heitor
1    PETR4 2025-10-01   31.41               10    Luis
10   PETR4 2025-10-01   31.42               10  Heitor
2   TAEE11 2025-10-01   36.75                1    Luis
11  TAEE11 2025-10-01   36.75                1  Heitor
3    VALE3 2025-10-01   58.16                1    Luis
12   VALE3 2025-10-01   58.16                1  Heitor
8   XPCI11 2025-10-01   84.03                1    Luis
17  XPCI11 2025-10-01   84.00                1  Heitor
7   XPML11 2025-10-01  105.21                1    Luis
16  XPML11 2025-10-01  105.21                1  Heitor
18   EMBR3 2025-10-06   78.97                1    Luis
19   GOAU3 2025-10-06   10.02                3    Luis
20   RAIL3 2025-10-06   15.83                2    Luis
21   SUZB3 2025-10-06   49.46                1    Luis
22   WEGE3 2025-10-06   36.05                3    Luis
23   EMBR3 2025-10-09   78.17                1  Heitor
24   GOAU3 2025-10-09   10.18                3  Heitor
25   RAIL3 2025-10-09   15.90                2  Heitor
26   SUZB3 2025-10-09   48.24                1  Heitor
27   WEGE3 2025-10-09   35.94                3  Heitor
28   WEGE3 2025-10-14   35.94               30  Heitor
29   BBSE3 2025-11-11   33.67                1    Luis
38   EMBR3 2025-11-11   87.66                1    Luis
39   GOAU3 2025-11-11   10.87                3    Luis
33  HGLG11 2025-11-11  158.49                1    Luis
34  HTMX11 2025-11-11  138.43                2    Luis
35  KNCR11 2025-11-11  104.85                1    Luis
30   PETR4 2025-11-11   32.93                5    Luis
40   RAIL3 2025-11-11   16.40                2    Luis
41   SUZB3 2025-11-11   46.70                1    Luis
31  TAEE11 2025-11-11   42.12                1    Luis
32   VALE3 2025-11-11   65.43                1    Luis
42   WEGE3 2025-11-11   46.08                3    Luis
37  XPCI11 2025-11-11   81.80                1    Luis
36  XPML11 2025-11-11  106.75                1    Luis
43   PETR4 2025-11-28   31.68               10    Luis
50   BBSE3 2025-12-08   35.43                1    Luis
46  HGLG11 2025-12-08  159.90                1    Luis
45  HTMX11 2025-12-08  143.52                1    Luis
48  KNCR11 2025-12-08  105.04                1    Luis
44   PETR4 2025-12-08   31.61               15    Luis
51  TAEE11 2025-12-08   41.63                1    Luis
52   VALE3 2025-12-08   70.62                1    Luis
49  XPCI11 2025-12-08   81.23                1    Luis
47  XPML11 2025-12-08  107.29                1    Luis

In [14]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 47
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            53 non-null     object
 1   Data             53 non-null     datetime64[ns]
 2   Valor            53 non-null     float64
 3   Número de Cotas  53 non-null     int64
 4   Dono             53 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 2.5+ KB

### Acumula cotas e agrupa aquisições no mesmo dia

In [15]:
# Acumula as cotas por ativo e dono

dic_cotas_acum = {
    "Heitor": {},
    "Luis": {}
}

lista_cotas_acum = []

for i in df_aquisicao.index:
    ativo = df_aquisicao.loc[i, "Ativo"]
    cotas = df_aquisicao.loc[i, "Número de Cotas"]
    dono = df_aquisicao.loc[i, "Dono"]
    if ativo not in dic_cotas_acum[dono]:
        dic_cotas_acum[dono][ativo] = cotas
    else:
        dic_cotas_acum[dono][ativo] += cotas
    lista_cotas_acum.append(dic_cotas_acum[dono][ativo])

df_aquisicao["Cotas Acumuladas"] = lista_cotas_acum
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Cotas Acumuladas", "Dono"])
df_aquisicao

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    BBSE3 2025-10-01   33.48                1                 1    Luis
9    BBSE3 2025-10-01   33.48                1                 1  Heitor
4   HGLG11 2025-10-01  160.32                1                 1    Luis
13  HGLG11 2025-10-01  160.30                1                 1  Heitor
5   HTMX11 2025-10-01  139.55                1                 1    Luis
14  HTMX11 2025-10-01  139.55                1                 1  Heitor
6   KNCR11 2025-10-01  103.57                1                 1    Luis
15  KNCR11 2025-10-01  103.66                1                 1  Heitor
1    PETR4 2025-10-01   31.41               10                10    Luis
10   PETR4 2025-10-01   31.42               10                10  Heitor
2   TAEE11 2025-10-01   36.75                1                 1    Luis
11  TAEE11 2025-10-01   36.75                1                 1  Heitor
3    VALE3 2025-10-01   58.16                1                 1    Luis
12   VALE3 2025-10-01   58.16                1                 1  Heitor
8   XPCI11 2025-10-01   84.03                1                 1    Luis
17  XPCI11 2025-10-01   84.00                1                 1  Heitor
7   XPML11 2025-10-01  105.21                1                 1    Luis
16  XPML11 2025-10-01  105.21                1                 1  Heitor
18   EMBR3 2025-10-06   78.97                1                 1    Luis
19   GOAU3 2025-10-06   10.02                3                 3    Luis
20   RAIL3 2025-10-06   15.83                2                 2    Luis
21   SUZB3 2025-10-06   49.46                1                 1    Luis
22   WEGE3 2025-10-06   36.05                3                 3    Luis
23   EMBR3 2025-10-09   78.17                1                 1  Heitor
24   GOAU3 2025-10-09   10.18                3                 3  Heitor
25   RAIL3 2025-10-09   15.90                2                 2  Heitor
26   SUZB3 2025-10-09   48.24                1                 1  Heitor
27   WEGE3 2025-10-09   35.94                3                 3  Heitor
28   WEGE3 2025-10-14   35.94               30                33  Heitor
29   BBSE3 2025-11-11   33.67                1                 2    Luis
38   EMBR3 2025-11-11   87.66                1                 2    Luis
39   GOAU3 2025-11-11   10.87                3                 6    Luis
33  HGLG11 2025-11-11  158.49                1                 2    Luis
34  HTMX11 2025-11-11  138.43                2                 3    Luis
35  KNCR11 2025-11-11  104.85                1                 2    Luis
30   PETR4 2025-11-11   32.93                5                15    Luis
40   RAIL3 2025-11-11   16.40                2                 4    Luis
41   SUZB3 2025-11-11   46.70                1                 2    Luis
31  TAEE11 2025-11-11   42.12                1                 2    Luis
32   VALE3 2025-11-11   65.43                1                 2    Luis
42   WEGE3 2025-11-11   46.08                3                 6    Luis
37  XPCI11 2025-11-11   81.80                1                 2    Luis
36  XPML11 2025-11-11  106.75                1                 2    Luis
43   PETR4 2025-11-28   31.68               10                25    Luis
50   BBSE3 2025-12-08   35.43                1                 3    Luis
46  HGLG11 2025-12-08  159.90                1                 3    Luis
45  HTMX11 2025-12-08  143.52                1                 4    Luis
48  KNCR11 2025-12-08  105.04                1                 3    Luis
44   PETR4 2025-12-08   31.61               15                40    Luis
51  TAEE11 2025-12-08   41.63                1                 3    Luis
52   VALE3 2025-12-08   70.62                1                 3    Luis
49  XPCI11 2025-12-08   81.23                1                 3    Luis
47  XPML11 2025-12-08  107.29                1                 3    Luis

In [16]:
df_compras_mesmo_dia = df_aquisicao.loc[df_aquisicao.duplicated(subset=["Ativo", "Data", "Dono"], keep=False)]
df_compras_mesmo_dia

Empty DataFrame
Columns: [Ativo, Data, Valor, Número de Cotas, Cotas Acumuladas, Dono]
Index: []

In [17]:
# Unifica as aquisições do mesmo dono no mesmo dia

indices_mesmo_dia = list(df_compras_mesmo_dia.index)

dicionario_novo = {"Ativo": [], "Data": [], "Valor": [], "Número de Cotas": [], "Cotas Acumuladas": [], "Dono": []}

ativo_anterior = None
data_anterior = None
dono_anterior = None
valor_total = 0
cotas_totais = 0
maior_cota_acumulada = -1
primeiro = True

for i in df_compras_mesmo_dia.index:
    ativo = df_compras_mesmo_dia.loc[i, "Ativo"]
    data = df_compras_mesmo_dia.loc[i, "Data"]
    valor = df_compras_mesmo_dia.loc[i, "Valor"]
    num_cotas = df_compras_mesmo_dia.loc[i, "Número de Cotas"]
    num_cotas_acumul = df_compras_mesmo_dia.loc[i, "Cotas Acumuladas"]
    dono = df_compras_mesmo_dia.loc[i, "Dono"]

    if (not primeiro) and ((ativo != ativo_anterior) or (data != data_anterior) or (dono != dono_anterior)):
        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)

        valor_total = valor * num_cotas
        cotas_totais = num_cotas
        maior_cota_acumulada = num_cotas_acumul
    elif i == df_compras_mesmo_dia.index[-1]:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

        if num_cotas_acumul > maior_cota_acumulada:
            maior_cota_acumulada = num_cotas_acumul

        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
    else:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

    if num_cotas_acumul > maior_cota_acumulada:
        maior_cota_acumulada = num_cotas_acumul
    
    ativo_anterior = ativo
    data_anterior = data
    dono_anterior = dono
    primeiro = False

pd.DataFrame(dicionario_novo)

Empty DataFrame
Columns: [Ativo, Data, Valor, Número de Cotas, Cotas Acumuladas, Dono]
Index: []

In [18]:
# Remove as aquisições do mesmo dia e adiciona a média ponderada da compra

df_aquisicao.drop(indices_mesmo_dia, inplace=True)
df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao.index = range(len(df_aquisicao))
df_aquisicao

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\2954683775.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    BBSE3 2025-10-01   33.48              1.0               1.0    Luis
1   XPML11 2025-10-01  105.21              1.0               1.0  Heitor
2   XPML11 2025-10-01  105.21              1.0               1.0    Luis
3   XPCI11 2025-10-01   84.00              1.0               1.0  Heitor
4   XPCI11 2025-10-01   84.03              1.0               1.0    Luis
5    VALE3 2025-10-01   58.16              1.0               1.0  Heitor
6   TAEE11 2025-10-01   36.75              1.0               1.0  Heitor
7   TAEE11 2025-10-01   36.75              1.0               1.0    Luis
8    PETR4 2025-10-01   31.42             10.0              10.0  Heitor
9    VALE3 2025-10-01   58.16              1.0               1.0    Luis
10  KNCR11 2025-10-01  103.66              1.0               1.0  Heitor
11  KNCR11 2025-10-01  103.57              1.0               1.0    Luis
12  HTMX11 2025-10-01  139.55              1.0               1.0  Heitor
13  HTMX11 2025-10-01  139.55              1.0               1.0    Luis
14  HGLG11 2025-10-01  160.30              1.0               1.0  Heitor
15  HGLG11 2025-10-01  160.32              1.0               1.0    Luis
16   BBSE3 2025-10-01   33.48              1.0               1.0  Heitor
17   PETR4 2025-10-01   31.41             10.0              10.0    Luis
18   EMBR3 2025-10-06   78.97              1.0               1.0    Luis
19   GOAU3 2025-10-06   10.02              3.0               3.0    Luis
20   RAIL3 2025-10-06   15.83              2.0               2.0    Luis
21   SUZB3 2025-10-06   49.46              1.0               1.0    Luis
22   WEGE3 2025-10-06   36.05              3.0               3.0    Luis
23   WEGE3 2025-10-09   35.94              3.0               3.0  Heitor
24   RAIL3 2025-10-09   15.90              2.0               2.0  Heitor
25   SUZB3 2025-10-09   48.24              1.0               1.0  Heitor
26   EMBR3 2025-10-09   78.17              1.0               1.0  Heitor
27   GOAU3 2025-10-09   10.18              3.0               3.0  Heitor
28   WEGE3 2025-10-14   35.94             30.0              33.0  Heitor
29   VALE3 2025-11-11   65.43              1.0               2.0    Luis
30  XPML11 2025-11-11  106.75              1.0               2.0    Luis
31  XPCI11 2025-11-11   81.80              1.0               2.0    Luis
32   WEGE3 2025-11-11   46.08              3.0               6.0    Luis
33  TAEE11 2025-11-11   42.12              1.0               2.0    Luis
34   SUZB3 2025-11-11   46.70              1.0               2.0    Luis
35   RAIL3 2025-11-11   16.40              2.0               4.0    Luis
36  KNCR11 2025-11-11  104.85              1.0               2.0    Luis
37  HTMX11 2025-11-11  138.43              2.0               3.0    Luis
38  HGLG11 2025-11-11  158.49              1.0               2.0    Luis
39   GOAU3 2025-11-11   10.87              3.0               6.0    Luis
40   EMBR3 2025-11-11   87.66              1.0               2.0    Luis
41   BBSE3 2025-11-11   33.67              1.0               2.0    Luis
42   PETR4 2025-11-11   32.93              5.0              15.0    Luis
43   PETR4 2025-11-28   31.68             10.0              25.0    Luis
44  TAEE11 2025-12-08   41.63              1.0               3.0    Luis
45   VALE3 2025-12-08   70.62              1.0               3.0    Luis
46   PETR4 2025-12-08   31.61             15.0              40.0    Luis
47  XPCI11 2025-12-08   81.23              1.0               3.0    Luis
48  HTMX11 2025-12-08  143.52              1.0               4.0    Luis
49  HGLG11 2025-12-08  159.90              1.0               3.0    Luis
50   BBSE3 2025-12-08   35.43              1.0               3.0    Luis
51  KNCR11 2025-12-08  105.04              1.0               3.0    Luis
52  XPML11 2025-12-08  107.29              1.0               3.0    Luis

### Replica ativos para todas as datas

In [19]:
ativos = pd.unique(df_aquisicao["Ativo"])
data = pd.unique(df_aquisicao["Data"])
dono = pd.unique(df_aquisicao["Dono"])

permutacao = list(product(ativos, data, dono))
df_permutacao = pd.DataFrame(permutacao, columns=["Ativo", "Data", "Dono"])
df_permutacao

     Ativo       Data    Dono
0    BBSE3 2025-10-01    Luis
1    BBSE3 2025-10-01  Heitor
2    BBSE3 2025-10-06    Luis
3    BBSE3 2025-10-06  Heitor
4    BBSE3 2025-10-09    Luis
..     ...        ...     ...
191  WEGE3 2025-11-11  Heitor
192  WEGE3 2025-11-28    Luis
193  WEGE3 2025-11-28  Heitor
194  WEGE3 2025-12-08    Luis
195  WEGE3 2025-12-08  Heitor

[196 rows x 3 columns]

In [20]:
df_aquisicao_geral = pd.DataFrame()

for i in df_permutacao.index:
    ativo = df_permutacao.loc[i, "Ativo"]
    data = df_permutacao.loc[i, "Data"]
    dono = df_permutacao.loc[i, "Dono"]

    serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] == data) & (df_aquisicao["Dono"] == dono)]
    if len(serie_aquisicao) >= 1:
        df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
    else:
        serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)]
        if len(serie_aquisicao) < 1:
            serie_aquisicao = pd.Series(
                {
                    "Ativo": ativo, 
                    "Data": data,
                    "Valor": 0,
                    "Número de Cotas": 0,
                    "Cotas Acumuladas": 0,
                    "Dono": dono
                }
            ).to_frame().T

            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
        else:
            serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)].iloc[-1, :]
            serie_aquisicao.loc["Data"] = data
            serie_aquisicao.loc["Valor"] = 0
            serie_aquisicao.loc["Número de Cotas"] = 0
            serie_aquisicao = serie_aquisicao.to_frame().T
            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])

df_aquisicao_geral.index = range(len(df_aquisicao_geral))
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono
0,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Luis
1,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Heitor
2,BBSE3,2025-10-06 00:00:00,0,0,1.0,Luis
3,BBSE3,2025-10-06 00:00:00,0,0,1.0,Heitor
4,BBSE3,2025-10-09 00:00:00,0,0,1.0,Luis
...,...,...,...,...,...,...
191,WEGE3,2025-11-11 00:00:00,0,0,33.0,Heitor
192,WEGE3,2025-11-28 00:00:00,0,0,6.0,Luis
193,WEGE3,2025-11-28 00:00:00,0,0,33.0,Heitor
194,WEGE3,2025-12-08 00:00:00,0,0,6.0,Luis
195,WEGE3,2025-12-08 00:00:00,0,0,33.0,Heitor

In [21]:
dicionario_preco_medio = {
    "Luis": {},
    "Heitor": {}
}

lista_preco_medio = []
lista_valor_investido = []
lista_valor_investido_total = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    dono = df_aquisicao_geral.loc[i, "Dono"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    num_cotas = df_aquisicao_geral.loc[i, "Número de Cotas"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]

    if cotas_acumuladas == 0:
        lista_preco_medio.append(0)
        lista_valor_investido.append(0)
        lista_valor_investido_total.append(0)
    elif valor == 0:
        lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)
    else:
        if ativo in dicionario_preco_medio[dono]:
            dicionario_preco_medio[dono][ativo][0] += valor * num_cotas
            dicionario_preco_medio[dono][ativo][1] += num_cotas
            lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        else:
            dicionario_preco_medio[dono][ativo] = [valor * num_cotas, num_cotas]
            lista_preco_medio.append((valor * num_cotas) / num_cotas)
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)

df_aquisicao_geral["Preço Médio"] = lista_preco_medio
df_aquisicao_geral["Valor Investido"] = lista_valor_investido
df_aquisicao_geral["Valor Investido Total"] = lista_valor_investido_total
df_aquisicao_geral["Ano Mês"] = df_aquisicao_geral["Data"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês
0,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Luis,33.480,33.48,33.48,2025_10
1,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Heitor,33.480,33.48,33.48,2025_10
2,BBSE3,2025-10-06 00:00:00,0,0,1.0,Luis,33.480,0.00,33.48,2025_10
3,BBSE3,2025-10-06 00:00:00,0,0,1.0,Heitor,33.480,0.00,33.48,2025_10
4,BBSE3,2025-10-09 00:00:00,0,0,1.0,Luis,33.480,0.00,33.48,2025_10
...,...,...,...,...,...,...,...,...,...,...
191,WEGE3,2025-11-11 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_11
192,WEGE3,2025-11-28 00:00:00,0,0,6.0,Luis,41.065,0.00,246.39,2025_11
193,WEGE3,2025-11-28 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_11
194,WEGE3,2025-12-08 00:00:00,0,0,6.0,Luis,41.065,0.00,246.39,2025_12
195,WEGE3,2025-12-08 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_12

### Lucro e Rendimento

#### Captura Preço Histórico

In [ ]:
data_minima = df_aquisicao_geral["Data"].min().strftime("%Y-%m-%d")
data_maxima = df_aquisicao_geral["Data"].max().strftime("%Y-%m-%d")
ano = int(data_maxima[:4])
mes = int(data_maxima[5:7])
if mes < 12:
    mes += 1
else:
    ano += 1
    mes = 1
data_maxima = f"{ano}-{mes}-01"
ativos = pd.unique(df_aquisicao_geral["Ativo"]).tolist()

lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))
    sleep(15)

df_precos_historicos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])

df_precos_historicos.reset_index(inplace=True)

# for nome, ticker in lista_tickers:
#     preco_data_recente = ticker.history(period='7d',interval='1d').iloc[[-1], :]
#     preco_data_recente.reset_index(inplace=True)
#     if len(str(preco_data_recente.iloc[0, 1]).split(' ')) > 1:
#         preco_data_recente.iloc[0, 1] = preco_data_recente.iloc[0, 1].date()
#     df_precos_historicos = pd.concat([df_precos_historicos, preco_data_recente])

df_precos_historicos["symbol"] = df_precos_historicos["symbol"].str.replace(".SA", "")
df_precos_historicos["Ano Mês"] = df_precos_historicos["date"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_precos_historicos # 4 min

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\3803563426.py:20: RuntimeWarning: can't compare datetime.datetime to datetime.date, sort order is undefined for incomparable objects.
  df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\3803563426.py:20: RuntimeWarning: can't compare datetime.datetime to datetime.date, sort order is undefined for incomparable objects.
  df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\3803563426.py:20: RuntimeWarning: can't compare datetime.datetime to datetime.date, sort order is undefined for incomparable objects.
  df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\3803563426.py:20: RuntimeWarning: can't compare datetime.datetime to datetime.date, sort order is undefined for incomparable objects.
  df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])
C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_22540\3803563426.py:20: RuntimeWarning: can't compare datetime.datetime to datetime.date, sort order is undefined for incomparable objects.
  df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
0,BBSE3,2025-10-01,33.330002,33.599998,33.119999,33.410000,3936600,33.410000,NaN,2025_10
1,BBSE3,2025-10-02,33.459999,33.490002,32.750000,33.080002,4818200,33.080002,NaN,2025_10
2,BBSE3,2025-10-03,33.000000,33.209999,32.820000,32.820000,2607700,32.820000,NaN,2025_10
3,BBSE3,2025-10-06,33.000000,33.000000,32.439999,32.799999,3747100,32.799999,NaN,2025_10
4,BBSE3,2025-10-07,32.820000,33.349998,32.740002,33.060001,6761600,33.060001,NaN,2025_10
...,...,...,...,...,...,...,...,...,...,...
737,WEGE3,2025-12-09,47.500000,47.810001,46.810001,47.660000,8650500,47.660000,0.0,2025_12
738,WEGE3,2025-12-10,47.700001,48.570000,47.500000,48.470001,4290600,48.470001,0.0,2025_12
739,WEGE3,2025-12-11,48.590000,48.779999,48.110001,48.549999,5154200,48.549999,0.0,2025_12
740,WEGE3,2025-12-12,48.700001,49.520000,47.980000,49.520000,9931700,49.520000,0.0,2025_12
741,WEGE3,2025-12-15,49.570000,50.000000,49.060001,49.680000,12049800,49.680000,0.0,2025_12

In [23]:
df_precos_historicos.loc[df_precos_historicos["Ano Mês"] == "2025_09"]#.iloc[-1, :]

Empty DataFrame
Columns: [symbol, date, open, high, low, close, volume, adjclose, dividends, Ano Mês]
Index: []

In [19]:
# df_precos_historicos.loc[(df_precos_historicos["symbol"] == "PETR4") & (df_precos_historicos["Ano Mês"] == "2024_04")].iloc[-1, :]["close"]
a = lista_tickers[0]
print(a)
print(datetime.now().strftime("%Y-%m-%d"))
teste = a[1].history(period='7d',interval='1d').iloc[[-1], :]
teste.reset_index(inplace=True)
teste.iloc[0, 1] = teste.iloc[0, 1].date() 
teste
# print(teste['date'][0])
# a[1].history(end=datetime.now().strftime("%Y-%m-%d"))

('BBSE3', <yahooquery.ticker.Ticker object at 0x000002695C664230>)
2025-12-03

C:\Users\luis.nascimento\AppData\Local\Temp\ipykernel_30872\4219498009.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2025-12-03' has dtype incompatible with datetime64[ns, America/Sao_Paulo], please explicitly cast to a compatible dtype first.
  teste.iloc[0, 1] = teste.iloc[0, 1].date()

     symbol        date       open       high    low  close   volume  adjclose
0  BBSE3.SA  2025-12-03  34.799999  34.990002  34.66  34.82  2636800     34.82

#### Calcula Lucro

In [24]:
lista_preco_fechamento = []
lista_preco_fechamento_total = []
lista_lucro = []
# lista_rendimento = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]
    valor_investido_total = df_aquisicao_geral.loc[i, "Valor Investido Total"]
    ano_mes = df_aquisicao_geral.loc[i, "Ano Mês"]

    preco_fechamento = df_precos_historicos.loc[(df_precos_historicos["symbol"] == ativo) & (df_precos_historicos["Ano Mês"] == ano_mes)].iloc[-1, :]["close"]

    lista_preco_fechamento.append(preco_fechamento)
    lista_preco_fechamento_total.append(preco_fechamento * cotas_acumuladas)
    if cotas_acumuladas > 0:
        lucro = (preco_fechamento * cotas_acumuladas) - valor_investido_total
        lista_lucro.append(lucro)
        # lista_rendimento.append((lucro / valor_investido_total) * 100)
    else:
        lista_lucro.append(0)
        # lista_rendimento.append(0)

df_aquisicao_geral["Preço de Fechamento"] = lista_preco_fechamento
df_aquisicao_geral["Preço de Fechamento Total"] = lista_preco_fechamento_total
df_aquisicao_geral["Lucro"] = lista_lucro
# df_aquisicao_geral["Rendimento"] = lista_rendimento
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
0,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Luis,33.480,33.48,33.48,2025_10,32.849998,32.849998,-0.630002
1,BBSE3,2025-10-01 00:00:00,33.48,1.0,1.0,Heitor,33.480,33.48,33.48,2025_10,32.849998,32.849998,-0.630002
2,BBSE3,2025-10-06 00:00:00,0,0,1.0,Luis,33.480,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
3,BBSE3,2025-10-06 00:00:00,0,0,1.0,Heitor,33.480,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
4,BBSE3,2025-10-09 00:00:00,0,0,1.0,Luis,33.480,0.00,33.48,2025_10,32.849998,32.849998,-0.630002
...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,WEGE3,2025-11-11 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_11,44.250000,1460.250000,274.230000
192,WEGE3,2025-11-28 00:00:00,0,0,6.0,Luis,41.065,0.00,246.39,2025_11,44.250000,265.500000,19.110000
193,WEGE3,2025-11-28 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_11,44.250000,1460.250000,274.230000
194,WEGE3,2025-12-08 00:00:00,0,0,6.0,Luis,41.065,0.00,246.39,2025_12,49.680000,298.080002,51.690002
195,WEGE3,2025-12-08 00:00:00,0,0,33.0,Heitor,35.940,0.00,1186.02,2025_12,49.680000,1639.440010,453.420010

In [25]:
df_aquisicao_geral["Data"] = pd.to_datetime(df_aquisicao_geral["Data"], format="%d-%m-%Y")
df_aquisicao_geral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ativo                      196 non-null    object
 1   Data                       196 non-null    datetime64[ns]
 2   Valor                      196 non-null    object
 3   Número de Cotas            196 non-null    object
 4   Cotas Acumuladas           196 non-null    object
 5   Dono                       196 non-null    object
 6   Preço Médio                196 non-null    float64
 7   Valor Investido            196 non-null    float64
 8   Valor Investido Total      196 non-null    float64
 9   Ano Mês                    196 non-null    object
 10  Preço de Fechamento        196 non-null    float64
 11  Preço de Fechamento Total  196 non-null    float64
 12  Lucro                      196 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 20.0+ KB

In [26]:
df_aquisicao_geral.loc[df_aquisicao_geral["Ativo"] == "PETR4"]

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
70,PETR4,2025-10-01,31.41,10.0,10.0,Luis,31.410000,314.10,314.10,2025_10,29.750000,297.500000,-16.600000
71,PETR4,2025-10-01,31.42,10.0,10.0,Heitor,31.420000,314.20,314.20,2025_10,29.750000,297.500000,-16.700000
72,PETR4,2025-10-06,0,0,10.0,Luis,31.410000,0.00,314.10,2025_10,29.750000,297.500000,-16.600000
73,PETR4,2025-10-06,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_10,29.750000,297.500000,-16.700000
74,PETR4,2025-10-09,0,0,10.0,Luis,31.410000,0.00,314.10,2025_10,29.750000,297.500000,-16.600000
75,PETR4,2025-10-09,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_10,29.750000,297.500000,-16.700000
76,PETR4,2025-10-14,0,0,10.0,Luis,31.410000,0.00,314.10,2025_10,29.750000,297.500000,-16.600000
77,PETR4,2025-10-14,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_10,29.750000,297.500000,-16.700000
78,PETR4,2025-11-11,32.93,5.0,15.0,Luis,31.916667,164.65,478.75,2025_11,31.790001,476.850014,-1.899986
79,PETR4,2025-11-11,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_11,31.790001,317.900009,3.700009
80,PETR4,2025-11-28,31.68,10.0,25.0,Luis,31.822000,316.80,795.55,2025_11,31.790001,794.750023,-0.799977
81,PETR4,2025-11-28,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_11,31.790001,317.900009,3.700009
82,PETR4,2025-12-08,31.61,15.0,40.0,Luis,31.742500,474.15,1269.70,2025_12,31.700001,1268.000031,-1.699969
83,PETR4,2025-12-08,0,0,10.0,Heitor,31.420000,0.00,314.20,2025_12,31.700001,317.000008,2.800008

In [27]:
df_aquisicao_geral.loc[df_aquisicao_geral["Ativo"] == "GOAU3"]

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
140,GOAU3,2025-10-01,0,0,0,Luis,0.000,0.00,0.00,2025_10,11.09,0.000000,0.000000
141,GOAU3,2025-10-01,0,0,0,Heitor,0.000,0.00,0.00,2025_10,11.09,0.000000,0.000000
142,GOAU3,2025-10-06,10.02,3.0,3.0,Luis,10.020,30.06,30.06,2025_10,11.09,33.270000,3.210000
143,GOAU3,2025-10-06,0,0,0,Heitor,0.000,0.00,0.00,2025_10,11.09,0.000000,0.000000
144,GOAU3,2025-10-09,0,0,3.0,Luis,10.020,0.00,30.06,2025_10,11.09,33.270000,3.210000
145,GOAU3,2025-10-09,10.18,3.0,3.0,Heitor,10.180,30.54,30.54,2025_10,11.09,33.270000,2.730000
146,GOAU3,2025-10-14,0,0,3.0,Luis,10.020,0.00,30.06,2025_10,11.09,33.270000,3.210000
147,GOAU3,2025-10-14,0,0,3.0,Heitor,10.180,0.00,30.54,2025_10,11.09,33.270000,2.730000
148,GOAU3,2025-11-11,10.87,3.0,6.0,Luis,10.445,32.61,62.67,2025_11,10.60,63.600002,0.930002
149,GOAU3,2025-11-11,0,0,3.0,Heitor,10.180,0.00,30.54,2025_11,10.60,31.800001,1.260001
150,GOAU3,2025-11-28,0,0,6.0,Luis,10.445,0.00,62.67,2025_11,10.60,63.600002,0.930002
151,GOAU3,2025-11-28,0,0,3.0,Heitor,10.180,0.00,30.54,2025_11,10.60,31.800001,1.260001
152,GOAU3,2025-12-08,0,0,6.0,Luis,10.445,0.00,62.67,2025_12,10.57,63.419998,0.749998
153,GOAU3,2025-12-08,0,0,3.0,Heitor,10.180,0.00,30.54,2025_12,10.57,31.709999,1.169999

In [28]:
df_aquisicao_geral.to_csv("Dados Modelados/Aquisições Realizadas.csv", index=False)

## Dividendos

In [29]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(ativos)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos.sort_values(by="Data", inplace=True)
df_dividendos

       Ativo       Data  Valor   DATA COM Tipo Receita    DY
12    KNCR11 2021-01-14   0.43 2020-12-30   Rendimento  0,49
54    XPCI11 2021-01-15   0.75 2020-12-30   Rendimento  0,81
29    HGLG11 2021-01-15   2.63 2020-12-30   Rendimento  1,45
71    XPML11 2021-01-22   0.67 2021-01-15   Rendimento  0,59
86    KNCR11 2021-02-11   0.28 2021-01-29   Rendimento  0,32
...      ...        ...    ...        ...          ...   ...
5703  KNCR11 2025-12-11   1.11 2025-11-28   Rendimento  1,04
5741  XPCI11 2025-12-12   0.90 2025-11-28   Rendimento  1,11
5716  HGLG11 2025-12-12   1.10 2025-11-28   Rendimento  0,68
1455   PETR4 2025-12-22   0.13 2025-08-21          JCP  0.45
1454   PETR4 2025-12-22   0.20 2025-08-21    Dividendo  0.66

[449 rows x 6 columns]

In [30]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 449 entries, 12 to 1454
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         449 non-null    object
 1   Data          449 non-null    datetime64[ns]
 2   Valor         449 non-null    float64
 3   DATA COM      449 non-null    datetime64[ns]
 4   Tipo Receita  449 non-null    object
 5   DY            449 non-null    object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 24.6+ KB

### Relaciona Dividendos com Aquisições para multiplicar o valor de dividendo pela quantidade total de cotas válidas

In [31]:
# Junta valores pelo dia

df_dividendos = df_dividendos.groupby(["Ativo", "Data", "DATA COM", "Tipo Receita"]).agg("sum")
df_dividendos = df_dividendos.reset_index()
df_dividendos

      Ativo       Data   DATA COM     Tipo Receita  Valor    DY
0     BBSE3 2021-02-25 2021-02-11        Dividendo   0.47  1.64
1     BBSE3 2021-02-25 2021-02-11  Rend. Tributado   0.00   0.0
2     BBSE3 2021-08-23 2021-08-11        Dividendo   0.52   2.4
3     BBSE3 2022-02-23 2022-02-10        Dividendo   0.91  3.76
4     BBSE3 2022-02-23 2022-02-10  Rend. Tributado   0.01  0.05
..      ...        ...        ...              ...    ...   ...
438  XPML11 2025-07-25 2025-07-18       Rendimento   0.92  0,89
439  XPML11 2025-08-25 2025-08-18       Rendimento   0.92  0,92
440  XPML11 2025-09-25 2025-09-18       Rendimento   0.92  0,87
441  XPML11 2025-10-24 2025-10-17       Rendimento   0.92  0,87
442  XPML11 2025-11-25 2025-11-17       Rendimento   0.92  0,86

[443 rows x 6 columns]

In [32]:
# Filtra apenas os dividendos válidos para as cotas adquiridas
# Separa cada dividendo por dono

df_dividendos_adquiridos = pd.merge(df_dividendos, df_aquisicao, on="Ativo", suffixes=[" Dividendos", " Aquisição"])
df_dividendos_adquiridos = df_dividendos_adquiridos.loc[df_dividendos_adquiridos["DATA COM"] >= df_dividendos_adquiridos["Data Aquisição"]]
df_dividendos_adquiridos

,Ativo,Data Dividendos,DATA COM,Tipo Receita,Valor Dividendos,DY,Data Aquisição,Valor Aquisição,Número de Cotas,Cotas Acumuladas,Dono
295,HGLG11,2025-11-14,2025-10-31,Rendimento,1.10,"0,69",2025-10-01,160.30,1.0,1.0,Heitor
296,HGLG11,2025-11-14,2025-10-31,Rendimento,1.10,"0,69",2025-10-01,160.32,1.0,1.0,Luis
299,HGLG11,2025-12-12,2025-11-28,Rendimento,1.10,"0,68",2025-10-01,160.30,1.0,1.0,Heitor
300,HGLG11,2025-12-12,2025-11-28,Rendimento,1.10,"0,68",2025-10-01,160.32,1.0,1.0,Luis
301,HGLG11,2025-12-12,2025-11-28,Rendimento,1.10,"0,68",2025-11-11,158.49,1.0,2.0,Luis
455,HTMX11,2025-11-07,2025-10-31,Rendimento,1.56,"1,11",2025-10-01,139.55,1.0,1.0,Heitor
456,HTMX11,2025-11-07,2025-10-31,Rendimento,1.56,"1,11",2025-10-01,139.55,1.0,1.0,Luis
459,HTMX11,2025-12-05,2025-11-28,Rendimento,1.80,"1,25",2025-10-01,139.55,1.0,1.0,Heitor
460,HTMX11,2025-12-05,2025-11-28,Rendimento,1.80,"1,25",2025-10-01,139.55,1.0,1.0,Luis
461,HTMX11,2025-12-05,2025-11-28,Rendimento,1.80,"1,25",2025-11-11,138.43,2.0,3.0,Luis
695,KNCR11,2025-11-13,2025-10-31,Rendimento,1.33,"1,26",2025-10-01,103.66,1.0,1.0,Heitor
696,KNCR11,2025-11-13,2025-10-31,Rendimento,1.33,"1,26",2025-10-01,103.57,1.0,1.0,Luis
699,KNCR11,2025-12-11,2025-11-28,Rendimento,1.11,"1,04",2025-10-01,103.66,1.0,1.0,Heitor
700,KNCR11,2025-12-11,2025-11-28,Rendimento,1.11,"1,04",2025-10-01,103.57,1.0,1.0,Luis
701,KNCR11,2025-12-11,2025-11-28,Rendimento,1.11,"1,04",2025-11-11,104.85,1.0,2.0,Luis
1582,XPCI11,2025-11-14,2025-10-31,Rendimento,0.90,"1,08",2025-10-01,84.00,1.0,1.0,Heitor
1583,XPCI11,2025-11-14,2025-10-31,Rendimento,0.90,"1,08",2025-10-01,84.03,1.0,1.0,Luis
1586,XPCI11,2025-12-12,2025-11-28,Rendimento,0.90,"1,11",2025-10-01,84.00,1.0,1.0,Heitor
1587,XPCI11,2025-12-12,2025-11-28,Rendimento,0.90,"1,11",2025-10-01,84.03,1.0,1.0,Luis
1588,XPCI11,2025-12-12,2025-11-28,Rendimento,0.90,"1,11",2025-11-11,81.80,1.0,2.0,Luis
1818,XPML11,2025-10-24,2025-10-17,Rendimento,0.92,"0,87",2025-10-01,105.21,1.0,1.0,Heitor
1819,XPML11,2025-10-24,2025-10-17,Rendimento,0.92,"0,87",2025-10-01,105.21,1.0,1.0,Luis
1822,XPML11,2025-11-25,2025-11-17,Rendimento,0.92,"0,86",2025-10-01,105.21,1.0,1.0,Heitor
1823,XPML11,2025-11-25,2025-11-17,Rendimento,0.92,"0,86",2025-10-01,105.21,1.0,1.0,Luis
1824,XPML11,2025-11-25,2025-11-17,Rendimento,0.92,"0,86",2025-11-11,106.75,1.0,2.0,Luis

In [33]:
df_dividendos_adquiridos = df_dividendos_adquiridos.filter(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Cotas Acumuladas', 'Dono'])
df_dividendos_adquiridos

,Ativo,Data Dividendos,Valor Dividendos,DATA COM,Tipo Receita,DY,Cotas Acumuladas,Dono
295,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",1.0,Heitor
296,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",1.0,Luis
299,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",1.0,Heitor
300,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",1.0,Luis
301,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",2.0,Luis
455,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",1.0,Heitor
456,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",1.0,Luis
459,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",1.0,Heitor
460,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",1.0,Luis
461,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",3.0,Luis
695,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",1.0,Heitor
696,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",1.0,Luis
699,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",1.0,Heitor
700,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",1.0,Luis
701,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",2.0,Luis
1582,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",1.0,Heitor
1583,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",1.0,Luis
1586,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",1.0,Heitor
1587,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",1.0,Luis
1588,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",2.0,Luis
1818,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",1.0,Heitor
1819,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",1.0,Luis
1822,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",1.0,Heitor
1823,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",1.0,Luis
1824,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",2.0,Luis

In [34]:
# Agrupa os dividendos, capturando o valor máximo de cotas do ativo válidas para multiplicar pelo dividendo

df_dividendos_adquiridos = df_dividendos_adquiridos.groupby(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Dono']).agg("max")
df_dividendos_adquiridos = df_dividendos_adquiridos.reset_index()
df_dividendos_adquiridos.rename(columns={"Data Dividendos": "Data", "Valor Dividendos": "Valor"}, inplace=True)
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas
0,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",Heitor,1.0
1,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",Luis,1.0
2,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",Heitor,1.0
3,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",Luis,2.0
4,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",Heitor,1.0
5,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",Luis,1.0
6,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",Heitor,1.0
7,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",Luis,3.0
8,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",Heitor,1.0
9,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",Luis,1.0
10,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",Heitor,1.0
11,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",Luis,2.0
12,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",Heitor,1.0
13,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",Luis,1.0
14,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",Heitor,1.0
15,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",Luis,2.0
16,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",Heitor,1.0
17,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",Luis,1.0
18,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",Heitor,1.0
19,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",Luis,2.0

In [35]:
# Calcula dividendo total, valor x número de cotas válidas e acumula os dividendos

lista_dividendos_totais = []
# lista_dividendos_acumulados = []

dividendo_acumulado = 0
for i in df_dividendos_adquiridos.index:
    valor = df_dividendos_adquiridos.loc[i, "Valor"]
    cotas_acumul = df_dividendos_adquiridos.loc[i, "Cotas Acumuladas"]
    dividendo_acumulado += valor * cotas_acumul

    lista_dividendos_totais.append(valor * cotas_acumul)
    # lista_dividendos_acumulados.append(dividendo_acumulado)

df_dividendos_adquiridos["Dividendos Totais"] = lista_dividendos_totais
# df_dividendos_adquiridos["Dividendos Acumulados"] = lista_dividendos_acumulados
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais
0,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",Heitor,1.0,1.10
1,HGLG11,2025-11-14,1.10,2025-10-31,Rendimento,"0,69",Luis,1.0,1.10
2,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",Heitor,1.0,1.10
3,HGLG11,2025-12-12,1.10,2025-11-28,Rendimento,"0,68",Luis,2.0,2.20
4,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",Heitor,1.0,1.56
5,HTMX11,2025-11-07,1.56,2025-10-31,Rendimento,"1,11",Luis,1.0,1.56
6,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",Heitor,1.0,1.80
7,HTMX11,2025-12-05,1.80,2025-11-28,Rendimento,"1,25",Luis,3.0,5.40
8,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",Heitor,1.0,1.33
9,KNCR11,2025-11-13,1.33,2025-10-31,Rendimento,"1,26",Luis,1.0,1.33
10,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",Heitor,1.0,1.11
11,KNCR11,2025-12-11,1.11,2025-11-28,Rendimento,"1,04",Luis,2.0,2.22
12,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",Heitor,1.0,0.90
13,XPCI11,2025-11-14,0.90,2025-10-31,Rendimento,"1,08",Luis,1.0,0.90
14,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",Heitor,1.0,0.90
15,XPCI11,2025-12-12,0.90,2025-11-28,Rendimento,"1,11",Luis,2.0,1.80
16,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",Heitor,1.0,0.92
17,XPML11,2025-10-24,0.92,2025-10-17,Rendimento,"0,87",Luis,1.0,0.92
18,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",Heitor,1.0,0.92
19,XPML11,2025-11-25,0.92,2025-11-17,Rendimento,"0,86",Luis,2.0,1.84

In [36]:
df_dividendos_adquiridos.to_csv("Dados Modelados/Dividendos Recebidos.csv", index=False)

## Análise de Preço Médio

In [37]:
lista_tickers

[('BBSE3', <yahooquery.ticker.Ticker at 0x1928d4e5b50>),
 ('XPML11', <yahooquery.ticker.Ticker at 0x1928da63080>),
 ('XPCI11', <yahooquery.ticker.Ticker at 0x1928dab9790>),
 ('VALE3', <yahooquery.ticker.Ticker at 0x1928dab8950>),
 ('TAEE11', <yahooquery.ticker.Ticker at 0x1928dabb5f0>),
 ('PETR4', <yahooquery.ticker.Ticker at 0x1928daba7e0>),
 ('KNCR11', <yahooquery.ticker.Ticker at 0x1928dabbf20>),
 ('HTMX11', <yahooquery.ticker.Ticker at 0x1928dabb0e0>),
 ('HGLG11', <yahooquery.ticker.Ticker at 0x1928daee1e0>),
 ('EMBR3', <yahooquery.ticker.Ticker at 0x1928daedd90>),
 ('GOAU3', <yahooquery.ticker.Ticker at 0x1928daec2f0>),
 ('RAIL3', <yahooquery.ticker.Ticker at 0x1928daed0a0>),
 ('SUZB3', <yahooquery.ticker.Ticker at 0x1928db63b60>),
 ('WEGE3', <yahooquery.ticker.Ticker at 0x1928dbabd40>)]

In [38]:
def formata_data(data):
    if len(str(data).split(' ')) > 1:
        return data.date()
    else:
        return data

df_precos_6_meses = pd.DataFrame()
for nome, ticker in lista_tickers:
    precos_recentes = ticker.history(period='6mo',interval='1mo')
    precos_recentes.reset_index(inplace=True)
    precos_recentes = precos_recentes.loc[:, ['symbol', 'date', 'close']]
    precos_recentes['date'] = precos_recentes['date'].apply(lambda x: formata_data(x))
    df_precos_6_meses = pd.concat([df_precos_6_meses, precos_recentes])
    
df_precos_6_meses

      symbol        date      close
0   BBSE3.SA  2025-07-01  33.700001
1   BBSE3.SA  2025-08-01  32.820000
2   BBSE3.SA  2025-09-01  33.259998
3   BBSE3.SA  2025-10-01  32.849998
4   BBSE3.SA  2025-11-01  34.110001
..       ...         ...        ...
2   WEGE3.SA  2025-09-01  36.590000
3   WEGE3.SA  2025-10-01  42.099998
4   WEGE3.SA  2025-11-01  44.250000
5   WEGE3.SA  2025-12-01  49.680000
6   WEGE3.SA  2025-12-15  49.680000

[97 rows x 3 columns]

In [39]:
df_precos_6_meses["symbol"] = df_precos_6_meses["symbol"].str.replace(".SA", "")
df_precos_6_meses.rename(columns={"symbol": "Ativo", "date": "Data", "close": "Preço"}, inplace=True)
df_precos_6_meses

    Ativo        Data      Preço
0   BBSE3  2025-07-01  33.700001
1   BBSE3  2025-08-01  32.820000
2   BBSE3  2025-09-01  33.259998
3   BBSE3  2025-10-01  32.849998
4   BBSE3  2025-11-01  34.110001
..    ...         ...        ...
2   WEGE3  2025-09-01  36.590000
3   WEGE3  2025-10-01  42.099998
4   WEGE3  2025-11-01  44.250000
5   WEGE3  2025-12-01  49.680000
6   WEGE3  2025-12-15  49.680000

[97 rows x 3 columns]

In [40]:
df_precos_6_meses.loc[df_precos_6_meses["Ativo"] == 'SUZB3']

   Ativo        Data      Preço
0  SUZB3  2025-07-01  52.150002
1  SUZB3  2025-08-01  52.450001
2  SUZB3  2025-09-01  49.900002
3  SUZB3  2025-10-01  48.889999
4  SUZB3  2025-11-01  47.580002
5  SUZB3  2025-12-01  48.709999
6  SUZB3  2025-12-15  48.709999

In [41]:
df_precos_6_meses.to_csv("Dados Modelados/Preços nos últimos 6 meses.csv", index=False)