# Bibliotecas

In [319]:
import pandas as pd
import yahooquery as yq
from itertools import product
from datetime import datetime

# Ativos da Carteira

In [333]:
carteira_1 = [
    # Ações
    ("BBSE3",
	"PETR4",
	"TAEE11",
	"VALE3"),

    # FIIs
    ("HGLG11",
    "HTMX11",
    "KNCR11",
    "XPCI11",
    "XPML11")

]

carteira_2 = [
    # Ações
    "EMBR3",
	"GOAU3",
	"RAIL3",
	"SUZB3",
    "WEGE3"
]

ativos = list(carteira_1[0]) + list(carteira_1[1]) + carteira_2
lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))

idx = 0
df_ativos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_ativos.loc[idx, 'Ativo'] = nome
    df_ativos.loc[idx, 'Setor'] = ticker.asset_profile[nome+'.SA']['industry']
    df_ativos.loc[idx, 'Indústria'] = ticker.asset_profile[nome+'.SA']['sector']
    df_ativos.loc[idx, 'Data Recomendação'] = datetime.now().strftime('%d-%m-%Y')
    df_ativos.loc[idx, 'Recomendação'] = ticker.financial_data[nome+'.SA']['recommendationKey']

    if nome in carteira_1[0]:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 1
    elif nome in carteira_1[1]:
        df_ativos.loc[idx, 'Tipo'] = "FII"
        df_ativos.loc[idx, 'Carteira'] = 1
    else:
        df_ativos.loc[idx, 'Tipo'] = "Ação"
        df_ativos.loc[idx, 'Carteira'] = 2
    idx += 1

df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira
0,BBSE3,Insurance - Diversified,Financial Services,09-10-2025,buy,Ação,1.0
1,PETR4,Oil & Gas Integrated,Energy,09-10-2025,buy,Ação,1.0
2,TAEE11,Utilities - Regulated Electric,Utilities,09-10-2025,underperform,Ação,1.0
3,VALE3,Other Industrial Metals & Mining,Basic Materials,09-10-2025,buy,Ação,1.0
4,HGLG11,REIT - Diversified,Real Estate,09-10-2025,none,FII,1.0
5,HTMX11,REIT - Hotel & Motel,Real Estate,09-10-2025,none,FII,1.0
6,KNCR11,REIT - Mortgage,Real Estate,09-10-2025,none,FII,1.0
7,XPCI11,REIT - Mortgage,Real Estate,09-10-2025,none,FII,1.0
8,XPML11,REIT - Retail,Real Estate,09-10-2025,none,FII,1.0
9,EMBR3,Aerospace & Defense,Industrials,09-10-2025,hold,Ação,2.0
10,GOAU3,Steel,Basic Materials,09-10-2025,none,Ação,2.0
11,RAIL3,Railroads,Industrials,09-10-2025,buy,Ação,2.0
12,SUZB3,Paper & Paper Products,Basic Materials,09-10-2025,strong_buy,Ação,2.0
13,WEGE3,Electrical Equipment & Parts,Industrials,09-10-2025,hold,Ação,2.0

In [337]:
acoes1 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 1)]['Ativo'].values
acoes1.sort()
print("Ações Carteira 1: ", acoes1)

fundos = df_ativos.loc[df_ativos['Tipo'] == "FII"]['Ativo'].values
fundos.sort()
print("Fundos Carteira 1: ", fundos)

acoes2 = df_ativos.loc[(df_ativos['Tipo'] == "Ação") & (df_ativos["Carteira"] == 2)]['Ativo'].values
acoes2.sort()
print("Ações Carteira 2: ", acoes2)

assert tuple(acoes1) == carteira_1[0]
assert tuple(fundos) == carteira_1[1]
assert list(acoes2) == carteira_2

Ações Carteira 1:  ['BBSE3' 'PETR4' 'TAEE11' 'VALE3']
Fundos Carteira 1:  ['HGLG11' 'HTMX11' 'KNCR11' 'XPCI11' 'XPML11']
Ações Carteira 2:  ['EMBR3' 'GOAU3' 'RAIL3' 'SUZB3' 'WEGE3']

In [338]:
df_ativos["Data Recomendação"] = pd.to_datetime(df_ativos["Data Recomendação"], format="%d-%m-%Y")
df_ativos["Carteira"] = df_ativos["Carteira"].astype(int)

for i in df_ativos.index:
    recomendacao = df_ativos.loc[i, "Recomendação"]
    if recomendacao == "none":
        df_ativos.loc[i, "Recomendação"] = None
        df_ativos.loc[i, "Data Recomendação"] = None

df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira
0,BBSE3,Insurance - Diversified,Financial Services,2025-10-09,buy,Ação,1
1,PETR4,Oil & Gas Integrated,Energy,2025-10-09,buy,Ação,1
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-10-09,underperform,Ação,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-10-09,buy,Ação,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1
9,EMBR3,Aerospace & Defense,Industrials,2025-10-09,hold,Ação,2
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2
11,RAIL3,Railroads,Industrials,2025-10-09,buy,Ação,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-10-09,strong_buy,Ação,2
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-10-09,hold,Ação,2

In [339]:
df_ativos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Ativo              14 non-null     object
 1   Setor              14 non-null     object
 2   Indústria          14 non-null     object
 3   Data Recomendação  8 non-null      datetime64[ns]
 4   Recomendação       8 non-null      object
 5   Tipo               14 non-null     object
 6   Carteira           14 non-null     int32
dtypes: datetime64[ns](1), int32(1), object(5)
memory usage: 1.4+ KB

In [342]:
balanco = {
    'BBSE3': 1,
    'PETR4': 10,
    'TAEE11': 1,
    'VALE3': 1,

    'HGLG11': 1,
    'HTMX11': 1, 
    'KNCR11': 1, 
    'XPCI11': 1,
    'XPML11': 1,

    "EMBR3": 1,
	"GOAU3": 3,
	"RAIL3": 2,
	"SUZB3": 1,
    "WEGE3": 3
}

balanco_ativos = []
for i in df_ativos.index:
    balanco_ativos.append(
        balanco[df_ativos.loc[[i], "Ativo"].values[0]]
    )

df_ativos["Balanço de Cotas"] = balanco_ativos
df_ativos

,Ativo,Setor,Indústria,Data Recomendação,Recomendação,Tipo,Carteira,Balanço de Cotas
0,BBSE3,Insurance - Diversified,Financial Services,2025-10-09,buy,Ação,1,1
1,PETR4,Oil & Gas Integrated,Energy,2025-10-09,buy,Ação,1,10
2,TAEE11,Utilities - Regulated Electric,Utilities,2025-10-09,underperform,Ação,1,1
3,VALE3,Other Industrial Metals & Mining,Basic Materials,2025-10-09,buy,Ação,1,1
4,HGLG11,REIT - Diversified,Real Estate,NaT,None,FII,1,1
5,HTMX11,REIT - Hotel & Motel,Real Estate,NaT,None,FII,1,1
6,KNCR11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
7,XPCI11,REIT - Mortgage,Real Estate,NaT,None,FII,1,1
8,XPML11,REIT - Retail,Real Estate,NaT,None,FII,1,1
9,EMBR3,Aerospace & Defense,Industrials,2025-10-09,hold,Ação,2,1
10,GOAU3,Steel,Basic Materials,NaT,None,Ação,2,3
11,RAIL3,Railroads,Industrials,2025-10-09,buy,Ação,2,2
12,SUZB3,Paper & Paper Products,Basic Materials,2025-10-09,strong_buy,Ação,2,1
13,WEGE3,Electrical Equipment & Parts,Industrials,2025-10-09,hold,Ação,2,3

In [343]:
df_ativos.to_csv('Dados Modelados/carteira_ativos.csv', index=False)

# Monta o Calendário dos Ativos da Carteira

## Aquisição

In [346]:
df_aquisicao = pd.read_csv("Exemplo Aquisição.csv")
df_aquisicao.rename(columns={"Preço de Aquisição": "Valor", "Data de Aquisição": "Data"}, inplace=True)
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Dono"])
df_aquisicao['Valor'] = df_aquisicao['Valor'].str.replace(',', '.').astype(float)
df_aquisicao["Data"] = pd.to_datetime(df_aquisicao["Data"], format="%d-%m-%Y")
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao

     Ativo       Data   Valor  Número de Cotas    Dono
0    PETR4 2024-04-01   32.00                1    Luis
1    GOAU3 2024-05-01    9.80                3    Luis
2    GOAU3 2024-05-01    9.80                3  Heitor
3    RAIL3 2024-06-01   15.77                3  Heitor
4    PETR4 2024-08-01   31.00                2    Luis
5    PETR4 2024-11-01   29.31                3    Luis
6    VALE3 2024-11-01   34.87                2    Luis
7    SUZB3 2024-11-01   50.31                2    Luis
8    SUZB3 2024-12-01   50.24                2  Heitor
12   PETR4 2025-07-01   31.79                3  Heitor
11   PETR4 2025-07-01   32.87                2  Heitor
9   TAEE11 2025-07-01   28.96                1    Luis
13   VALE3 2025-08-01   33.89                2  Heitor
14  HGLG11 2025-08-01  152.89                1  Heitor
15   WEGE3 2025-08-01   36.06                4    Luis
16   WEGE3 2025-08-01   36.06                4  Heitor
17   PETR4 2025-09-01   31.34                1  Heitor
10   PETR4 2025-09-01   31.09                1    Luis
18   PETR4 2025-09-01   31.75                2  Heitor

In [347]:
df_aquisicao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ativo            19 non-null     object
 1   Data             19 non-null     datetime64[ns]
 2   Valor            19 non-null     float64
 3   Número de Cotas  19 non-null     int64
 4   Dono             19 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 912.0+ bytes

### Acumula cotas e agrupa aquisições no mesmo dia

In [348]:
# Acumula as cotas por ativo e dono

dic_cotas_acum = {
    "Heitor": {},
    "Luis": {}
}

lista_cotas_acum = []

for i in df_aquisicao.index:
    ativo = df_aquisicao.loc[i, "Ativo"]
    cotas = df_aquisicao.loc[i, "Número de Cotas"]
    dono = df_aquisicao.loc[i, "Dono"]
    if ativo not in dic_cotas_acum[dono]:
        dic_cotas_acum[dono][ativo] = cotas
    else:
        dic_cotas_acum[dono][ativo] += cotas
    lista_cotas_acum.append(dic_cotas_acum[dono][ativo])

df_aquisicao["Cotas Acumuladas"] = lista_cotas_acum
df_aquisicao = df_aquisicao.filter(["Ativo", "Data", "Valor", "Número de Cotas", "Cotas Acumuladas", "Dono"])
df_aquisicao

     Ativo       Data   Valor  Número de Cotas  Cotas Acumuladas    Dono
0    PETR4 2024-04-01   32.00                1                 1    Luis
1    GOAU3 2024-05-01    9.80                3                 3    Luis
2    GOAU3 2024-05-01    9.80                3                 3  Heitor
3    RAIL3 2024-06-01   15.77                3                 3  Heitor
4    PETR4 2024-08-01   31.00                2                 3    Luis
5    PETR4 2024-11-01   29.31                3                 6    Luis
6    VALE3 2024-11-01   34.87                2                 2    Luis
7    SUZB3 2024-11-01   50.31                2                 2    Luis
8    SUZB3 2024-12-01   50.24                2                 2  Heitor
12   PETR4 2025-07-01   31.79                3                 3  Heitor
11   PETR4 2025-07-01   32.87                2                 5  Heitor
9   TAEE11 2025-07-01   28.96                1                 1    Luis
13   VALE3 2025-08-01   33.89                2                 2  Heitor
14  HGLG11 2025-08-01  152.89                1                 1  Heitor
15   WEGE3 2025-08-01   36.06                4                 4    Luis
16   WEGE3 2025-08-01   36.06                4                 4  Heitor
17   PETR4 2025-09-01   31.34                1                 6  Heitor
10   PETR4 2025-09-01   31.09                1                 7    Luis
18   PETR4 2025-09-01   31.75                2                 8  Heitor

In [349]:
df_compras_mesmo_dia = df_aquisicao.loc[df_aquisicao.duplicated(subset=["Ativo", "Data", "Dono"], keep=False)]
df_compras_mesmo_dia

    Ativo       Data  Valor  Número de Cotas  Cotas Acumuladas    Dono
12  PETR4 2025-07-01  31.79                3                 3  Heitor
11  PETR4 2025-07-01  32.87                2                 5  Heitor
17  PETR4 2025-09-01  31.34                1                 6  Heitor
18  PETR4 2025-09-01  31.75                2                 8  Heitor

In [350]:
# Unifica as aquisições do mesmo dono no mesmo dia

indices_mesmo_dia = list(df_compras_mesmo_dia.index)

dicionario_novo = {"Ativo": [], "Data": [], "Valor": [], "Número de Cotas": [], "Cotas Acumuladas": [], "Dono": []}

ativo_anterior = None
data_anterior = None
dono_anterior = None
valor_total = 0
cotas_totais = 0
maior_cota_acumulada = -1
primeiro = True

for i in df_compras_mesmo_dia.index:
    ativo = df_compras_mesmo_dia.loc[i, "Ativo"]
    data = df_compras_mesmo_dia.loc[i, "Data"]
    valor = df_compras_mesmo_dia.loc[i, "Valor"]
    num_cotas = df_compras_mesmo_dia.loc[i, "Número de Cotas"]
    num_cotas_acumul = df_compras_mesmo_dia.loc[i, "Cotas Acumuladas"]
    dono = df_compras_mesmo_dia.loc[i, "Dono"]

    if (not primeiro) and ((ativo != ativo_anterior) or (data != data_anterior) or (dono != dono_anterior)):
        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)

        valor_total = valor * num_cotas
        cotas_totais = num_cotas
        maior_cota_acumulada = num_cotas_acumul
    elif i == df_compras_mesmo_dia.index[-1]:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

        if num_cotas_acumul > maior_cota_acumulada:
            maior_cota_acumulada = num_cotas_acumul

        dicionario_novo["Ativo"].append(ativo_anterior)
        dicionario_novo["Data"].append(data_anterior)
        dicionario_novo["Valor"].append(valor_total / cotas_totais)
        dicionario_novo["Número de Cotas"].append(cotas_totais)
        dicionario_novo["Cotas Acumuladas"].append(maior_cota_acumulada)
        dicionario_novo["Dono"].append(dono_anterior)
    else:
        valor_total += valor * num_cotas
        cotas_totais += num_cotas

    if num_cotas_acumul > maior_cota_acumulada:
        maior_cota_acumulada = num_cotas_acumul
    
    ativo_anterior = ativo
    data_anterior = data
    dono_anterior = dono
    primeiro = False

pd.DataFrame(dicionario_novo)

   Ativo       Data      Valor  Número de Cotas  Cotas Acumuladas    Dono
0  PETR4 2025-07-01  32.222000                5                 5  Heitor
1  PETR4 2025-09-01  31.613333                3                 8  Heitor

In [351]:
# Remove as aquisições do mesmo dia e adiciona a média ponderada da compra

df_aquisicao.drop(indices_mesmo_dia, inplace=True)
df_aquisicao = pd.concat([df_aquisicao, pd.DataFrame(dicionario_novo)])
df_aquisicao.sort_values(by="Data", inplace=True)
df_aquisicao.index = range(len(df_aquisicao))
df_aquisicao

     Ativo       Data       Valor  Número de Cotas  Cotas Acumuladas    Dono
0    PETR4 2024-04-01   32.000000                1                 1    Luis
1    GOAU3 2024-05-01    9.800000                3                 3    Luis
2    GOAU3 2024-05-01    9.800000                3                 3  Heitor
3    RAIL3 2024-06-01   15.770000                3                 3  Heitor
4    PETR4 2024-08-01   31.000000                2                 3    Luis
5    PETR4 2024-11-01   29.310000                3                 6    Luis
6    VALE3 2024-11-01   34.870000                2                 2    Luis
7    SUZB3 2024-11-01   50.310000                2                 2    Luis
8    SUZB3 2024-12-01   50.240000                2                 2  Heitor
9   TAEE11 2025-07-01   28.960000                1                 1    Luis
10   PETR4 2025-07-01   32.222000                5                 5  Heitor
11   VALE3 2025-08-01   33.890000                2                 2  Heitor
12  HGLG11 2025-08-01  152.890000                1                 1  Heitor
13   WEGE3 2025-08-01   36.060000                4                 4    Luis
14   WEGE3 2025-08-01   36.060000                4                 4  Heitor
15   PETR4 2025-09-01   31.090000                1                 7    Luis
16   PETR4 2025-09-01   31.613333                3                 8  Heitor

### Replica ativos para todas as datas

In [352]:
ativos = pd.unique(df_aquisicao["Ativo"])
data = pd.unique(df_aquisicao["Data"])
dono = pd.unique(df_aquisicao["Dono"])

permutacao = list(product(ativos, data, dono))
df_permutacao = pd.DataFrame(permutacao, columns=["Ativo", "Data", "Dono"])
df_permutacao

     Ativo       Data    Dono
0    PETR4 2024-04-01    Luis
1    PETR4 2024-04-01  Heitor
2    PETR4 2024-05-01    Luis
3    PETR4 2024-05-01  Heitor
4    PETR4 2024-06-01    Luis
..     ...        ...     ...
139  WEGE3 2025-07-01  Heitor
140  WEGE3 2025-08-01    Luis
141  WEGE3 2025-08-01  Heitor
142  WEGE3 2025-09-01    Luis
143  WEGE3 2025-09-01  Heitor

[144 rows x 3 columns]

In [353]:
df_aquisicao_geral = pd.DataFrame()

for i in df_permutacao.index:
    ativo = df_permutacao.loc[i, "Ativo"]
    data = df_permutacao.loc[i, "Data"]
    dono = df_permutacao.loc[i, "Dono"]

    serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] == data) & (df_aquisicao["Dono"] == dono)]
    if len(serie_aquisicao) >= 1:
        df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
    else:
        serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)]
        if len(serie_aquisicao) < 1:
            serie_aquisicao = pd.Series(
                {
                    "Ativo": ativo, 
                    "Data": data,
                    "Valor": 0,
                    "Número de Cotas": 0,
                    "Cotas Acumuladas": 0,
                    "Dono": dono
                }
            ).to_frame().T

            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])
        else:
            serie_aquisicao = df_aquisicao.loc[(df_aquisicao["Ativo"] == ativo) & (df_aquisicao["Data"] < data) & (df_aquisicao["Dono"] == dono)].iloc[-1, :]
            serie_aquisicao.loc["Data"] = data
            serie_aquisicao.loc["Valor"] = 0
            serie_aquisicao.loc["Número de Cotas"] = 0
            serie_aquisicao = serie_aquisicao.to_frame().T
            df_aquisicao_geral = pd.concat([df_aquisicao_geral, serie_aquisicao])

df_aquisicao_geral.index = range(len(df_aquisicao_geral))
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor
2,PETR4,2024-05-01 00:00:00,0,0,1,Luis
3,PETR4,2024-05-01 00:00:00,0,0,0,Heitor
4,PETR4,2024-06-01 00:00:00,0,0,1,Luis
...,...,...,...,...,...,...
139,WEGE3,2025-07-01 00:00:00,0,0,0,Heitor
140,WEGE3,2025-08-01 00:00:00,36.06,4,4,Luis
141,WEGE3,2025-08-01 00:00:00,36.06,4,4,Heitor
142,WEGE3,2025-09-01 00:00:00,0,0,4,Luis
143,WEGE3,2025-09-01 00:00:00,0,0,4,Heitor

In [354]:
dicionario_preco_medio = {
    "Luis": {},
    "Heitor": {}
}

lista_preco_medio = []
lista_valor_investido = []
lista_valor_investido_total = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    dono = df_aquisicao_geral.loc[i, "Dono"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    num_cotas = df_aquisicao_geral.loc[i, "Número de Cotas"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]

    if cotas_acumuladas == 0:
        lista_preco_medio.append(0)
        lista_valor_investido.append(0)
        lista_valor_investido_total.append(0)
    elif valor == 0:
        lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)
    else:
        if ativo in dicionario_preco_medio[dono]:
            dicionario_preco_medio[dono][ativo][0] += valor * num_cotas
            dicionario_preco_medio[dono][ativo][1] += num_cotas
            lista_preco_medio.append(dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1])
        else:
            dicionario_preco_medio[dono][ativo] = [valor * num_cotas, num_cotas]
            lista_preco_medio.append((valor * num_cotas) / num_cotas)
        lista_valor_investido.append(valor * num_cotas)
        lista_valor_investido_total.append((dicionario_preco_medio[dono][ativo][0] / dicionario_preco_medio[dono][ativo][1]) * cotas_acumuladas)

df_aquisicao_geral["Preço Médio"] = lista_preco_medio
df_aquisicao_geral["Valor Investido"] = lista_valor_investido
df_aquisicao_geral["Valor Investido Total"] = lista_valor_investido_total
df_aquisicao_geral["Ano Mês"] = df_aquisicao_geral["Data"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis,32.00,32.00,32.00,2024_04
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2024_04
2,PETR4,2024-05-01 00:00:00,0,0,1,Luis,32.00,0.00,32.00,2024_05
3,PETR4,2024-05-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2024_05
4,PETR4,2024-06-01 00:00:00,0,0,1,Luis,32.00,0.00,32.00,2024_06
...,...,...,...,...,...,...,...,...,...,...
139,WEGE3,2025-07-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_07
140,WEGE3,2025-08-01 00:00:00,36.06,4,4,Luis,36.06,144.24,144.24,2025_08
141,WEGE3,2025-08-01 00:00:00,36.06,4,4,Heitor,36.06,144.24,144.24,2025_08
142,WEGE3,2025-09-01 00:00:00,0,0,4,Luis,36.06,0.00,144.24,2025_09
143,WEGE3,2025-09-01 00:00:00,0,0,4,Heitor,36.06,0.00,144.24,2025_09

### Lucro e Rendimento

#### Captura Preço Histórico

In [355]:
data_minima = df_aquisicao_geral["Data"].min().strftime("%Y-%m-%d")
data_maxima = df_aquisicao_geral["Data"].max().strftime("%Y-%m-%d")
ano = int(data_maxima[:4])
mes = int(data_maxima[5:7])
if mes < 12:
    mes += 1
else:
    ano += 1
    mes = 1
data_maxima = f"{ano}-{mes}-01"
ativos = pd.unique(df_aquisicao_geral["Ativo"]).tolist()

lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))

df_precos_historicos = pd.DataFrame()
for nome, ticker in lista_tickers:
    df_precos_historicos = pd.concat([df_precos_historicos, ticker.history(start=data_minima, end=data_maxima, interval='1d')])

df_precos_historicos.reset_index(inplace=True)
df_precos_historicos["symbol"] = df_precos_historicos["symbol"].str.replace(".SA", "")
df_precos_historicos["Ano Mês"] = df_precos_historicos["date"].apply(lambda x: str(x)[0:4] + "_" + str(x)[5:7])
df_precos_historicos

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
0,PETR4,2024-04-01,37.500000,37.709999,37.209999,37.650002,23697800,28.460199,0.000000,2024_04
1,PETR4,2024-04-02,37.820000,38.650002,37.770000,38.619999,45930700,29.193434,0.000000,2024_04
2,PETR4,2024-04-03,38.700001,39.009998,38.220001,38.419998,31437200,29.042248,0.000000,2024_04
3,PETR4,2024-04-04,38.470001,39.480000,37.430000,37.980000,165566800,28.709646,0.000000,2024_04
4,PETR4,2024-04-05,37.900002,38.570000,37.169998,38.099998,65469200,28.800354,0.000000,2024_04
...,...,...,...,...,...,...,...,...,...,...
3019,WEGE3,2025-09-24,36.740002,37.090000,36.599998,36.889999,4562300,36.778034,0.000000,2025_09
3020,WEGE3,2025-09-25,36.990002,36.990002,36.110001,36.349998,8075800,36.239670,0.000000,2025_09
3021,WEGE3,2025-09-26,36.490002,36.599998,36.209999,36.320000,4491900,36.209763,0.000000,2025_09
3022,WEGE3,2025-09-29,36.970001,36.970001,36.029999,36.369999,4873200,36.369999,0.110235,2025_09
3023,WEGE3,2025-09-30,36.599998,36.790001,36.250000,36.590000,7668000,36.590000,0.000000,2025_09

In [356]:
df_precos_historicos.loc[df_precos_historicos["Ano Mês"] == "2025_09"]#.iloc[-1, :]

,symbol,date,open,high,low,close,volume,adjclose,dividends,Ano Mês
356,PETR4,2025-09-01,31.200001,31.370001,31.049999,31.170000,9889700,31.170000,0.000000,2025_09
357,PETR4,2025-09-02,31.000000,31.440001,31.000000,31.330000,19812000,31.330000,0.000000,2025_09
358,PETR4,2025-09-03,31.120001,31.350000,30.920000,31.059999,29788800,31.059999,0.000000,2025_09
359,PETR4,2025-09-04,31.000000,31.320000,30.930000,31.059999,24816500,31.059999,0.000000,2025_09
360,PETR4,2025-09-05,31.080000,31.090000,30.190001,30.590000,46121900,30.590000,0.000000,2025_09
...,...,...,...,...,...,...,...,...,...,...
3019,WEGE3,2025-09-24,36.740002,37.090000,36.599998,36.889999,4562300,36.778034,0.000000,2025_09
3020,WEGE3,2025-09-25,36.990002,36.990002,36.110001,36.349998,8075800,36.239670,0.000000,2025_09
3021,WEGE3,2025-09-26,36.490002,36.599998,36.209999,36.320000,4491900,36.209763,0.000000,2025_09
3022,WEGE3,2025-09-29,36.970001,36.970001,36.029999,36.369999,4873200,36.369999,0.110235,2025_09
3023,WEGE3,2025-09-30,36.599998,36.790001,36.250000,36.590000,7668000,36.590000,0.000000,2025_09

In [357]:
df_precos_historicos.loc[(df_precos_historicos["symbol"] == "PETR4") & (df_precos_historicos["Ano Mês"] == "2024_04")].iloc[-1, :]["close"]

42.02000045776367

#### Calcula Lucro

In [358]:
lista_preco_fechamento = []
lista_preco_fechamento_total = []
lista_lucro = []
# lista_rendimento = []

for i in df_aquisicao_geral.index:
    ativo = df_aquisicao_geral.loc[i, "Ativo"]
    valor = df_aquisicao_geral.loc[i, "Valor"]
    cotas_acumuladas = df_aquisicao_geral.loc[i, "Cotas Acumuladas"]
    valor_investido_total = df_aquisicao_geral.loc[i, "Valor Investido Total"]
    ano_mes = df_aquisicao_geral.loc[i, "Ano Mês"]

    preco_fechamento = df_precos_historicos.loc[(df_precos_historicos["symbol"] == ativo) & (df_precos_historicos["Ano Mês"] == ano_mes)].iloc[-1, :]["close"]

    lista_preco_fechamento.append(preco_fechamento)
    lista_preco_fechamento_total.append(preco_fechamento * cotas_acumuladas)
    if cotas_acumuladas > 0:
        lucro = (preco_fechamento * cotas_acumuladas) - valor_investido_total
        lista_lucro.append(lucro)
        # lista_rendimento.append((lucro / valor_investido_total) * 100)
    else:
        lista_lucro.append(0)
        # lista_rendimento.append(0)

df_aquisicao_geral["Preço de Fechamento"] = lista_preco_fechamento
df_aquisicao_geral["Preço de Fechamento Total"] = lista_preco_fechamento_total
df_aquisicao_geral["Lucro"] = lista_lucro
# df_aquisicao_geral["Rendimento"] = lista_rendimento
df_aquisicao_geral

,Ativo,Data,Valor,Número de Cotas,Cotas Acumuladas,Dono,Preço Médio,Valor Investido,Valor Investido Total,Ano Mês,Preço de Fechamento,Preço de Fechamento Total,Lucro
0,PETR4,2024-04-01 00:00:00,32.0,1,1,Luis,32.00,32.00,32.00,2024_04,42.020000,42.020000,10.020000
1,PETR4,2024-04-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2024_04,42.020000,0.000000,0.000000
2,PETR4,2024-05-01 00:00:00,0,0,1,Luis,32.00,0.00,32.00,2024_05,38.790001,38.790001,6.790001
3,PETR4,2024-05-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2024_05,38.790001,0.000000,0.000000
4,PETR4,2024-06-01 00:00:00,0,0,1,Luis,32.00,0.00,32.00,2024_06,38.049999,38.049999,6.049999
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,WEGE3,2025-07-01 00:00:00,0,0,0,Heitor,0.00,0.00,0.00,2025_07,37.110001,0.000000,0.000000
140,WEGE3,2025-08-01 00:00:00,36.06,4,4,Luis,36.06,144.24,144.24,2025_08,37.660000,150.639999,6.399999
141,WEGE3,2025-08-01 00:00:00,36.06,4,4,Heitor,36.06,144.24,144.24,2025_08,37.660000,150.639999,6.399999
142,WEGE3,2025-09-01 00:00:00,0,0,4,Luis,36.06,0.00,144.24,2025_09,36.590000,146.360001,2.120001
143,WEGE3,2025-09-01 00:00:00,0,0,4,Heitor,36.06,0.00,144.24,2025_09,36.590000,146.360001,2.120001

In [359]:
df_aquisicao_geral["Data"] = pd.to_datetime(df_aquisicao_geral["Data"], format="%d-%m-%Y")
df_aquisicao_geral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ativo                      144 non-null    object
 1   Data                       144 non-null    datetime64[ns]
 2   Valor                      144 non-null    object
 3   Número de Cotas            144 non-null    object
 4   Cotas Acumuladas           144 non-null    object
 5   Dono                       144 non-null    object
 6   Preço Médio                144 non-null    float64
 7   Valor Investido            144 non-null    float64
 8   Valor Investido Total      144 non-null    float64
 9   Ano Mês                    144 non-null    object
 10  Preço de Fechamento        144 non-null    float64
 11  Preço de Fechamento Total  144 non-null    float64
 12  Lucro                      144 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 14.8+ KB

In [360]:
df_aquisicao_geral.to_csv("Dados Modelados/Aquisições Realizadas.csv", index=False)

## Dividendos

In [361]:
df_dividendos = pd.concat(
    [
        pd.read_csv('Dados Modelados/Dividendos pagos por data (2021-2025).csv'), 
        pd.read_csv('Dados Modelados/FIIs rendimentos por data (2021-2025).csv')
    ])
df_dividendos = df_dividendos.loc[df_dividendos['ATIVO'].isin(ativos)]
df_dividendos.rename(columns={"ATIVO": "Ativo", "VALOR": "Valor", "TIPO": "Tipo Receita", "DATA PAGAMENTO": "Data"}, inplace=True)
df_dividendos = df_dividendos.filter(["Ativo", "Data", "Valor", "DATA COM", "Tipo Receita", "DY"])
df_dividendos["Valor"] = df_dividendos["Valor"].apply(lambda x: str(x).replace(',', '.'))
df_dividendos["Valor"] = df_dividendos["Valor"].apply(
    lambda x: float(str(x).split('.')[0] + '.' + str(x).split('.')[1][:2])
)

df_dividendos["Data"] = pd.to_datetime(df_dividendos["Data"], format="%Y-%m-%d")
df_dividendos["DATA COM"] = pd.to_datetime(df_dividendos["DATA COM"], format="%Y-%m-%d")
df_dividendos.sort_values(by="Data", inplace=True)
df_dividendos

       Ativo       Data  Valor   DATA COM Tipo Receita    DY
29    HGLG11 2021-01-15   2.63 2020-12-30   Rendimento  1,45
106   HGLG11 2021-02-12   0.78 2021-01-29   Rendimento  0,43
43     WEGE3 2021-03-10   0.17 2021-02-26    Dividendo  0.22
44     WEGE3 2021-03-10   0.01 2020-09-25          JCP  0.03
45     WEGE3 2021-03-10   0.01 2020-12-21          JCP  0.03
...      ...        ...    ...        ...          ...   ...
1445  TAEE11 2025-11-27   0.63 2025-08-18          JCP  1.87
1444  TAEE11 2025-11-27   0.23 2025-08-18    Dividendo  0.68
1443  TAEE11 2025-11-27   0.32 2025-04-29    Dividendo  0.89
1454   PETR4 2025-12-22   0.20 2025-08-21    Dividendo  0.66
1455   PETR4 2025-12-22   0.13 2025-08-21          JCP  0.45

[211 rows x 6 columns]

In [362]:
df_dividendos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 211 entries, 29 to 1455
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ativo         211 non-null    object
 1   Data          211 non-null    datetime64[ns]
 2   Valor         211 non-null    float64
 3   DATA COM      211 non-null    datetime64[ns]
 4   Tipo Receita  211 non-null    object
 5   DY            211 non-null    object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 11.5+ KB

### Relaciona Dividendos com Aquisições para multiplicar o valor de dividendo pela quantidade total de cotas válidas

In [363]:
# Junta valores pelo dia

df_dividendos = df_dividendos.groupby(["Ativo", "Data", "DATA COM", "Tipo Receita"]).agg("sum")
df_dividendos = df_dividendos.reset_index()
df_dividendos

      Ativo       Data   DATA COM Tipo Receita  Valor    DY
0    HGLG11 2021-01-15 2020-12-30   Rendimento   2.63  1,45
1    HGLG11 2021-02-12 2021-01-29   Rendimento   0.78  0,43
2    HGLG11 2021-03-12 2021-02-26   Rendimento   0.78  0,44
3    HGLG11 2021-04-15 2021-03-31   Rendimento   0.78  0,44
4    HGLG11 2021-05-14 2021-04-30   Rendimento   0.78  0,45
..      ...        ...        ...          ...    ...   ...
200   WEGE3 2025-03-12 2024-12-20          JCP   0.07  0.14
201   WEGE3 2025-03-12 2025-02-28    Dividendo   0.30  0.62
202   WEGE3 2025-08-13 2025-03-21          JCP   0.08  0.17
203   WEGE3 2025-08-13 2025-06-20          JCP   0.09  0.23
204   WEGE3 2025-08-13 2025-07-25    Dividendo   0.17  0.47

[205 rows x 6 columns]

In [364]:
# Filtra apenas os dividendos válidos para as cotas adquiridas
# Separa cada dividendo por dono

df_dividendos_adquiridos = pd.merge(df_dividendos, df_aquisicao, on="Ativo", suffixes=[" Dividendos", " Aquisição"])
df_dividendos_adquiridos = df_dividendos_adquiridos.loc[df_dividendos_adquiridos["DATA COM"] >= df_dividendos_adquiridos["Data Aquisição"]]
df_dividendos_adquiridos

,Ativo,Data Dividendos,DATA COM,Tipo Receita,Valor Dividendos,DY,Data Aquisição,Valor Aquisição,Número de Cotas,Cotas Acumuladas,Dono
56,HGLG11,2025-09-12,2025-08-29,Rendimento,1.10,"0,71",2025-08-01,152.89,1,1,Heitor
267,PETR4,2024-05-20,2024-04-25,Dividendo,1.10,2.6,2024-04-01,32.00,1,1,Luis
273,PETR4,2024-05-20,2024-04-25,Rend. Tributado,0.02,0.05,2024-04-01,32.00,1,1,Luis
279,PETR4,2024-05-20,2024-05-02,Dividendo,0.84,2.02,2024-04-01,32.00,1,1,Luis
285,PETR4,2024-05-20,2024-05-02,Rend. Tributado,0.03,0.08,2024-04-01,32.00,1,1,Luis
...,...,...,...,...,...,...,...,...,...,...,...
482,TAEE11,2025-11-27,2025-08-18,JCP,0.63,1.87,2025-07-01,28.96,1,1,Luis
511,VALE3,2025-03-14,2024-12-11,JCP,0.52,0.89,2024-11-01,34.87,2,2,Luis
513,VALE3,2025-03-14,2025-03-07,Dividendo,2.14,3.79,2024-11-01,34.87,2,2,Luis
515,VALE3,2025-09-03,2025-08-12,JCP,1.89,3.39,2024-11-01,34.87,2,2,Luis
516,VALE3,2025-09-03,2025-08-12,JCP,1.89,3.39,2025-08-01,33.89,2,2,Heitor

In [365]:
df_dividendos_adquiridos = df_dividendos_adquiridos.filter(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Cotas Acumuladas', 'Dono'])
df_dividendos_adquiridos

,Ativo,Data Dividendos,Valor Dividendos,DATA COM,Tipo Receita,DY,Cotas Acumuladas,Dono
56,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",1,Heitor
267,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,1,Luis
273,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,1,Luis
279,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,1,Luis
285,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,1,Luis
...,...,...,...,...,...,...,...,...
482,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,1,Luis
511,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,2,Luis
513,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,2,Luis
515,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,2,Luis
516,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,2,Heitor

In [366]:
# Agrupa os dividendos, capturando o valor máximo de cotas do ativo válidas para multiplicar pelo dividendo

df_dividendos_adquiridos = df_dividendos_adquiridos.groupby(['Ativo', 'Data Dividendos', 'Valor Dividendos', 'DATA COM', 'Tipo Receita',
       'DY', 'Dono']).agg("max")
df_dividendos_adquiridos = df_dividendos_adquiridos.reset_index()
df_dividendos_adquiridos.rename(columns={"Data Dividendos": "Data", "Valor Dividendos": "Valor"}, inplace=True)
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Heitor,1
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Luis,1
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Luis,1
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Luis,1
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Luis,1
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Luis,1
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Luis,1
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Luis,1
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Luis,1
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Luis,1
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Luis,1
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Luis,3
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Luis,3
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Luis,3
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Luis,6
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Luis,6
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Luis,6
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Luis,6
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Luis,6
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Luis,6
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Luis,6
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Luis,6
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Luis,6
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Luis,6
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Luis,6
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Luis,6
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Luis,6
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Heitor,5
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Luis,6
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Heitor,5
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Luis,6
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Heitor,5
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Luis,6
33,RAIL3,2025-06-25,0.81,2025-06-16,Dividendo,4.15,Heitor,3
34,SUZB3,2025-01-10,2.01,2024-12-16,JCP,3.16,Heitor,2
35,SUZB3,2025-01-10,2.01,2024-12-16,JCP,3.16,Luis,2
36,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Luis,1
37,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Luis,1
38,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Luis,2
39,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Luis,2
40,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Heitor,2
41,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Luis,2

In [367]:
# Calcula dividendo total, valor x número de cotas válidas e acumula os dividendos

lista_dividendos_totais = []
# lista_dividendos_acumulados = []

dividendo_acumulado = 0
for i in df_dividendos_adquiridos.index:
    valor = df_dividendos_adquiridos.loc[i, "Valor"]
    cotas_acumul = df_dividendos_adquiridos.loc[i, "Cotas Acumuladas"]
    dividendo_acumulado += valor * cotas_acumul

    lista_dividendos_totais.append(valor * cotas_acumul)
    # lista_dividendos_acumulados.append(dividendo_acumulado)

df_dividendos_adquiridos["Dividendos Totais"] = lista_dividendos_totais
# df_dividendos_adquiridos["Dividendos Acumulados"] = lista_dividendos_acumulados
df_dividendos_adquiridos

,Ativo,Data,Valor,DATA COM,Tipo Receita,DY,Dono,Cotas Acumuladas,Dividendos Totais
0,HGLG11,2025-09-12,1.10,2025-08-29,Rendimento,"0,71",Heitor,1,1.10
1,PETR4,2024-05-20,0.02,2024-04-25,Rend. Tributado,0.05,Luis,1,0.02
2,PETR4,2024-05-20,0.03,2024-05-02,Rend. Tributado,0.08,Luis,1,0.03
3,PETR4,2024-05-20,0.84,2024-05-02,Dividendo,2.02,Luis,1,0.84
4,PETR4,2024-05-20,1.10,2024-04-25,Dividendo,2.6,Luis,1,1.10
5,PETR4,2024-06-20,0.02,2024-04-25,Rend. Tributado,0.07,Luis,1,0.02
6,PETR4,2024-06-20,0.04,2024-05-02,Rend. Tributado,0.1,Luis,1,0.04
7,PETR4,2024-06-20,0.84,2024-05-02,Dividendo,2.02,Luis,1,0.84
8,PETR4,2024-08-20,0.52,2024-06-11,JCP,1.38,Luis,1,0.52
9,PETR4,2024-09-20,0.07,2024-06-11,JCP,0.2,Luis,1,0.07
10,PETR4,2024-09-20,0.44,2024-06-11,Dividendo,1.19,Luis,1,0.44
11,PETR4,2024-11-21,0.11,2024-08-21,Dividendo,0.3,Luis,3,0.33
12,PETR4,2024-11-21,0.41,2024-08-21,JCP,1.07,Luis,3,1.23
13,PETR4,2024-12-20,0.52,2024-08-21,Dividendo,1.37,Luis,3,1.56
14,PETR4,2024-12-23,1.55,2024-12-11,Dividendo,3.86,Luis,6,9.30
15,PETR4,2025-02-20,0.01,2024-12-23,Rend. Tributado,0.03,Luis,6,0.06
16,PETR4,2025-02-20,0.66,2024-12-23,JCP,1.8,Luis,6,3.96
17,PETR4,2025-03-20,0.01,2024-12-23,JCP,0.03,Luis,6,0.06
18,PETR4,2025-03-20,0.01,2024-12-23,Rend. Tributado,0.05,Luis,6,0.06
19,PETR4,2025-03-20,0.65,2024-12-23,Dividendo,1.77,Luis,6,3.90
20,PETR4,2025-05-20,0.01,2025-04-16,Rend. Tributado,0.05,Luis,6,0.06
21,PETR4,2025-05-20,0.35,2025-04-16,Dividendo,1.13,Luis,6,2.10
22,PETR4,2025-06-20,0.02,2025-04-16,Rend. Tributado,0.07,Luis,6,0.12
23,PETR4,2025-06-20,0.35,2025-04-16,Dividendo,1.13,Luis,6,2.10
24,PETR4,2025-08-20,0.45,2025-06-02,JCP,1.45,Luis,6,2.70
25,PETR4,2025-09-22,0.14,2025-06-02,JCP,0.47,Luis,6,0.84
26,PETR4,2025-09-22,0.30,2025-06-02,Dividendo,0.99,Luis,6,1.80
27,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Heitor,5,1.65
28,PETR4,2025-11-21,0.33,2025-08-21,JCP,1.11,Luis,6,1.98
29,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Heitor,5,0.65
30,PETR4,2025-12-22,0.13,2025-08-21,JCP,0.45,Luis,6,0.78
31,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Heitor,5,1.00
32,PETR4,2025-12-22,0.20,2025-08-21,Dividendo,0.66,Luis,6,1.20
33,RAIL3,2025-06-25,0.81,2025-06-16,Dividendo,4.15,Heitor,3,2.43
34,SUZB3,2025-01-10,2.01,2024-12-16,JCP,3.16,Heitor,2,4.02
35,SUZB3,2025-01-10,2.01,2024-12-16,JCP,3.16,Luis,2,4.02
36,TAEE11,2025-11-27,0.23,2025-08-18,Dividendo,0.68,Luis,1,0.23
37,TAEE11,2025-11-27,0.63,2025-08-18,JCP,1.87,Luis,1,0.63
38,VALE3,2025-03-14,0.52,2024-12-11,JCP,0.89,Luis,2,1.04
39,VALE3,2025-03-14,2.14,2025-03-07,Dividendo,3.79,Luis,2,4.28
40,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Heitor,2,3.78
41,VALE3,2025-09-03,1.89,2025-08-12,JCP,3.39,Luis,2,3.78

In [368]:
df_dividendos_adquiridos.to_csv("Dados Modelados/Dividendos Recebidos.csv", index=False)